### ISSUE TITLE
ANW-229: Result pages in the new PUI contain invalid HTML and a faux hierarchy when a truncated note in the result set gets chopped in the middle of HTML tags

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#1006]
See:  http://dev.archivesspace.org/search?utf8=%E2%9C%93&op%5B%5D=&q%5B%5D=artifacts&limit=&field%5B%5D=&from_year%5B%5D=&to_year%5B%5D=&commit=Search

Search results http://dev.archivesspace.org/repositories/2/archival_objects/19869 and http://dev.archivesspace.org/repositories/20/archival_objects/68455 cause problems, because these records have "truncated notes" that contain HTML.  If you remove the html_safe method from this line, https://github.com/archivesspace/archivesspace/blob/master/public/app/views/shared/_result.html.erb#L23, you'll see the problem, since the notes will trail off somewhere like "\<li> i'm some list text... "

I don't know of any easy fix for this that would retain the HTML when the notes are truncated.  Previously we had the "see more / see less" javascript in the search results, but I think that still needs to be refined overall to be useful.  The only quick fix that I see is to change line 23 to something like this:

<%= strip_tags(truncated_note[0..end_index]) %>

Alternatively, there might be some luck in testing for HTML characters, and if so, conditionally changing line 22 to something like this:

<% end_index = truncated_note.rindex(' <') || 499 %>

But that would be more work, and probably wouldn't fix the problem (and you wouldn't always want to do that, otherwise the truncation could occuring the middle of words... e.g. "more descri...").

Anyhow, I don't see much value in having the HTML in the search results, so just stripping them altogether with the "strip_tags" method, or whatever is desired by the developers, should be fine.  Far better to not have links and styling in the search results than to have the ultra-malformed HTML, I'd think.

**Comment by cdibella** [comment]
@fordmadox - thanks for all the sleuthing on this. Does this sound like the issue described at https://archivesspace.atlassian.net/browse/ANW-229? There's an example from University of Minnesota's PUI in the description.

**Comment by fordmadox** [comment]
Yes, @cdibella that's the exact same problem.  Too bad I didn't see the ticket, otherwise Cory's note from 10/13 would've saved me some time!
