### ISSUE TITLE
1.1.0 will not run under Java 1.8 (?)

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/archivesspace#105]
Trying to install version 1.1.0 on Mac OS running Mavericks and Java 1.8.0_05, the startup script fails with this error from the backend:

```
load error: ./app/main -- net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expressions class file:
1. The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
                value = "" + StringUtils.join( ((java.lang.String)field_identifier.getValue()).replaceAll("null", "").replace("\"","").replace("[","").replace("]","").split(","), '-'); //$JR_EXPR_ID=9$
```

Running on a Linux box with Java 1.7.0_51 works fine. Found this, which seems to be related to this error:
http://stackoverflow.com/questions/24301986/the-type-java-lang-charsequence-cannot-be-resolved-in-package-declaration

**Comment by cfitz** [comment]
This has been resolved, as the new version of jasper works with java 8
