### ISSUE TITLE
Plugin assets not loading when running AS under Tomcat

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/archivesspace#108]
When running AS under Tomcat, files in a plugin's assets directories fail to load. Plugins work without problems when running under Jetty.

Confirmed with LCNAF plugin.

I'm running 1.1.0 - not sure if the same issue was present under 1.0.9.

**Comment by quoideneuf** [comment]
I'm closing this based on the comments ¯\_(ツ)_/¯
