### ISSUE TITLE
"incompatible encodings: UTF-8 and ASCII-8BIT" re: subnote text

### ISSUE THREAD

**Issue by bsl** [archivesspace/archivesspace#1088]
_single_note.html.rb: `subnote['_text'].html_safe`

If `subnote['_text']` contains characters like "—" (em dash, U+2014, e2 80 94), the view crashes with "ActionView::Template::Error (incompatible encodings: UTF-8 and ASCII-8BIT)".

**Comment by mark-cooper** [comment]
Fixed for next release: https://github.com/archivesspace/archivesspace/commit/3aa600169e2a78f9068195980ef2c83edcb228a5
