### ISSUE TITLE
DigitalObjectListTableReport should be repository scoped

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#1109]
DigitalObjectListTableReport should be repository scoped, but it's global.

**Comment by sdm7g** [comment]
#1109

**Comment by sdm7g** [comment]
Also noting here that all reports, even those that are globally scoped resources, say "Scoped for Repository: " $current_repo  at the bottom.

**Comment by sdm7g** [comment]
Note: This is still a bug in 2.3.0-RC1

**Comment by lmcglohon** [comment]
Fixed by #1110 and #1125. Will be included in v2.3.1.
