### ISSUE TITLE
OutOfMemory (PermGen) Error

### ISSUE THREAD

**Issue by seth-shaw-unlv** [archivesspace/archivesspace#1114]
After a migration from 1.5.4 to 2.2.0 we are experiencing OutOfMemoryErrors (PermGen) after 11-14 days even after increasing the default MaxPermGen Java Opt. This suggests a memory leak, although the question is *where*.

A work-around is to periodically (weekly) restart the application.

**Comment by cfitz** [comment]
@seth-shaw-unlv  yes, i've had this problem as well. 
My guess would be the indexer. It's having to do a lot more work to service the features of the public UI. What can be happening is that the indexer is unable to complete a total or large reindex and is crashing then restarting. 

Can you tell if you're indexer is completing? Currently its a bit hard to tell, but there should be a large amount of .dat files in both the data/indexer_pui_state and the data/indexer_state directories.

**Comment by seth-shaw-unlv** [comment]
As far as I can tell the indexer is working. We only use the staff interface right now, so the public interface is rarely touched.

Tail of the log this morning shows:
```
Staff Indexer [2018-01-29 08:29:02 -0800] Running index round
Staff Indexer [2018-01-29 08:29:02 -0800] Index round complete
PUI Indexer [2018-01-29 08:29:29 -0800] Running index round
PUI Indexer [2018-01-29 08:29:29 -0800] Index round complete
Staff Indexer [2018-01-29 08:29:32 -0800] Running index round
Staff Indexer [2018-01-29 08:29:33 -0800] Index round complete
PUI Indexer [2018-01-29 08:29:59 -0800] Running index round
PUI Indexer [2018-01-29 08:30:00 -0800] Index round complete
Staff Indexer [2018-01-29 08:30:03 -0800] Running index round
Staff Indexer [2018-01-29 08:30:04 -0800] Index round complete
```
The directories you mentioned show:
```
indexer_pui_state:
total 32
11 Jan 29 08:26 2_archival_object.dat
11 Jan 29 08:26 2_classification.dat
11 Jan 29 08:26 2_classification_term.dat
11 Jan 29 08:26 2_digital_object_component.dat
11 Jan 29 08:26 2_digital_object.dat
11 Jan 29 08:26 2_resource.dat
11 Jan 29 08:26 _deletes_deletes.dat
11 Jan 29 08:26 repositories_repositories.dat

indexer_state:
total 64
11 Jan 26 16:03 2_accession.dat
11 Jan 26 16:28 2_agent_corporate_entity.dat
11 Jan 25 12:41 2_agent_family.dat
11 Jan 26 16:28 2_agent_person.dat
11 Dec 11 09:16 2_agent_software.dat
11 Jan 26 16:27 2_archival_object.dat
11 Jan 26 16:28 2_classification.dat
11 Apr 11  2017 2_digital_object_component.dat
11 Dec 11 09:16 2_digital_object.dat
11 Jan 26 14:02 2_event.dat
11 Dec 11 09:16 2_location.dat
11 Jan 26 16:28 2_resource.dat
11 Jan 26 16:28 2_subject.dat
11 Jan 26 16:28 2_top_container.dat
11 Jan 29 08:26 _deletes_deletes.dat
11 Jan 29 08:26 repositories_repositories.dat
```

**Comment by cfitz** [comment]
@seth-shaw-unlv 
hm that look fine, but if you're not using the PUI, I would turn them off and see if that resolves the problem...that will at least narrow you're suspects. Set pui_indexer_enabled and enable_public to false in the config and restart.

**Comment by lmcglohon** [comment]
@seth-shaw-unlv Are you still experiencing this issue?

**Comment by seth-shaw-unlv** [comment]
We began restarting the application weekly about this time. We haven't run into it since then.
