### ISSUE TITLE
Seperate vs. Separate in the XSL-FO output (very minor issue)

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#1116]
Just a note that it should be "separate" in lines:

https://github.com/archivesspace/archivesspace/blob/master/stylesheets/as-ead-pdf.xsl#L105
https://github.com/archivesspace/archivesspace/blob/master/stylesheets/as-ead-pdf.xsl#L117

ASpace doesn't support tables, though, so those elements have to be hardcoded as mixed content.

**Comment by cdibella** [comment]
I fixed these typos, though haven't touched the underlying issue with support for tables that @fordmadox notes.
