### ISSUE TITLE
Tomcat setup script does not copy stylesheets directory

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/archivesspace#114]
Running AS under Tomcat we were unable to export EAD to PDF due to this error:
(RuntimeError) {"error":"File not found: as-ead-pdf.xsl in []"}

Copied the stylesheets directory from the main install location to the Tomcat directory and this fixed the problem. This should probably be added to the Tomcat setup script.

**Comment by cfitz** [comment]
Added this to the configure-tomcat script. Will be available on next release.
