### ISSUE TITLE
Successful posts to "/config/enumeration_values/:enum_val_id/position" do not return JSON responses

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1163]
This issue was found using ArchivesSpace version 2.2.2. Looking at the blame history of `archivesspace/backend/app/controllers/enumeration.rb` controller, it appears that this has been an issue since the feature was created and is still an issue. Below is a screenshot of what I'm seeing when I send a successful POST to this endpoint of the ArchivesSpace API, using the Insomnia REST/HTTP client.

![image](https://user-images.githubusercontent.com/16184219/37677957-fa661bca-2c52-11e8-9ecf-d9f4a5999c38.png)
![image](https://user-images.githubusercontent.com/16184219/37678153-9ab92266-2c53-11e8-9263-b6e666a4fc91.png)

On the other side, POSTs to this enpoint that fail come back with valid JSON.

![image](https://user-images.githubusercontent.com/16184219/37678106-762f76fc-2c53-11e8-865c-d89e399b6936.png)
![image](https://user-images.githubusercontent.com/16184219/37678126-841bb442-2c53-11e8-8be4-e10404ed4661.png)

This appears to be relevant line of the controller: https://github.com/archivesspace/archivesspace/blob/e8c6e6ed96cf7497060b4008565e250ebbadb6a1/backend/app/controllers/enumeration.rb#L91

**Comment by trevorthornton** [comment]
Have you tried the same endpoint with an integer value for position, like:
/config/enumeration_values/931/position?position=1

On Tue, Mar 20, 2018 at 3:37 PM, Austin T Schaffer <notifications@github.com

**Comment by AustinTSchaffer** [comment]
@trevorthornton 

Yes, I sent various different POSTs, each with at least one of the following.

- a valid integer position as a query string parameter 
- a valid integer position as a form-url-encoded parameter
- a valid integer position as a multipart-form parameter

I'm randomizing the order of enumeration 40 in a script. When the POSTs have all the correct information, including a valid `X-ArchivesSpace-Session`, the API responses come back as something resembling `<#EnumerationValue0x0123456789abcdef>`. When I go to http://my.base.url:8080/enumerations?id=40, I can see that the order of the enumerations is being successfully updated.

**Comment by cfitz** [comment]
It just needs to call to_jsonmodel on the response being returned by the controller.

**Comment by AustinTSchaffer** [comment]
@cfitz 

Oh ok, that seems easy enough of a fix. Will that just return a JSON representation of the object, after it has been updated?

I wasn't sure if this endpoint should be returning a response similar to the POST an update endpoints, something like:

```
{"stale": null, "warnings": [], "status": "Updated", "uri": "/config/enumeration_values/931", "id": 931, "lock_version": 11}
```

**Comment by cfitz** [comment]
@AustinTSchaffer  yeah, I think it's "trying" to just return the json representation...I added something to call the to_jsonmodel with a reloaded version of the record from the DB. 
Yeah, I guess that'd be enough or is there something that might be more relevant?

**Comment by AustinTSchaffer** [comment]
@cfitz 

Just sending back the object is probably fine, since it'll have the uri and lock_version, and the EnumVal records are small. It does seem like most of the other "POST an update" endpoints use the `updated_response(*opts)` response.

(https://github.com/archivesspace/archivesspace/blob/14dac8f07b7b1a543f96ca6bd22b8f46e21d1a02/backend/app/lib/rest.rb#L30)

**Comment by cfitz** [comment]
Heh, yeah I think "most" do, but some don't...it might be best to make it's own response in the rest.rb? Similar to moved_response or suppressed_response? Something like:
json_response({:status => 'Position Updated', :id => enumeration_value_id, :position => new_position })

It seems like getting back a verification of the new position would be helpful.

**Comment by AustinTSchaffer** [comment]
I like that a lot better than the default `:status=>'Updated'` response, and it seems in-line with the existing `moved_response`, `suppressed_response`, and `deleted_response`. How does this look to you?

```ruby
def new_position_response(id, new_position)
    json_response({:status => 'Position Updated', :id => id, :position => new_position})
end
```

Do you know if there are any other objects in ArchivesSpace that are explicitly ordered, similarly to enumeration_values?

**Comment by cfitz** [comment]
I think that looks good to me. FYI - I did update the PR to just use the modified_response.

There are other controllers that use position, but there's a wrinkle where all of those ( i think ) also provision changing the parent...like ArchivalObjects, which can have a series of nested lists, so I'm not sure the response would be the same, since you have to allow for re-parenting.
