### ISSUE TITLE
"/config/enumerations/migration" does not respect the enumeration's :editable status

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1167]
**Problem**

It seems that the `/config/enumerations/migration` API endpoint should not allow EnumerationValue merges, if the referenced Enumeration is not editable. Using this endpoint, it's possible to delete EnumerationValues from Enumerations that have `false` as the value for their `editable` property.

**Steps to reproduce**

1. The `file_version_xlink_show_attribute` enumeration is not an editable enumeration, based on the enumeration's record. In my testing instance of ArchivesSpace, this enumeration has the enumeration id of 40. 
2. When I attempt to post an update to the enum's `values` array, removing the value `"new"`, the server responds with an "Access denied" error.
3. When I attempt to merge/migrate the enumeration_value `"new"` to enumeration_value `"other"`, the server returns a copy of the record, with the value "new" no longer in the enumeration's `"values"` and `"enumeration_values"` arrays. Running a `GET /config/enumerations/40` confirms that the value no longer exists for enumeration 40.
4. Now that the enumeration_value `"new"` no longer exists within enumeration 40, there is no way to put it back through the API.

**GET /config/enumerations/40 | Initial GET**
```json
// Response
{
	"lock_version": 31,
	"name": "file_version_xlink_show_attribute",
	"editable": false,
	"jsonmodel_type": "enumeration",
	"values": ["replace", "other", "embed", "new"],
	"readonly_values": [],
	"uri": "/config/enumerations/40",
	...
}
```

**POST /config/enumerations/40 | Deleting a value by posting an array without the value**
```json
// Post Data
{
	"lock_version": 31,
	"name": "file_version_xlink_show_attribute",
	"editable": false,
	"jsonmodel_type": "enumeration",
	"values": ["replace", "other", "embed"], 
	"readonly_values": [],
	"uri": "/config/enumerations/40",
	...
}

// Response
{"error": "Access denied"}
```

**POST /config/enumerations/migration | "Deleting" a value by merging it with another**
```
// Post Data
{"enum_uri": "/config/enumerations/40", "from": "new", "to": "other"}

// Response
{
	"lock_version": 31,
	"name": "file_version_xlink_show_attribute",
	"editable": false,
	"jsonmodel_type": "enumeration",
	"values": ["replace", "other", "embed"],
	"readonly_values": [],
	"uri": "/config/enumerations/40",
	...
}
```

**POST /config/enumerations/40 | Trying to add the value back**
```json
// Post Data
{
	"lock_version": 31,
	"name": "file_version_xlink_show_attribute",
	"editable": false,
	"jsonmodel_type": "enumeration",
	"values": ["replace", "other", "embed", "new"], 
	"readonly_values": [],
	"uri": "/config/enumerations/40",
	...
}

// Response
{"error": "Access denied"}
```

**Comment by lorawoodford** [comment]
Appears to be resolved by #1834
