### ISSUE TITLE
frontend and public broken in master with jruby-complete-9.1.16.0.jar 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#1224]
Both frontend and public  devservers fail using jruby-complete-9.1.16.0.jar in current master.
( running in development mode on Mac -- not sure if that is significant. ) 

`[java] F, [2018-04-24T12:27:42.093437 #24371] FATAL -- : NotImplementedError (utimensat unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries):
`

It would appear to be due to a JRuby issue:
[File.utime failing with JRuby 9.1.16.0 #5075](https://github.com/jruby/jruby/issues/5075)

This appears to be fixed in  [jruby-9.1.17.0](http://jruby.org/2018/04/23/jruby-9-1-17-0.html)

**Comment by lmcglohon** [comment]
Fixed by #1225
