### ISSUE TITLE
search on keyword will fail when it includes a record with an event

### ISSUE THREAD

**Issue by kogugg** [archivesspace/archivesspace#124]
We have a fresh install of v1.1.0, with the aspace-110-plugin included.  We noticed that the top search will display an error message ("We're sorry, but something went wrong") if the resultset includes any record with an event.  When we take off the event from the record, the search works fine.  Or if we do an advanced search based on the title or anything other than keyword, it works fine.    

Just to clarify - we are not searching on the event itself, or any information within the event, we are searching for accession and resource records, but if those records have events, an error message is displayed. 

![search error message](https://cloud.githubusercontent.com/assets/8290098/5384698/afcf250c-8089-11e4-84e8-576fda8571d3.png)

**Comment by cfitz** [comment]
Hi, I still haven't been able to replicate this bug. Have you tried this on v1.1.2?

**Comment by cfitz** [comment]
Closing, since this cannot be replicated.
