### ISSUE TITLE
Archival objects fail to display when created via API.

### ISSUE THREAD

**Issue by rferris** [archivesspace/archivesspace#1254]
It seems that if you send an api POST to/repositories/:repo_id/archival_objects and fail to inculude "publish": false in your json there will be a NULL entry in publish column in the archival_object db table - which will cause the front end to not display this item in the tree. 

However, if you try to fetch the tree via /repositories/:repo_id/resourcs/:id/tree it will display as "publish": false - even though the front end is not happy with the actual underlying data.

**Comment by lorawoodford** [comment]
Hi Rohan,

This issue should be resolved with this PR I put in in April: https://github.com/archivesspace/archivesspace/pull/1208 . It's been included in the 2.4 release candidate that was put out last week (https://github.com/archivesspace/archivesspace/releases/tag/v2.4.0-RC1), so feel free to give it a try.  Feedback always welcome.

Best,

Lora

**Comment by lmcglohon** [comment]
@rferris I believe this was fixed (see note from Lora on Jun4). So I am going to close this issue. If you believe this is still a problem, please reopen this issue with information about why you believe the issue has not been fixed. Best, Laney
