### ISSUE TITLE
Intermittent failures during startup

### ISSUE THREAD

**Issue by kardeiz** [archivesspace/archivesspace#1262]
The startup process for ArchivesSpace 2.3.1 seems really fragile. Roughly 75% of the time, AS will get stuck or something will fail during startup. The rest of the time, AS starts up fine and runs normally.

The two most common issues I've noticed:

Getting stuck at initial database connection:

    I, [2018-06-01T09:05:03.940264 #17011]  INFO -- : Thread-2000: Connecting to database: jdbc:mysql://<redacted>. Max connections: 28

It hangs at this step indefinitely.

And two, some weird error during the Rails loading phase:

    ActionController::RoutingError (uninitialized constant ActiveSupport::Dependencies
      Did you mean?  ActiveSupport::Dependencies):

Which leads to a lot of:

    E, [2018-06-01T09:02:09.423236 #15978] ERROR -- : [4cb87a08-9002-4332-80f0-6922088df3c7] Net::ReadTimeout

We never encountered these issues with 1.5.x. 

Any thoughts? Thanks!

**Comment by kardeiz** [comment]
Thanks for the questions!

Java 8 (`1.8.0_161`)
RedHat 7.4
mysql-connector-java-5.1.26

**Comment by cfitz** [comment]
Hm. Ok...might try and bump the mysql connector version up to a newer one in the 5.x.x release? 

I've seen some MySQL setups where the issue was the number of connections to a single user was limited, which caused problems for aspace, but if you didn't see that in the earlier aspace versions, I don't think that would be the problem here...

**Comment by kardeiz** [comment]
Thanks! I'll try updating the driver...

**Comment by kardeiz** [comment]
Thanks again! I've only restarted a few times after updating the driver, but haven't had any issues so far. I'll go ahead and close this.
