### ISSUE TITLE
problems with plugin gem initialization and Gemfile changes in v2.4.0 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#1268]
See https://github.com/harvard-library/aspace-import-excel/issues/33

The conditional blocks in Gemfiles for including pry gems in :development appears to cause a problem with plugins that also include pry.  The bundler seems to think there are duplicate versions specified, but there is only one version installed, and startup fails.

**Comment by lmcglohon** [comment]
@sdm7g I think this has been resolved so I am closing this issue. Please reopen this if you think it hasn't been resolved.
