### ISSUE TITLE
Newly added GC opts can conflict with existing deployments #1285

### ISSUE THREAD

**Issue by mark-cooper** [archivesspace/archivesspace#1289]
#1285 introduces a variable to set GC which can crash a deployment with (now) conflicting settings applied through `JAVA_OPTS`. As the latter is a standard for configuring JAVA environments it seems (to me at least) a bad precedent to continually add app specific variables to accomplish what can already be done in a well trodden way.

```txt
Jun 24 02:20:39 as-yale-dev c5b874ee36b3[1244]: Conflicting collector combinations in option list; please refer to the release notes for the combinations allowed
Jun 24 02:20:39 as-yale-dev c5b874ee36b3[1244]: Error: Could not create the Java Virtual Machine.
Jun 24 02:20:39 as-yale-dev c5b874ee36b3[1244]: Error: A fatal exception has occurred. Program will exit.
```

Perhaps better documentation on how to configure a java environment (using `JAVA_OPTS`) is preferable to creating bespoke vars (which will anyway have to be documented)? That more freely allows an implementer to configure the environment to their preference without having to be aware of custom options.

**Comment by cfitz** [comment]
Hm. Yeah I was just following the precedent that was set with the ASPACE_ environment variables, which I'm not crazy about. 

I did put something in the TUNING_README.md about this setting, but that's probably not very helpful. 
Maybe it would be better to do something to check if the JAVA_OPTS has this settings first, then add if it's not there? 
My guess is that >90% of the active installs don't have any GC settings but 99.9% of them would benefit from it.

**Comment by mark-cooper** [comment]
Yeah, it's sort of a tricky one. I think the ASPACE_ approach isn't ideal -- where does it end? How many ASPACE_ vars are too many before it becomes a mess of figuring what options exist, what the default values are, and whether to override them?

"Maybe it would be better to do something to check if the JAVA_OPTS has this settings first, then add if it's not there?"

That actually sounds really good to me, and a sensible way to apply defaults. If it's not defined then use the defaults otherwise let an implementer completely override the defaults by supplying their own values. It would be easy to derive from the defaults, and there's only a single env var to manage which is a standard one for java environments anyway. If I supply my own JAVA_OPTS I get exactly what I expect otherwise I get the defaults that ArchivesSpace supplies. Can't think of an obvious downside (multiple aspace installs or alongside other java apps under a single user account maybe ... and if that's a real concern I'd still prefer something like `ASPACE_OPTS` to a proliferation of `ASPACE_*` vars).

**Comment by lorawoodford** [comment]
Closing per @mark-cooper
