### ISSUE TITLE
ArchivesSpace Docker containers report their version as HEAD

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1305]
ArchivesSpace reports its own version as `HEAD` whenever you run the `archivesspace/archivesspace` Docker image, regardless of whether you set up the Docker container with MySQL, or just use the Apache Derby testing database.

This appears to be the case for true for the Docker images for ArchivesSpace versions 2.3.2, 2.4.0, and 2.4.1. I have not tried the images for versions 2.3.1 or earlier. The version shows as HEAD in the '/' endpoint of the API, the staff interface, and the public interface.

**API**

```bash
$ docker run --detach --name example_aspace_container archivesspace/archivesspace:2.3.2
$ # Some time Later
$ docker container exec example_aspace_container curl http://localhost:8089
{
  "databaseProductName": "Apache Derby",
  "databaseProductVersion": "10.12.1.1 - (1704137)",
  "ruby_version": "2.3.0",
  "host_os": "linux",
  "host_cpu": "x86_64",
  "build": "java1.7",
  "archivesSpaceVersion": "HEAD"
}
```

**Staff Interface**

![image](https://user-images.githubusercontent.com/16184219/42818328-8f729948-899e-11e8-972d-4e5b2ab2d0c6.png)

**Public Interface**

![image](https://user-images.githubusercontent.com/16184219/42818364-afd8b8ca-899e-11e8-869c-77404e5058fd.png)

**Comment by AustinTSchaffer** [comment]
Additionally, using the '/version' endpoint returns: `ArchivesSpace (HEAD)`

**Comment by mark-cooper** [comment]
Should be addressed by: https://github.com/archivesspace/archivesspace/pull/1307

**Comment by lmcglohon** [comment]
Closing because #1307 has been merged into master
