### ISSUE TITLE
Spawning Resources from Accessions and  pre-populated fields

### ISSUE THREAD

**Issue by stothert** [archivesspace/archivesspace#1306]
We have created a resource template that includes 8 notes that we don't want staff to forget to add to resources. These show up for all users with "Pre-populate Records?" selected in their repository preferences. Unfortunately if you spawn a resource from an accession none of those fields populate.

**Comment by lmcglohon** [comment]
Related JIRA tickets - https://archivesspace.atlassian.net/browse/ANW-725 and https://archivesspace.atlassian.net/browse/ANW-616

**Comment by lorawoodford** [comment]
Closing as a duplicate of the above mentioned JIRA tickets.
