### ISSUE TITLE
Non-administrators can't batch edit locations

### ISSUE THREAD

**Issue by kloor** [archivesspace/archivesspace#1351]
Repository Managers in our system have been confused because a "Edit Batch" button appears above the list of locations, but it is disabled and there are no checkboxes next to the locations to check and enable it.

It appears that this is because the checkboxes are only displayed if the user has the `administer_system` permission: https://github.com/archivesspace/archivesspace/blob/master/frontend/app/views/locations/index.html.erb#L3

This happened as part of the commit for AR-833, which added the ability to for system administrators to bulk delete locations:
https://github.com/archivesspace/archivesspace/commit/b27411fff94c7c65528eb4216f413ca9dc494aa6#diff-94b2140f695e02f9579497f0c7beb904

It seems to me that the checkboxes should still be displayed regardless, or at least if the user has `update_location_record` permissions.

**Comment by pobocks** [comment]
@lmcglohon Pinging this because it's a notable issue round my place of work, and it's a one-line fix that I am happy to do a PR for.
