### ISSUE TITLE
Valid EAD imported, malformed EAD exported due to implicit paragraphs.  (v1.1.2) 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#137]
[link to user_group email](http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2015-February/001174.html) because pasting the text seems to not play well with Markdown support. 

The summary is that implicit paragraphs in the text get exported as `<p>...</p>` tags without
regard to existing markup tags in text. Result is malformed XML: 

```
<p><blockqoute></p><p></blockquote></p>
```

**Comment by cfitz** [comment]
Hi,

Yes, so <p> tags are kinda a bugbear in Aspace. If you can come up with a solution that doesn't break anything, we'd be happy to accept a pull-request.

**Comment by mark-cooper** [comment]
@sdm7g do you know if this one is still an issue?

**Comment by lmcglohon** [comment]
Closed during review with HM.
