### ISSUE TITLE
Collection Organization Links in Collection Organization tab do not return data

### ISSUE THREAD

**Issue by quist00** [archivesspace/archivesspace#1400]
## Expected Behavior

When in  collection organization tab of a collection , tree of links  on right should populate div on left with pertinent information.
## Current Behavior

Address bar changes, but no data is loaded.  

## Steps to Reproduce (for bugs)

When in  collection organization tab of a collection (http://archives.fullerton.edu/repositories/5/resources/62/collection_organization), tree of links  on right should populate div on left with pertinent information (e.g. http://archives.fullerton.edu/repositories/5/resources/62/collection_organization#tree::archival_object_6472) 
Address bar changes, but no data is loaded.  This is in contrast to the behavior witnessed when you use the similar tree of links from the collection main screen (http://archives.fullerton.edu/repositories/5/resources/62) where the link address is to
http://archives.fullerton.edu/repositories/5/archival_objects/6472, and the data loads into a new page.

## Your Environment

* Version used: 2.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): 70.0.3538.77 (Official Build) (64-bit), Firefox 63.0.1 (64-bit)
* Operating System and version (desktop or mobile): windows 10
* Link to your project: http://archives.fullerton.edu

**Comment by cdibella** [comment]
Hello @quist00 - typically when these areas get out of whack, your site either needs to be reindexed, or there's something in the data that is preventing reindexing. Have you tried reindexing? 

Cal State Fullerton is an ArchivesSpace member institution, so if you need help, feel free to contact us at ArchivesSpaceHome@lyrasis.org and we can connect you with more in-depth technical support.

**Comment by quist00** [comment]
I have not.  Since it was present via one list, I assumed indexing was not a factor, but I will try that and report back.  It will be great if that is all it is.

Thanks,

David Palmquist
