### ISSUE TITLE
Archivesspace 2.5.1 (Your session expired due to inactivity)

### ISSUE THREAD

**Issue by tpegues2** [archivesspace/archivesspace#1401]
When I login to archivespace, I am getting the message:  "Your session expired due to inactivity"
## Expected Behavior
I expected I should just be able to login and not kicked out after being authenticated.

## Current Behavior

Not able to access screen after successful login.
## Steps to Reproduce (for bugs)

1. Go to the archivesspace home page and login under staff.
2. https://websitename/staff/login
3. Type in username and password and then press enter.
4. Message appears second later: "Your session expired due to inactivity."

## Context

This is an initial installation and staff members need to be able to login for admin work.

## Your Environment

* Version used:2.5.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Vmware
* Operating System and version (desktop or mobile): RedHat Release 7
* Link to your project:

**Comment by cdibella** [comment]
Hello @tpegues2 - filing an issue in our github repository is best done when there is a change in the code needed or to report a systemic bug. (What you're reporting is not being experienced across installed v2.5.1 ArchivesSpaces.) Although our github participants have a great deal of technical knowledge, they can't typically troubleshoot an installation this way. You'll likely get better results emailing us at ArchivesSpaceHome@lyrasis.org or joining the ArchivesSpace Google Group at https://groups.google.com/forum/#!forum/archivesspace and posting your question there.

**Comment by tpegues2** [comment]
Hi Christine,

We did find a work around but we weren’t sure if we should report it as a bug or the best way to get it resolved.

========================================
Hi Blake--
We were able to fix the issue by setting the following settings in config.rb and restarting ArchivesSpace:
* AppConfig[:session_expire_after_seconds] = -1
This let me log in without being kicked out due to “inactivity” immediately. Once I set these back to the default values, the problem returned.
I’m not sure where to go from here. Do we submit a bug report?
- Gilberto Miralla-Flores
===========================

Happy Thanksgiving!!!


Tharrow Pegues
