### ISSUE TITLE
Proxy Runtime Error

### ISSUE THREAD

**Issue by HowtoGravity** [archivesspace/archivesspace#1426]
I'm trying to set up ArchivesSpace(2.5.1) under a prefix. But I can't get it to work. I've tried following the direction [https://github.com/archivesspace/archivesspace/blob/master/README_PREFIX.md](https://github.com/archivesspace/archivesspace/blob/master/README_PREFIX.md) but that gives me this error:
WARNING: FAILED org.eclipse.jetty.server.Server@54c5c875: java.net.BindException: Address already in use
java.net.BindException: Address already in use

I've checked the ports and nothing seems to be using it.
My configuration for ArchivesSpace:
![screen shot 2018-12-15 at 10 51 48 am](https://user-images.githubusercontent.com/29865651/50045467-e4f69c80-0058-11e9-838c-f41515f2fac9.png)

I've also tried this way:
![annotation 2018-12-15 101236](https://user-images.githubusercontent.com/29865651/50045474-0e172d00-0059-11e9-9a00-60d66b6aba20.jpg)

And I get this error:
![annotation 2018-12-15 100855](https://user-images.githubusercontent.com/29865651/50045136-7e22b480-0053-11e9-8db9-cb5610bbb153.jpg)

/etc/apache2/sites-enabled/000-default.conf file
![annotation 2018-12-15 102005](https://user-images.githubusercontent.com/29865651/50045167-f38e8500-0053-11e9-8cb7-9aa5ca0b9feb.jpg)

**Comment by HowtoGravity** [comment]
Yea, i tried it both ways just to verify what the issue was and it did end up failing both ways. But i did eventually find the issue. The issue was that I set :8080, :8081 in the config file, where you are suppose to put the URL of each port, and in Apache and they were conflicting with each other, and by commenting out :8080, :8081 in the config file it seems to work somewhat.

The other issue i am having now is that my stylesheet isn't working, none of my css are there for my staff webpage, and a few seems to be working for the public interface.

**Comment by HowtoGravity** [comment]
And there were a couple of Apache things i need to enable as well
`sudo a2enmod proxy`
`sudo a2enmod proxy_http`

**Comment by cfitz** [comment]
Ok. Can you post your config.rb that you're working with now?

**Comment by HowtoGravity** [comment]
I haven't changed much in the config.rb file the only things I've changed are on line 17, 206 & 208.

The CSS only stops working when I switch it to proxy. So when i turn off proxy the css comes back.

[config.zip](https://github.com/archivesspace/archivesspace/files/2690902/config.zip)

**Comment by cfitz** [comment]
So what happens if you have:

`
AppConfig[:frontend_proxy_url] = 'http://aspace.myarchive.org/staff' 
AppConfig[:public_proxy_url] = 'http://aspace.myarchive.org/public' 
`

instead of http://localhost. And what URL is the browser trying to resolve for the css?

**Comment by cfitz** [comment]
In your browser, open the developer toolbar and load the page. You should see some 404 errors when the browser tries to go the URL that's not being handled correctly by the proxy.

**Comment by HowtoGravity** [comment]
Yea i see the 404 errors. It says that it cant be found. Any idea as to why it cant be found?

**Comment by cfitz** [comment]
Your proxy is not routing it correctly. What are the 404 URLs and what's your proxy configuration look like?

**Comment by HowtoGravity** [comment]
The things I blacked out are the IP address of the box I'm running off of. 

![annotation 2018-12-18 100425](https://user-images.githubusercontent.com/29865651/50166269-524e3b80-02ac-11e9-89ac-cbdcd0ac6d59.jpg)

**Comment by cfitz** [comment]
The bit that you're blacking out doesn't have a port number in it, correct? 
What's theme.css? Is that something you're adding?

**Comment by HowtoGravity** [comment]
yes it's just the IP there is no port number. theme.css is something that I did add when i was making css changes. Is there somewhere i need to add that so it can be seen?

Contents of themes.css
![annotation 2018-12-18 134735](https://user-images.githubusercontent.com/29865651/50178966-7e2ce980-02cb-11e9-9df8-e71a92919b92.jpg)

**Comment by HowtoGravity** [comment]
theme.css isn't being applied to the `/public` either. Could it be that I didn't put it in the correct directory that's why it can't see that css? If that's the case what directory should it be located in, because right now it's located in `archivesspace-2.5.1/public/app/assets/stylesheets` & `archivesspace-2.5.1/frontend/app/assets/stylesheets`

**Comment by cfitz** [comment]
Ok, so, how are you adding this theme.css file? You're including it as a plugin? Or are you doing your own custom build?

**Comment by cfitz** [comment]
Ok, so the plot thickens! 

I would strongly suggest not using a custom build unless you absolutely have to.
Themes and CSS changes can be done as a plugin ( there some documentation at  https://github.com/archivesspace/archivesspace/blob/v2.5.1/CUSTOMIZING_THEMING.md about this). 
But, either way, you need to make sure you're adding the proxy prefixes to any assest includes your using. Check how you're including the theme.css and make sure it's having the path put in front of it...
