### ISSUE TITLE
API query endpoint to get resource by eadid

### ISSUE THREAD

**Issue by jronallo** [archivesspace/archivesspace#145]
The external id we use for filenaming during digitization and some of our workflows is the eadid. In looking through the API documentation I could not find a way to make a query to the API and return the resource with a given eadid. If this is not there, could such an endpoint be added? Seems common to use the eadid as the main external identifier for looking things up and that this would be a beneficial API endpoint for others.

**Comment by quoideneuf** [comment]
Hi Jason,

I think you can do what you want using the search API. For example, if you want a resource with ead_id=FOO:

/search?type%5B%5D=resource&page=1&filter_term%5B%5D=%7B%22ead_id%22%3A%22FOO%22%7D

Brian

**Comment by jronallo** [comment]
@quoideneuf Thank you for the tip. I see now that I can get the resource this way. It still seems like a common enough query that it calls for a simpler request. If I am searching for a unique resource why do I need to do a query that includes a page number and then have my results returned as an array?

**Comment by quoideneuf** [comment]
@jronallo - There certainly wouldn't be a lot of difficulty in adding a special endpoint to resolve ead_id. It's one of several "unique identifiers" for resources ASpace, so it's probably hasn't been missed because of the redundancy.

**Comment by jronallo** [comment]
@quoideneuf OK, I just thought there might be some syntactic sugar to make the API a bit simpler to use. Thank you point me to something that got me going again.
