### ISSUE TITLE
403 Forbidden Error (Not sure if it's ArchivesSpace settings or other settings)

### ISSUE THREAD

**Issue by HowtoGravity** [archivesspace/archivesspace#1459]
I'm not sure where else to go but i'm hoping someone here could point me in the right direction. But I just got done setting up ArchivesSpace using a prefix /public & /staff. Doesn't matter which one i use after a while of browsing around I suddenly get a 403 Forbidden You don't have permission to access /staff/.... on this server. The only way i can clear it up is if i clear my cookies. Even after that i would still get 403 Forbidden when browsing around ArchivesSpace. 

Is this something that has to do with an ArchivesSpace setting or other settings on apache?

I'm assuming it's settings in apache that's causing this because all my previous test box worked fine but when i switched over to the production box i get this error. All my test box i managed and had full control but the production box is not within my control and i do not manage it.

Any helpful tip would be appreciated.

**Comment by Blake-** [comment]
Sounds like Apache, are you on httpS or http? What's the config file look like?

**Comment by Blake-** [comment]
The apache config file for that domain. Sounds like something isn't quite right there, and/or, the frontend_proxy_url / public_proxy_url maybe off in your ArchivesSpace config.rb.

**Comment by HowtoGravity** [comment]
In the ArchivesSpace config file there are only a few places where i had made changes, AppConfig[:db_url], AppConfig[:default_admin_password], AppConfig[:frontend_proxy_url], AppConfig[:public_proxy_url], and AppConfig[:pui_hide].

Frontend: AppConfig[:frontend_proxy_url] = 'https://DomainName/staff'
Public: AppConfig[:public_proxy_url] = 'https://DomainName/public'

I don't have permission to view the apache config file for the domain. I've talked with our IT person that help me set it up he suggested I look to make sure it's not something with ArchivesSpace before he goes messing with apache's config file.

**Comment by Blake-** [comment]
That looks around right, just  frontend_proxy_url & public_proxy_url is probably fine. Probably means it's an Apache settings thing.

What does the error look like in the Apache & archivesspace.out logs?

**Comment by HowtoGravity** [comment]
archivesspace.out logs doesn't have anything out of the ordinary, everything looks fine up to and during the error. 

And i don't have permission to view the Apache error logs.

A few questions I have is What determines that someone is logged in? What does ArchivesSpace look for to check to see if someone is currently logged in? and how is a session tracked?
