### ISSUE TITLE
export/import of JSON resources

### ISSUE THREAD

**Issue by jronallo** [archivesspace/archivesspace#146]
I am trying to export JSON resources from an AS repository via the API and then import them into a local repository via the API to use for development. I would like to be able to cherry pick a resource from a remote repository to pull down into my local repository when I am working on an issue or adding a new feature to an external application that uses the AS API.

There are a couple issues that make this more work than it could be. Exporting resources does not resolve all related resources recursively. For instance even when subjects are set to be resolved, they are not resolved within related_accessions. Even when subjects are resolved, import fails because it cannot find a matching subject that already exists in the database. I would expect that resolved subjects would be imported.

Right now in order to get a resource that was exported to import into an empty repository, I need to delete at least the following keys in a resource: related_accessions, subjects, and linked_agents. Subject information is particularly important for my current development.

Maybe there is some other way via the API or otherwise to move resources from one repository to another in separate instances of AS? I could see something like this being useful for aggregators as well.

**Comment by quoideneuf** [comment]
I'm going to go ahead an close this because I don't think the API is intended to support this use case. It would be possible and interesting for someone to create a tool that can copy one instance to another using the API.
