### ISSUE TITLE
Add Unicode support to PDF generator

### ISSUE THREAD

**Issue by avatar382** [archivesspace/archivesspace#1522]
## Expected Behavior
Generating a PDF with unicode characters, like a Chinese symbol, should render that character correctly.

## Current Behavior
Currently, generating a PDF results in unicode characters like Chinese symbols being rendered with the '#' character.

## Possible Solution
Related thread on user's group board: http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2016-May/003598.html

## Steps to Reproduce (for bugs)
Attached sample PDF showing issue/

## Context
This issue was reported to us by Claremont University. 

## Your Environment
ArchivesSpace 2.5.0 running on Ubuntu 16.04.

**Comment by avatar382** [comment]
[document.pdf](https://github.com/archivesspace/archivesspace/files/3052017/document.pdf)

**Comment by lorawoodford** [comment]
#2010 resolves this issue for staff-side PDF generation, but the issue remains on the PUI.  The PUI issue is specifically documented in https://archivesspace.atlassian.net/browse/ANW-1075 so I'm going to close this issue in favor of that JIRA (which will get more visibility than this issue).
