### ISSUE TITLE
Linking a "software" agent to a Resource record breaks both the MARC and EAD export options.  

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#1552]
## Expected Behavior
Successful exports! :)

## Current Behavior
Both export options produce malformed output when a software agent is linked.

## Possible Solution

* For the EAD output, the generic "name" element could be used (see https://www.loc.gov/ead/tglib/elements/name.html)
* I'm not sure what the MARC encoding would need to look like without doing some research, but I wanted to note the issue as it came up in testing.

## Steps to Reproduce (for bugs)

1. Go here: http://test.archivesspace.org/staff/resources/2/  
2. Notice that the software agent for ArchivesSpace is linked as a subject.
3. Export the MARC record (open it up and see that you just get a one line error)
4. Export the EAD record (open it up and see that the exporter chokes on that heading and points you to /app/exporters/serializers/ead.rb:383)

**Comment by lmcglohon** [comment]
@fordmadox I have put in a pull request for this issue. I exported the software agent linked as a subject into a 653 field (https://www.loc.gov/marc/bibliographic/bd653.html).

**Comment by lmcglohon** [comment]
@fordmadox The pull request that fixes this issue, I believe, is now in the master branch. I would appreciate it if you could test it out and let me know if it satisfies the issue.

**Comment by lorawoodford** [comment]
@fordmadox - I believe this issue has been resolved with https://github.com/archivesspace/archivesspace/pull/1743 which was included in v 2.7.1 so I am closing, but reopen if I am mistaken.
