### ISSUE TITLE
Some tests duplicated in `selenium/spec` and `frontend/spec/selenium/spec`

### ISSUE THREAD

**Issue by lorawoodford** [archivesspace/archivesspace#1554]
As frontend tests are added and updated, tests may be duplicated in these locations.  Specifically, search_spec.rb is nearly identical, with the one located in `frontend` including newer updates for the "Found in" context column.  In the future, it is assumed that frontend tests will all be located in `frontend`, but until that time test duplication may exist.  Similarly, existing documentation will need to be updated to point developers to run staff side UI tests with `build/run frontend:selenium` instead of previously used `selenium:staff` or `selenium:test`.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lmcglohon** [comment]
Fixed by https://github.com/archivesspace/archivesspace/pull/1702
