### ISSUE TITLE
Repository creation URL lacks input validation, gives vague error.

### ISSUE THREAD

**Issue by alistairjmcintyre** [archivesspace/archivesspace#1557]
When creating a new Repository, setting the 'Home Page URL' field to a URI that lacks a scheme, it throws a "We're sorry, but something went wrong." error.

## Expected Behavior
If I enter www.google.com, I think it's safe to assume I mean 'https://www.google.com', or alternatively some input validation around this form.

## Current Behavior
No input validation on the form, and this was a fairly difficult bug to decipher. It also does the same thing on edit.

## Possible Solution
I would personally use https:// as a default scheme, but also put some input validation on form submit here. Vague errors are the worst errors.

## Steps to Reproduce (for bugs)
1. Log into the Staff Interface
2. In the top right hand corner to the left of the username, select System > Manage Repositories
3. Here, in the top right corner of the main content portion select "Create Repository"
4. The values of other fields don't seem to matter as much (and I haven't tested extensively), but when setting 'Home Page URL' - Enter a value such as 'google.com' and then click save. It will fail.
5. Press the back button in your browser, put "http://" in front of that url, and try clicking save again - It should work.

## Your Environment
* Version used: ArchivesSpace v2.5.2
* Server Environment: Ubuntu 18.04, running on Java 8 with MariaDB 10.1 for the database and nginx as a front-end reverse proxy.
* Client Environment: Observed on Windows 10 running Chrome and on Ubuntu 18.04 running Firefox.

**Comment by lmcglohon** [comment]
@alistairjmcintyre I believe this is fixed. If you try to input a URL without a scheme you get an error message. It will accept either http or https. 

<img width="500" alt="Screen Shot 2019-12-13 at 1 54 30 PM" src="https://user-images.githubusercontent.com/3585151/70834813-2c208600-1db0-11ea-8e5f-7322b71dae1c.png">
