### ISSUE TITLE
EAD Data Import not working in Firefox in v2.6.0

### ISSUE THREAD

**Issue by Geoffsc** [archivesspace/archivesspace#1614]
I've recently upgraded to v2.6.0 from v2.5.2. For my archive, when I go to Create>Background Job>Import Data, choose EAD in the Import Type dropdown and click "Add file" and add an EAD file and click Start Job I get the error "Files - At least 1 item(s) is required" in Firefox. This is working fine in Chrome. I suspect other import types may not work as well, but I've only tested with EAD files.

**Comment by alexduryee** [comment]
I tested Firefox on macOS (67.0.4) with 2.6.0 and uploading EAD files worked fine.  Which operating system are you running?

I wonder if this is related to #1572 somehow.

**Comment by Geoffsc** [comment]
Myself and my coworker are using FF 67.0.4 on Windows 10. We both experienced the same issue.

**Comment by Geoffsc** [comment]
Just wanted to give an update: myself and my co-worker both re-installed Firefox (clearing extensions on install) and it's working now. So I wonder if a FF extension may have been somehow blocking this functionality but I'm not sure which one it may have been. Either way, it seems this may be a viable workaround.

**Comment by lorawoodford** [comment]
Closing since this appears to have been resolved, but please reopen/refile if I'm incorrect.
