### ISSUE TITLE
Solr configuration of bq for sort only functions with q.op as OR

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#1636]
In [solrconfig.xml](https://github.com/archivesspace/archivesspace/blob/master/solr/solrconfig.xml#L363), bq is set in order to prioritize return values by primary_type.  While this works currently with all configuration default, this is due to the default query operation being *OR*, and applying to bq; if `q.op` is set to *AND* or the `mm` parameter is set, `bq` will be effectively *AND*ed, and thus match nothing, and fail to influence relevance and sort order.
 
## Expected Behavior

What should happen is that changing `q.op` or `mm` should only affect which records are returned, not how they sort.

## Current Behavior

If `q.op` is set to *AND* or `mm` is set to a value that causes multiple terms to be required, this is applied to `bq`, and as the clauses of `bq` are mutually exclusive, it doesn't match, and the records are sorted without relevance boosting.

## Possible Solution

Referring to Solr docs [here](https://lucene.apache.org/solr/guide/7_4/the-dismax-query-parser.html#bq-boost-query-parameter), it looks like the suggested configuration for applying varying boosts to different documents is to provide multiple `bq` params, one per boosted term.  It seems to be the case that explicitly *OR*ing the terms in a single `bq` is logically equivalent; I can't speak to relevant performance.

There are two separate issues at hand: changing the default value in [https://github.com/archivesspace/archivesspace/blob/master/solr/solrconfig.xml], and changing how `AppConfig[:solr_params]` handles `bq` and any other repeatable parameters.

### Config
Unless there's a negative consequence I'm missing, the `bq` term in the `solrconfig.xml` should be decomposed into its separate terms, and each placed in a separate `bq`.

### AppConfig
Add handling to the `AppConfig[:solr_params]` value when read that detects if the value in a parameter is an array, and decomposes it into separate `bq` values when calling Solr.  

## Steps to Reproduce (for bugs)

1. Set `AppConfig[:solr_params] = {"q.op" => "AND"}` 
2. restart ArchivesSpace
3. Search using a query that will bring back both Archival Objects and Resources, where the AOs will be higher relevance sans boost query.

## Your Environment

* Version used: ArchivesSpace v2.5.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Any
* Operating System and version (desktop or mobile): Any

## Notes
Thanks to @marktriggs, who did the lion's share of figuring out what was going on.

**Comment by lmcglohon** [comment]
@pobocks I just merged the separate terms PR. I am wondering if you are planning to put in a PR with the change in the processing of the solr_params configuration to create separate bq's?

**Comment by pobocks** [comment]
So, I'm not unwilling to do the work, but I'm also not sure when I'll be able to get to it, and I think also that I need a better idea of the whole scope of what Solr params _can_ look like before I could do The Right Thing.  Like, is "if an array is a value, make it multiple params?" correct?

**Comment by pobocks** [comment]
And, sadly from the "getting time to work on this" perspective, our local issue is resolved without fixing the broader params issue by the "separate them with OR" workaround, so I'd have to take the off-hours time that I'm HOPING to devote to the docs stuff.

**Comment by lmcglohon** [comment]
@pobocks No worries! Please do not feel obligated to do more on this especially since your local issue has been resolved. Just didn't want to duplicate effort.

**Comment by pobocks** [comment]
So, I had some time on the train, and got the backend part of this I think done to a reasonable standard.

The PUI piece... I think it's substantially more work - the backend already stores and handles the params as an array of arrays, the PUI I think you'd want to think it out a little further and implement some sort of convenience object like a multidict with to_a generating all pairs.

**Comment by pobocks** [comment]
I'm running tests now, I will PR the backend part when they finish running. Basically, it's just "if the parameter is an array, iterate over it and add one per array element"

**Comment by pobocks** [comment]
@lmcglohon poking this bc I don't know if you'd get notified otherwise, not bc urgent

**Comment by lmcglohon** [comment]
Implemented in #1638 So closing this issue
