### ISSUE TITLE
OAI-PMH response for mods does not serialize xmlns:xsi inside the mods record

### ISSUE THREAD

**Issue by markpbaggett** [archivesspace/archivesspace#1687]
Hello, I've been tasked with mapping our ArchivesSpace finding aids to our local discovery system and have come across a tiny bug.  The discovery system splits and serializes the OAI-PMH response from ArchivesSpace into individual records before processing them.  If you do this versus **oai_mods**, the new file isn't valid.  This is because the xmlns:xsi declaration is only applied at the OAI-PMH node, but not to any of the individual records.  Interestingly, this only seems to be a problem with oai_mods and not the other metadata formats.  

## Expected Behavior

I think the MODS output should work exactly as the other metadata formats available with OAI-PMH so that it is possible to split valid XML at a specific element in the OAI-PMH response.

## Current Behavior

You can see this behaviour by just looking at the sample auto-generated responses in the getrecord examples.  MODS has no xsi namespace declaration inside the record node, but the other formats do:

* [MODS has no xsi namespace declaration](https://github.com/archivesspace/archivesspace/blob/ae5c60ca9376d9ee83ad0d561a5bcfbdd2467894/backend/spec/fixtures/oai/responses/getrecord_oai_mods.xml#L12)
* [oai_dc does have an xsi namespace declaration](https://github.com/archivesspace/archivesspace/blob/ae5c60ca9376d9ee83ad0d561a5bcfbdd2467894/backend/spec/fixtures/oai/responses/getrecord_resource_oai_dc.xml#L12)
* [so does oai_dcterms](https://github.com/archivesspace/archivesspace/blob/ae5c60ca9376d9ee83ad0d561a5bcfbdd2467894/backend/spec/fixtures/oai/responses/getrecord_resource_oai_dcterms.xml#L12)
* [so does oai_marc](https://github.com/archivesspace/archivesspace/blob/ae5c60ca9376d9ee83ad0d561a5bcfbdd2467894/backend/spec/fixtures/oai/responses/getrecord_resource_oai_marc.xml#L12)

## Possible Solution

I assume the problem is right here in the [oai_mods.rb mapper](https://github.com/archivesspace/archivesspace/blob/a2bcff22fd5b7f2f345b0e7b3767db1d3550113b/backend/app/lib/oai/mappers/oai_mods.rb#L9).  I'm happy to open a pull request to change this to this:

```ruby
      xml.mods('xmlns' => 'http://www.loc.gov/mods/v3',
               'xmlns:xlink' => 'http://www.w3.org/1999/xlink',
               'xmlns:xsi' => 'http://www.w3.org/2001/XMLSchema-instance',
               'xsi:schemaLocation' => 'http://www.loc.gov/mods/v3 https://www.loc.gov/standards/mods/v3/mods-3-6.xsd') do
```

## Steps to Reproduce (for bugs)
1. Look at the response of our [oai_mods here](http://albatross.lib.utk.edu/oai?verb=ListRecords&set=class&metadataPrefix=oai_mods).  The only xsi declaration is at the top of the response.
2. Compare that with our [oai_dc](http://albatross.lib.utk.edu/oai?verb=ListRecords&set=class&metadataPrefix=oai_dc).  This is exactly what we want.

## Context
We use MODS and I was trying to map our ArchivesSpace to our discovery system in the same way we do our other systems (institutional repository, digital collections).  Honestly, I can live with another metadata format for now if there is a problem with my solution.

## Your Environment
We're still on ArchivesSpace 2.5.0.

**Comment by lmcglohon** [comment]
@markpbaggett Thank you for the solution! I have put in a pull request including it.

**Comment by lmcglohon** [comment]
@markpbaggett this should go out in the next release.
