### ISSUE TITLE
XSS vulnerability in url search

### ISSUE THREAD

**Issue by stevendshelton** [archivesspace/archivesspace#1691]
We received this notice from our campus IT:

XSS Vulnerability

 

The following alert is the product of the Dorkbot service

created by UT Austin:  https://security.utexas.edu/dorkbot

 

Dorkbot serves 1,600+ campuses across 135 countries.

=========================================================

 

The Information Security Office at the University of Texas at Austin

has found the following web page to be vulnerable to a high-risk application attack:

 

GET:  {archivesspace domain}/search?q%5B%5D=%22Appalachian%20Region,%20Southern%22&op%5B%5D=1&field%5B%5D=1&from_year%5B%5D=1&to_year%5B%5D=1%22%3E%3C**script%3Ealert(150)%3C/scrip**t%3E&limit=resource&utf8=%E2%9C%93&commit=Search

 

ATTACK DETAILS:

This page is vulnerable to Cross-site scripting attacks.

 

Cross-site scripting attacks, in general, are an issue because

they are enabling attacks. Specially-crafted malicious URLs can

steal authentication tokens/cookies when a logged-in user visits them,

giving the attacker full access to that user's account in the application.

Reflected XSS attacks, in particular, are a concern as they can be used to

socially engineer a user into clicking on what appears to be a legitimate URL.

 

Verified.

I've checked this on a number of other 2.6 sites and can replicate it so it is not just limited to our installation. I know this could be handled in Nginx, but we are running this server directly on the Jetty server in AS and I'm not sure how to add XSS protection.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lmcglohon** [comment]
@stevendshelton Thank you for submitting this issue. It has been resolved with pull request #1631 and will be coming out soon (probably next week) in the next release v2.7.0.

**Comment by milaje** [comment]
HI there, this still is an issue in 3.4.0.
