### ISSUE TITLE
Wrong logging level in indexer?

### ISSUE THREAD

**Issue by andrew-morrison** [archivesspace/archivesspace#1692]
## Expected Behavior
The level of logging by the indexer should be determined by the value of `AppConfig[:indexer_log_level]` in the config/config.rb file of a built production ArchivesSpace system.

## Current Behavior
The level of logging by the indexer is controlled by `AppConfig[:backend_log_level]` instead.

## Possible Solution
Change this line:
https://github.com/archivesspace/archivesspace/blob/076d2db72c7ff90cd1c0a1d12d8a2554bc8459af/indexer/app/main.rb#L109

## Steps to Reproduce
1. Set `AppConfig[:backend_log_level]` to "warn" and `AppConfig[:indexer_log_level]` to "info".
2. Restart ArchivesSpace.
3. Check application log file: nothing is written to it about the indexer, even if you [force a re-index](https://archivesspace.github.io/archivesspace/user/re-creating-indexes/).
4. Set `AppConfig[:backend_log_level]` to "info".
5. Restart ArchivesSpace.
6. Check application log file: now messages about the periodic indexer are written to it.

## Context
We would like to know when the indexer is running (normally) but only when problems occur in the backend. But, as the default value is "debug", changing this might cause others to see a big increase in logging.

## Your Environment
This appears to have been the behvaiour in all releases since at least 2017-12-11.

**Comment by lmcglohon** [comment]
Related to #1258
