### ISSUE TITLE
Startup failure on fresh instance due to non-UTF-8 table

### ISSUE THREAD

**Issue by ph448** [archivesspace/archivesspace#1697]
## Expected Behavior
ArchivesSpace initialises and starts operating.

## Current Behavior
After DB migrations are done the logs show a warning saying that the table `rights_statement_pre_088` is not UTF-8. From then on, database connections fail and ArchivesSpace is no longer operational:
```
as_1     | E, [2019-10-11T14:03:38.394096 #83] ERROR -- : Thread-2000: DB connection failed:                                                                                                   
as_1     | The following MySQL database tables are not set to use UTF-8 for their character                                                                                                    
as_1     | encoding:                                                                                                                                                                           
as_1     |                                                                                                                                                                                     
as_1     |   * rights_statement_pre_088                                                                                                                                                        
as_1     |                                                                                                                                                                                     
as_1     | Please refer to README.md for instructions on configuring your database to use                                                                                                      
as_1     | UTF-8.                                                                                                                                                                              
as_1     |                                                                                                                                                                                     
as_1     | If you want to override this restriction (not recommended!) you can set the                                                                                                         
as_1     | following option in your config.rb file:                                                                                                                                            
as_1     |                                                                                                                                                                                     
as_1     |   AppConfig[:allow_non_utf8_mysql_database] = "true"                                                                                                                                
as_1     |                                                                                                                                                                                     
as_1     | But note that ArchivesSpace largely assumes that your data will be UTF-8                                                                                                            
as_1     | encoded.  Running in a non-UTF-8 configuration is not supported.                                                                                                                    
as_1     |                                                                                                                                                                                     
as_1     |                                                                                                                                                                                     
as_1     | E, [2019-10-11T14:03:39.676956 #83] ERROR -- : Thread-2000: ***** DATABASE CONNECTION FAILED *****                                                                                  
as_1     |                                                                                                                                                                                     
as_1     | ArchivesSpace could not connect to your specified database URL (jdbc:mysql://as-db:3306/archivesspace?user=[REDACTED]&password=[REDACTED]&useUnicode=true&characterEncoding=UTF-8). 
```
## Possible Solution
Dropping the table or converting it to UTF-8 both solve the issue. I don't have instances that have pre-088 rights statements, so I don't know which of these is feasible for those installations, but for the case where the resulting table is empty (like a fresh install as of today), it should be safe for the migration to delete it.

## Steps to Reproduce (for bugs)
1. Configure ArchivesSpace with a database connection to an empty database
2. Start ArchivesSpace

## Context
I am using ArchivesSpace in Docker to test-drive migrations of hundreds of thousands of records and need to spin up new instances in my testing without user interaction, which is not currently possible.

## Your Environment
* Versions used: 2.5.2, 2.6.0, 2.7.0-RC1
* Database: MariaDB 10.3.15, MySQL 5.7.27

**Comment by lmcglohon** [comment]
@ph448 I was able to replicate what you are getting by not specifying default character set utf8 when I created my database.  Did you include 'default character set utf8' when the database was created? For example, create database archivesspace default character set utf8;

**Comment by ph448** [comment]
@lmcglohon thanks for the swift response. I did not create the database but set environment variables for the mariadb container to create it. My database settings were:
<pre>
MariaDB [archivesspace]> show create database archivesspace\G
*************************** 1. row ***************************
       Database: archivesspace
Create Database: CREATE DATABASE `archivesspace` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */
1 row in set (0.000 sec)

MariaDB [archivesspace]> show create table rights_statement_pre_088\G
*************************** 1. row ***************************
       Table: rights_statement_pre_088
Create Table: CREATE TABLE `rights_statement_pre_088` (
  ...
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
1 row in set (0.000 sec)

MariaDB [archivesspace]> show variables like '%character%'; 
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
</pre>

I have set the encoding to 'utf8' instead of 'utf8mb4' and now the database passes the check. Is there any other technical reason for 'utf8mb4' not to pass besides the two strings not comparing equal?

**Comment by lmcglohon** [comment]
@ph448 I think you have discovered the issue and I don't know of any other technical reason for the failure.

**Comment by lmcglohon** [comment]
@ph448 Since I believe this is resolved, I am going to close this issue. Please feel free to re-open it if you think it isn't resolved.

**Comment by ph448** [comment]
@lmcglohon I don't think this is resolved as ArchivesSpace chokes on a valid UTF-8 character encoding setting. MySQL 8.0 [recommends setting 'utf8mb4' explicitly](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html) and MariaDB has an [open issue for changing utf8 to mean utf8mb4](https://jira.mariadb.org/browse/MDEV-8334), with an interim step of renaming current utf8 to utf8mb3, slated for the next release, 10.5.

**Comment by ph448** [comment]
@lmcglohon I am new to JRuby/Rails and am currently finding my way around the build/test system, in particular I cannot test my changes because I am not yet able to configure a MySQL database connection for the development server. I should figure it out soon and be able to submit a PR, but feel free to move this forward if you want to.

**Comment by sdm7g** [comment]
Note also: 

[common/db/db_migratior:  Sequel::MySQL.default_charset = 'utf8'](https://github.com/archivesspace/archivesspace/blob/master/common/db/db_migrator.rb#L7)

and perhaps this collation needs to be changed as well
[common/db/migrations/001_create_base_schema.rb: create_table(:enumeration_value, :collate => :utf8_bin) do](https://github.com/archivesspace/archivesspace/blob/master/common/db/migrations/001_create_base_schema.rb#L33)

**Comment by ph448** [comment]
@sdm7g I would be happy to work on those in a separate PR to make ArchivesSpace use 'utf8mb4' by default.

@lmcglohon I have been able to test the changes and they seem to work. I have in the process muddled up my fork of the repository, so I'll do another fork and create the PR from there to keep this project's history clean.
