### ISSUE TITLE
Need to continue to add fonts for PDFs

### ISSUE THREAD

**Issue by lmcglohon** [archivesspace/archivesspace#1701]
## Current Behavior

#1642 was a good start for adding fonts but it does not cover all fonts.

## Possible Solution

Documentation/instruction on how to add more fonts and the addition of more fonts

**Comment by seth-shaw-unlv** [comment]
Perhaps [Mātṛkā](https://lapislazulitexts.com/articles/matrka-serif) or [Gentium](https://software.sil.org/gentium)?
