### ISSUE TITLE
Indexing changes for fullrecord?

### ISSUE THREAD

**Issue by marktriggs** [archivesspace/archivesspace#172]
Hi ArchivesSpacers,

While working with Yale we've had a few cases where searches match documents that were surprising to users.

This comes about because keyword (and typeahead) searches generally target the `fullrecord` Solr field, and this is populated with the raw JSON representation of each record by this copyField definition:

     <copyField source="json" dest="fullrecord"/>

For example, if you search for "lock" you'll probably get a match on the `lock_version` JSON property, which you won't see in the user interface but is hiding there behind the scenes.

I'm wondering whether we could change this as follows:

  * Remove the copyField definition from schema.xml and change the indexer to generate values for this field itself.

  * Change the default `fullrecord` generator to index the (string?) values from JSON documents instead of the entire document.

The first change would allow for more fine-grained control over which fields get indexed for keyword searching, while the second would hopefully give a less surprising default.  What do you think?

Thanks!

Mark

**Comment by bdwestbrook** [comment]
This sounds like a good improvement to me, Mark.  But it would be good to hear from others.

Brad
