### ISSUE TITLE
Failed to clean XML: The entity "nbsp" was referenced, but not declared (When Printing)

### ISSUE THREAD

**Issue by tpegues2** [archivesspace/archivesspace#1720]
We are unable to print some items in Archivesspace.  Some of them work while others of them do not.  
## Expected Behavior

The pdf should appear and I should be able to print it with no issue.  
## Current Behavior

The pdf doesn't not appear but instead I get the following message:
We're Sorry Something Went Wrong. If you are the application owner please check your logs.

I, [2019-11-21T12:14:16.243890 #13568]  INFO -- : [3612a513-1a17-470b-a90b-a095cfec7962]   Rendered pdf/_footer.html.erb (0.0ms)
I, [2019-11-21T12:14:16.256609 #13568]  INFO -- : [3612a513-1a17-470b-a90b-a095cfec7962] Completed 500 Internal Server Error in 1473ms
F, [2019-11-21T12:14:16.257652 #13568] FATAL -- : [3612a513-1a17-470b-a90b-a095cfec7962]
F, [2019-11-21T12:14:16.257738 #13568] FATAL -- : [3612a513-1a17-470b-a90b-a095cfec7962] RuntimeError (Failed to clean XML: The entity "nbsp" was referenced, but not declared.):
F, [2019-11-21T12:14:16.257772 #13568] FATAL -- : [3612a513-1a17-470b-a90b-a095cfec7962]
F, [2019-11-21T12:14:16.257818 #13568] FATAL -- : [3612a513-1a17-470b-a90b-a095cfec7962] app/lib/xml_cleaner.rb:31:in `clean'
[3612a513-1a17-470b-a90b-a095cfec7962] app/models/finding_aid_pdf.rb:94:in `generate'
[3612a513-1a17-470b-a90b-a095cfec7962] app/controllers/pdf_controller.rb:17:in `resource'
I, [2019-11-21T12:14:19.155176 #13568]  INFO -- : Thread-2016: Staff Indexer [2019-11-21 12:14:19 -0500] Running index round
I, [2019-11-21T12:14:19.488602 #13568]  INFO -- : Thread-2016: Staff Indexer [2019-11-21 12:14:19 -0500] Index round complete
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by suhailrepo** [comment]
Hello,

We are in University of Auckland, recently upgraded to v2.7.1 of archivesspace. On generating we are expereincing the same issue.

 FATAL -- : [b3a9ef93-0190-4496-b407-4974b0c3659d] RuntimeError (Failed to clean XML: The entity name must immediately follow the '&' in the entity reference.):

FATAL -- : [b3a9ef93-0190-4496-b407-4974b0c3659d] app/lib/xml_cleaner.rb:32:in `clean'
[b3a9ef93-0190-4496-b407-4974b0c3659d] app/models/finding_aid_pdf.rb:94:in `generate'
[b3a9ef93-0190-4496-b407-4974b0c3659d] app/controllers/pdf_controller.rb:15:in `resource

**Comment by lorawoodford** [comment]
I believe this issue has been resolved by #1573 (included in v2.8.0).  If this issue persists please open a new issue.
