### ISSUE TITLE
Some language notes exported as CDATA

### ISSUE THREAD

**Issue by andrew-morrison** [archivesspace/archivesspace#1721]
Language notes containing XML elements are output as CDATA inside `langmaterial` when exporting to EAD 2002, since the 2.7.0 release. The EAD3 export is not affected.

## Expected Behavior
Here is an example of correct output:
```xml
<langmaterial id="aspace_b2699c5be6501ba38829701baf1bd87f">
   This is an example of something more than just text 
   <language langcode="eng">English</language> and 
   <language>Something without codes</language>
</langmaterial>
```

## Current Behavior
Here is an example of the current, incorrect output:
```xml
<langmaterial id="aspace_b2699c5be6501ba38829701baf1bd87f">
<![CDATA[This is an example of something more than just text <language langcode="eng">English</language> and <language>Something without codes</language>]]>
</langmaterial>
```

## Possible Solution
In backend/app/exporters/serializers/ead.rb, the new `serialize_languages` method of the _EADSerializer_ class created for multiple languages in 2.7.0 does not, like all the other `serialize_*` methods, take a third argument for a variable called `fragments`. That means it cannot pass that on when it calls the `sanitize_mixed_content` method of the same class. It sends a boolean instead, which should be the (optional) fourth argument. For a language note containing just text, that isn't a problem, but if it contains any XML, `ASpaceExport::Utils.has_html?(content)` is true, but it cannot do `context.text (fragments << content )`, because content cannot be appended to a boolean. So it falls back to doing this: `context.cdata content`. Hence the CDATA output.

Modifying the `serialize_languages` method, and the two calls to it, fixes the bug.

## Steps to Reproduce (for bugs)
1. Create a language note in a resource or archival object.
2. Include some `language` tags or other XML.
3. Export as EAD (do not select EAD3 schema).

## Context
While the exported EAD is valid, what should be child elements of `langmaterial`, such as `language`, are character data, so cannot be accessed as nodes by an XML parser. For example, if using OAI-PMH to feed in to another system.

## Your Environment
* Version used: 2.7.0

**Comment by lorawoodford** [comment]
Resolved by #1722
