### ISSUE TITLE
Non-ASCII characters in slugs cause public user interface error

### ISSUE THREAD

**Issue by andrew-morrison** [archivesspace/archivesspace#1725]
If you include a character that is outside the ASCII range in a record title, which is then automatically added to the slug field for that record, the public user interface page for that record will not be displayed if accessed via its slug-based URL. An example of such a character is an en-dash, which is commonly used in date ranges.

## Expected Behavior
The page should display.

## Current Behavior
On a production system, you get a "We're sorry, but something went wrong" message. On a development system, a the error message is:
```
URI::InvalidURIError in ObjectsController#show
URI must be ascii only
```
The problem is narrowed to this line:

https://github.com/archivesspace/archivesspace/blob/c29a86fb1b16b55ef77a3910a10464582c44821f/public/app/controllers/application_controller.rb#L92

## Possible Solution
Even if the web browser has percent-encoded the non-ASCII character, Rails unencodes it. But the Ruby URI module only accepts ASCII characters when it creates an URI object. This is done to send a query containing the slug to the backend in order to find the matching record. Possible fixes include:

 * Make the slug-generating code as strict as the URI module (but that could be an internationalization issue, and won't fix existing slugs.)
 * Replace the URI module with something that supports non-ASCII characters (the Addressable gem?)
 * Re-encode before passing to the URI module. A quick (but not extensively tested) fix is to change line 92 to this:
```ruby
url = URI("#{JSONModel::HTTP.backend_url}#{URI.escape(uri)}")
```

## Steps to Reproduce (for bugs)
1. Set `AppConfig[:use_human_readable_urls]` to true.
2. Use the staff interface to create a new resource record. 
3. Give it a title including the `–` character.
4. Let it automatically generate the slug.
5. Ensure it is set to be published.
6. Save, give it time to index the new record, then click View Published

Here is one I made earlier: 

 * http://test.archivesspace.org/resources/testing_date_ranges_in_titles_1879%E2%80%931959_and_their is broken.
 * http://test.archivesspace.org/repositories/2/resources/85 displays without issues.

## Context
Cannot upgrade to 2.7.0 (or 2.6.x, presumably) without fixing this.

## Your Environment
* Version used: 2.7.0

**Comment by lmcglohon** [comment]
@andrew-morrison I have put in a pull request that I believe will fix this issue. Once in the core code base, all installations that have already generated slugs using automatic generation can run the Generate slugs in bulk background job which will clean up all existing, auto-generated slugs.
