### ISSUE TITLE
Tricky dependencies in build.xml 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#1765]
There are some tricky dependencies in build.xml that cause issues if the *:deserver targets are not run in a particular order.  

## Current Behavior

 If you run public:devserver target before you run frontend:devserver, dependencies on that target ( frontend:devserver => frontend:clean => solr:nuke ) will attempt to delete indexer_pui_state directory. If that directory is already open, it may instead merely unlink the directory, and another one with the same name may be created later. 

Other PUI functions may fail. What exactly fails or how may be timing dependent. 

## Possible Solution
If possible, dependencies should be reordered and fixed. 
If not, this behavior should be documented, as the behavior is somewhat puzzling. 

A more complete review of dependencies is required to determine how of if they can be easily reordered. 

## Steps to Reproduce (for bugs)

1.  ./build/run backend:devserver 
2.  ./build/run indexer
3.  ./build/run public:devserver
4.  ./build/run frontend:devserver 
It's possible these actions are timing dependent. 
However, what I observed was that the build/indexer_pui_state disappeared and reappeared missing previously existing content. Sometimes other PUI functions failed. 

## Context

 Mysterious failures when testing and review PUI pull requests. 

## Your Environment

* Version used:  current master branch

**Comment by pobocks** [comment]
I think this is the same as the issue I reported in the ASpace JIRA - if so, there's a PR for it:

https://github.com/archivesspace/archivesspace/pull/1758

**Comment by lmcglohon** [comment]
@sdm7g I believe this issue has been resolved with #1758 so am closing this issue.
