### ISSUE TITLE
'parameterize' call in migration fails because parameterize isn't available on String

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#1784]
In [migration 120](https://github.com/archivesspace/archivesspace/blob/master/common/db/migrations/120_clean_slugs_for_repositories.rb#L23), if unwanted characters are found in the slug, a string method called `parameterize` is called.  This appears to be a method in ActiveSupport::Inflector, but the migration code is not run in a context where ActiveSupport inflectors are mixed into String.

## Expected Behavior
Migration should clean up slugs as per parameterize.

## Current Behavior
If a slug needs cleaning, the migration will fail with a "NoMethodError"

## Possible Solution
Adding:

```ruby
require 'active_support/inflector'
```

somewhere in the migration process.  It would work in the specific migration, but it might be better to include it somewhere that would affect all migrations, naive guess: [build/scripts/migrate_db.rb](https://github.com/archivesspace/archivesspace/blob/master/build/scripts/migrate_db.rb#L8)

Doug Simon found this issue, and is testing if adding ActiveSupport in the migrate_db script works now, will update in comment.

## Steps to Reproduce (for bugs)
Run the migration with a slug value that is anything except just digits; in all other cases, parameterize gets run. 

## Context
Dev environments where we've tried to migrate from existing 2.5.x codebases have failed to display resources due to migration failure.

## Your Environment
Running on master, having migrated the DB from a 2.5.1 db with slugs present in it.

**Comment by lmcglohon** [comment]
@pobocks trying to replicate this. Slugs didn't go in until 2.6.0, so I am confused about a 2.5.1 DB having slugs present. Can you provide more information?

**Comment by pobocks** [comment]
My guess is that it's actually a migration from somewhere north of 2.5.1, it's on a dev machine so it could be most points inbetween.  But I think the issue is definitely real - I'd say to replicate, wind back to commit immediately before the migration was introduced, add a slug with chars other than digits, and then bump and migrate.

**Comment by pobocks** [comment]
First commit migration shows up in is: eb814ec7d187491c6ac7c09ddb011c62b44d0e17

**Comment by lmcglohon** [comment]
@pobocks it sounds to me that the db you are using for development is in a place in between releases.  Development DBs between releases should be considered throw aways because, in between releases, the master branch in the ArchivesSpace repository is a continuously moving target. Unless the migration fails going from one release to another, there is no issue to handle here. As far as I know performing a migration up to 2.6.0 or higher is working fine so I am going to close this issue and reject the PR.

**Comment by pobocks** [comment]
@lmcglohon - Would respectfully like to ask you to reconsider/re-open.

The situation that caused us to find it is weird, granted - but I think _something_ ought to be done, because this migration will cause a NoMethodError _in almost any situation it's not a no-op_.  Even if that only hits developers, having a trap for careless developers that provides no other benefit seems like a bad idea. If it can only run pre 2.6.0 and there can't be slugs pre 2.6.0, it should just be removed maybe?  And if it can be run post 2.6.0, then it's a real problem for anyone, and should be fixed.

**Comment by lmcglohon** [comment]
@pobocks this migration should be run only when upgrading from 2.5.x or earlier to 2.6.0 or later versions. Slugs were introduced in 2.6.0 and that included automatically generating slugs for all repository records. This migration deals with the cleaning up those repository slugs. I don't understand why you think it would be run post 2.6.0.

**Comment by pobocks** [comment]
I think maybe we've gotten confused by each other here, so I'm going to outline where I think this will occur (and where it did occur with Doug's instance).

1. START with 2.5.x release that has repo_codes with non-numeric characters in them
2. run 118_create_slugs_for_repositories.rb - those repos all have slugs now
3. run 120_clean_slugs_for_repositories.rb - NoMethodError because of non-numeric slugs

I'm not sure _why_ y'all haven't hit it - do you have repo_codes defined? Do most places and test data have numeric repo_codes?

And I guess also, like... even if the case is unreachable, it contains code that will error out invariably if hit, which will be looked at and maybe emulated next time someone does a "clean X field," etc?  Does that make sense?

**Comment by lmcglohon** [comment]
@pobocks That helps clarify what you are talking about. Would it be ok if I think about it over the weekend and get back to you on Monday? I need to finish something up today and want to reexamine what you have said here with a fresh perspective.

**Comment by pobocks** [comment]
Sure thing - we've got a workaround, after all, so it's not a rush job by any means!

Also, unrelated note: I'm gonna be round your way next week (conf at Stanford), so let me know if you're up to meet up and maybe get a food at some point!

**Comment by lmcglohon** [comment]
@pobocks cool! I may be able to drive up for dinner one night - it is a 2-3 hour drive each way. Let me know when you are available!

**Comment by lmcglohon** [comment]
@pobocks PR #1786 merged into master. Thanks for finding this!

**Comment by pobocks** [comment]
Thanks!  @Hurlyburly2 did most of the work, I'm just the messenger on this one :-)
