### ISSUE TITLE
Collection Organization Window Not Appearing 

### ISSUE THREAD

**Issue by tpegues2** [archivesspace/archivesspace#1815]
## Current Behavior
We recently upgraded from 2.5 to 2.6. Container edits to existing collections and new collections are not reflected in the Collection organization window. General information made to the resources are reflected just fine and work properly. The collection organization area shows no data and the tab to get to it is locked.  

## Steps to Reproduce (for bugs)

1. Here is how it looks today.
    http://archivesspace.kennesaw.edu/repositories/4/resources/96 
2. Here is an old example from 2019 that looks like it's supposed to:
    http://archivesspace.kennesaw.edu/repositories/4/resources/332
## Your Environment

* Version used: 2.6.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Archivesspace
* Operating System and version (desktop or mobile): RHEL7.7
* Link to your project:

**Comment by lorawoodford** [comment]
@tpegues2  - In looking at your examples today, I see active Collection Organization sidebars and tabs/pills, suggesting that this issue has been resolved.  Usually when a missing/empty Collection Organization panel is reported it is the result of an incomplete/still running indexing process.  The PUI indexer runs quite a bit slower than the staff side indexer, so a lag in indexing may be encountered (especially when a complete/fresh reindex is initiated).  

I'm going to close this issue for now, but please reopen if I've missed something.
