### ISSUE TITLE
Docker Failing on Maven MYSQL Connector

### ISSUE THREAD

**Issue by brimwats** [archivesspace/archivesspace#1819]
Docker-Compose Up Fails

## Expected Behavior
Docker-Compose should build archivesspace correctlly. 

## Current Behavior
It does not.

## Steps to Reproduce (for bugs)

Run docker-compose up
Have it fail on step 4/15

## Context

```
Step 4/15 : RUN cd /source &&     ARCHIVESSPACE_VERSION=${SOURCE_BRANCH:-`git symbolic-ref -q --short HEAD || git describe --tags --match v*`} &&     ARCHIVESSPACE_VERSION=${ARCHIVESSPACE_VERSION#"heads/"} &&     echo "Using version: $ARCHIVESSPACE_VERSION" &&     ./scripts/build_release $ARCHIVESSPACE_VERSION &&     mv ./*.zip / &&     cd / &&     unzip /*.zip -d / &&     wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar &&     cp /mysql-connector-java-5.1.39.jar /archivesspace/lib/
 ---> Running in a8735c85af23
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
ERROR: Service 'archives' failed to build: The command '/bin/sh -c cd /source &&     ARCHIVESSPACE_VERSION=${SOURCE_BRANCH:-`git symbolic-ref -q --short HEAD || git describe --tags --match v*`} &&     ARCHIVESSPACE_VERSION=${ARCHIVESSPACE_VERSION#"heads/"} &&     echo "Using version: $ARCHIVESSPACE_VERSION" &&     ./scripts/build_release $ARCHIVESSPACE_VERSION &&     mv ./*.zip / &&     cd / &&     unzip /*.zip -d / &&     wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar &&     cp /mysql-connector-java-5.1.39.jar /archivesspace/lib/' returned a non-zero code: 128
```

## Your Environment

* Version used: The most recent. 
* Environment name and version (e.g. Chrome 39, node.js 5.4): Docker.
* Operating System and version (desktop or mobile): Ubuntu 18

**Comment by brimwats** [comment]
I have tried

1) sudo curl -L -o /mysql-connector-java-5.1.39.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar

then exporting it to classpath. it did not work (or I did it wrong?)

2) pip install mysql-connector-python
it did not work

**Comment by mark-cooper** [comment]
Hi @brimwats

The docker compose file is provided for developers to test branches with a more complete, prod-like ArchivesSpace environment, so you need to be working with the source repository (which it appears you are not: "not a git repository"). There's more info here: https://archivesspace.github.io/archivesspace/user/docker/

**Comment by brimwats** [comment]
well, that's embarrassing! 🤦🏻‍♀️🤦🏻‍♂️

Thanks for that @mark-cooper ! Do you know of a good Docker-compose that I can work into my own compose file? I'm mostly teaching myself various platforms and I've managed to get AtoM, Omeka and a couple others running well and reverse proxied.

**Comment by mark-cooper** [comment]
Sure, I think a reasonable starting point for trying things out would be to use the existing compose file but replace the `build: .` instruction with `image: archivesspace/archivesspace:2.7.1`. That will run aspace with the image from Docker Hub. If you want to build your own image you could create your own Dockerfile and pack whatever you want into it =)

But please do note the disclaimer at: https://archivesspace.github.io/archivesspace/user/docker/

There's no official support for Docker as a deployment option, you're essentially on your own aside from what community help (such as this) you can get.

**Comment by brimwats** [comment]
Yes! That's exactly what I'm looking for! thanks so much for the pointer @mark-cooper 😁
