### ISSUE TITLE
SMTP Not working when trying to send request

### ISSUE THREAD

**Issue by HowtoGravity** [archivesspace/archivesspace#1826]
Trying to set up the "Request" button with SMTP but it's not working. The application is pretty bare bones only slight aesthetic changes here and there, no plugins of any kind installed. Please let me know if any more information is needed. 

OS: Debian 9
ArchivesSpace 2.7.0

Here are my settings
`AppConfig[:pui_page_actions_request] = true`
`AppConfig[:pui_email_override] = 'sometestemail@gmail.com'`
`AppConfig[:pui_request_email_fallback_to_address] = 'sometestemail@gmail.com'`
`AppConfig[:pui_request_email_fallback_from_address] = 'sometestemail@gmail.com'`
`AppConfig[:pui_email_delivery_method] = :smtp`
`AppConfig[:pui_email_smtp_settings] = {`
`    address:              "smtp.gmail.com",`
`      port:                 587,`
`      domain:               'gmail.com',`
`      user_name:            'sometestemail@gmail.com',`
`      password:             'password_for_test_email',`
`      authentication:       'plain',`
`      enable_starttls_auto:  true`
`}`
`AppConfig[:pui_email_perform_deliveries] = true`
`AppConfig[:pui_email_raise_delivery_errors] = true`

**Comment by mark-cooper** [comment]
@HowtoGravity when you say it's not working what actually happens? I assume you're attempting to use the request form in the public interface - are you getting an error message? Is there anything relevant you can see in the aspace log?

**Comment by HowtoGravity** [comment]
@mark-cooper Sorry about delayed reply everything was put on hold due to the pandemic. 

But on the webpage everything seems to go thought perfectly, no error of any kind. After filling out the information on the request window and clicking on "Request" button it closes the window as if the request went though.

In the log files I can see it creating the email and populating it with the correct information. Everything looks to be working up to this point.

The issue is that I am not actually receiving any email in the requestor's inbox and i don't see any sent email in the sender's sent box. The email credentials are correct.

Is there another linux application or archivesSpace plugin I need to setup locally to actually do the email sending?
