### ISSUE TITLE
Archivesspace Won't Start After Installation (An Exception Happened During JRuby-Rack)

### ISSUE THREAD

**Issue by tpegues2** [archivesspace/archivesspace#1840]
Getting these messages when attempting to start archivesspace.  It runs for a minute and then quickly stops.  

## Current Behavior

Mar 18, 2020 8:58:06 PM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFO: An exception happened during JRuby-Rack startup
mismatched number of keys: [:event_id] vs [:db, :name]
--- System
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]
Time: 2020-03-18 20:58:06 -0400
Server: jetty/8.1.5.v20120716
jruby.home: uri:classloader://META-INF/jruby.home

"backtrace": [
      "/srv/archivesspace/gems/gems/sequel-4.20.0/lib/sequel/model/associations.rb:1945:in `def_one_to_many'",
      "/srv/archivesspace/gems/gems/sequel-4.20.0/lib/sequel/model/associations.rb:1691:in `associate'",
      "/srv/archivesspace/gems/gems/sequel-4.20.0/lib/sequel/model/associations.rb:1733:in `one_to_many'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/mixins/external_documents.rb:4:in `included'",
      "org/jruby/RubyModule.java:2638:in `include'",
      "/srv/archivesspace/gems/gems/sequel-4.20.0/lib/sequel/model/base.rb:478:in `include'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/event.rb:9:in `<class:Event>'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/model/event.rb:3:in `<main>'",
      "org/jruby/RubyKernel.java:956:in `require'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:133:in `block in ArchivesSpaceService'",
      "org/jruby/RubyArray.java:1735:in `each'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:1:in `block in (root)'",
      "org/jruby/RubyArray.java:1735:in `each'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:132:in `block in ArchivesSpaceService'",
      "org/jruby/RubyArray.java:1735:in `each'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:131:in `block in ArchivesSpaceService'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:130:in `ArchivesSpaceService'",
      "/srv/archivesspace/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1411:in `<class:configure>'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:78:in `<main>'",
      "org/jruby/RubyKernel.java:956:in `require'",
      "/srv/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:38:in `(root)'",
      "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `block in (root)'",
      "org/jruby/RubyBasicObject.java:1691:in `instance_eval'",

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Archivesspace 2.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): RHEL 7.7
* Link to your project:

**Comment by cdibella** [comment]
This is a support issue rather than an ArchivesSpace code issue. If you still need help, please email us at ArchivesSpaceHome@lyrasis.org.
