### ISSUE TITLE
Title sort in Location and other Tables are not numeric-sensitive

### ISSUE THREAD

**Issue by michael-lts** [archivesspace/archivesspace#1853]
In the staff interface, when sorting by title in location, resources and other tables, numbers within alphanumeric titles are not sorting numerically

## Expected Behavior
Title ABC10 should sort after ABC9, not ABC1. That is the titles should sort ABC1, ABC2 ... ABC9, ABC10 ...

## Current Behavior
Currently those titles sort ABC1, ABC10, ABC2 ...

## Possible Solution
for the sort_title field in solr use different analyzer that handles numerical sort

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lorawoodford** [comment]
Closed/resolved by #1854
