### ISSUE TITLE
Grandchild indicator indexer field appears to be incorrect

### ISSUE THREAD

**Issue by ktamaral** [archivesspace/archivesspace#1858]
There appears to be a type-o with the grandchild indicator in the indexer. The grandchild indicator is supposed to be "indicator_3" however it is being appended to the "grand_child_container_u_sstr" field as "indicator_2".

## Expected Behavior

We haven't experienced any use-case issues since we typically don't use grandchild indicator, I just happened to notice this type-o when working on another feature.

## Possible Solution

indexer/app/lib/indexer_common.rb

Current:
doc['grand_child_container_u_sstr'] << "#{instance['sub_container']['type_3']} #{instance['sub_container']['indicator_2']}"

Suggested update:
doc['grand_child_container_u_sstr'] << "#{instance['sub_container']['type_3']} #{instance['sub_container']['indicator_3']}"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mark-cooper** [comment]
@ktamaral thx for pointing this out. Your proposed solution looks correct to me. Can you make a pull request with the update?

**Comment by ktamaral** [comment]
Apologies for the delay in response (I need to fix my notification settings). This issue can be closed since it appears to have already been fixed in master e.g. https://github.com/archivesspace/archivesspace/blob/master/indexer/app/lib/indexer_common.rb#L663
