### ISSUE TITLE
After Upgrade from ArchivesSpace 2.6.0 to  2.7.1 (Search Results Order Changed)

### ISSUE THREAD

**Issue by tpegues2** [archivesspace/archivesspace#1909]
## Expected Behavior
I upgraded from Archivesspace 2.6.0 to 2.7.1 and expected the same search results or close.

## Current Behavior
 When I do a search on the public interface, nothing comes up the way it's supposed to.
Just for example,  "Bowling Yates" typed in the main search bar brings up: http://archivesspace.kennesaw.edu/search?utf8=%E2%9C%93&op%5B%5D=&q%5B%5D=bowling+yates&limit=&field%5B%5D=&from_year%5B%5D=&to_year%5B%5D=&commit=Search as the first entry but literally nothing else I've tried finds the right things without tweaking it and it didn't used to be that way.
(When I put in "Blair Family" this comes up: http://archivesspace.kennesaw.edu/search?utf8=%E2%9C%93&op%5B%5D=&q%5B%5D=blair+family&limit=&field%5B%5D=&from_year%5B%5D=&to_year%5B%5D=&commit=Search)
 
Has some sort of filter been put on it that wasn't there before? Or maybe a filter used to be there and it disappeared...
It used to pull up what you were looking for within the first few entries but now it doesn't. I tried "Michael Coles," "Betty Siegel," and "Georgia Writers Association."

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
Archivesspace 2.7.1
RHEL 6

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by cdibella** [comment]
This is a support issue rather than an ArchivesSpace code issue. If you still need help, please email us at ArchivesSpaceHome@lyrasis.org.
