### ISSUE TITLE
ANW-1086 Browser warning on sameSite cookies

### ISSUE THREAD

**Issue by Blake-** [archivesspace/archivesspace#1945]
Currently FireFox warns:

`Cookie “_archivesspace-public_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies`

## Expected Behavior

No warning

## Current Behavior

warning

## Possible Solution

add
`response.headers['Set-Cookie'] = 'Secure;SameSite=None'.`
to a controller someplace, can't find which one

https://archivesspace.atlassian.net/projects/ANW/issues/ANW-1086

**Comment by quoideneuf** [comment]
This was resolved by improving the documentation for deployment here:
https://github.com/archivesspace/tech-docs/pull/146
