### ISSUE TITLE
Using external Solr 6.6.6 with ArchivesSpace 2.8.0

### ISSUE THREAD

**Issue by kloor** [archivesspace/archivesspace#1961]
With the upgrade to ArchivesSpace 2.8.0, reloading the core for our external Solr 6.6.6 installation failed. After some trial and error, I found the [Docker file](https://github.com/archivesspace/archivesspace/blob/master/solr/Dockerfile) that appears to set up the internal Solr with a 6.6 version, and made the same changes to my external solr: Using solrconfig-6.6.xml and schemal-6.6xml and installing the icu4j-65_1.jar file. Once I did this, the core loaded successfully, but Solr produced errors such as the following while reindexing most items:
```
E, [2020-08-07T09:04:41.008119 #104959] ERROR -- : Thread-2026: SolrIndexerError when indexing records: {"responseHeader":{"status":400,"QTime":2},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],"msg":"ERROR: [doc=/repositories/2/resources/488] unknown field 'dates'","code":400}}
```

I did find issue #734 which was about supporting Solr 6.6, but it was closed with a comment that maintenance issues are no longer tracked in GitHub. It isn't clear if the issue was actually completed or not, and I don't know where maintenance issues are now tracked.

Is using an external Solr 6.6 supported, or should I only use the internal installation? If it is supported, is there a way to resolve these errors or is this a bug in the schema?

**Comment by mark-cooper** [comment]
Hi @kloor apologies for the slow response. External Solr is not officially supported at the moment, which means there is no testing done by the program team to confirm that an externally hosted Solr is fully compatible with ArchivesSpace. That is a goal, but not a reality yet. The only supported version is the embedded 4.10.4 Solr. 

We do know that external Solr is used by some institutions and that they've had success with it. Aside from this issue I haven't heard of a problem with external Solr yet. Where you able to resolve your problem? If you did and can report back anything you did differently to make it work we can get that information into the technical document to help out others who may run into something similar.

**Comment by Blake-** [comment]
Someone else reported getting it running, this is what they said they did

```
I copied the entries for dates, extents from the other schema file in the solr directory, and then additionally this one
<dynamicField name="*_u_icusort" type="sort_icu" indexed="true" stored="true" multiValued="false"/>
```

**Comment by quoideneuf** [comment]
ArchivesSpace currently pairs with Solr 8.1.x, so this issue should be closed.
