### ISSUE TITLE
Dates Column in the Resources view isn't displaying correctly

### ISSUE THREAD

**Issue by Geoffsc** [archivesspace/archivesspace#1986]
We're trying to upgrade ArchivesSpace from 2.6.0 to 2.8.0. We noticed that in 2.8.0 the dates on the Resources view aren't displaying correctly. Screenshots are below:

![resources-260](https://user-images.githubusercontent.com/28767461/94862602-38410700-0407-11eb-9417-b56fb8e01688.png)
![resources-280](https://user-images.githubusercontent.com/28767461/94862605-38d99d80-0407-11eb-8e74-9347959b33b2.png)

We checked our customized plugins but aren't seeing anything obvious that would affect this view. Please let me know if I can provide any more information that may be helpful.

Server OS is Oracle Linux 7.8
Database is MySQL 5.7

**Comment by lorawoodford** [comment]
Hi @Geoffsc : Did you ensure that you forced a FULL reindex as part of the upgrade process and as documented in the [release notes](https://github.com/archivesspace/archivesspace/releases/tag/v2.8.0)?  (Delete everything in the `data/` directory, but not the directory itself... more instructions here: https://archivesspace.github.io/tech-docs/administration/indexes.html).  The behavior you're witnessing suggests that a reindex wasn't completed/successful.

**Comment by Geoffsc** [comment]
Thanks so much, it looks like that resolved the issue! We'll be sure to pay closer attention to the release notes in the future :)
