### ISSUE TITLE
“resolve” parameter examples in API docs are very unclear or wrong

### ISSUE THREAD

**Issue by t4k** [archivesspace/archivesspace#2023]
Many endpoints in the API have an optional resolve parameter.

> [String] resolve (Optional) – A list of references to resolve and embed in the response

The example for this parameter is usually formatted like this:

> `?resolve[]=[record_types, to_resolve]`

The bracket use with multiple placeholder words are very misleading.

## Expected Behavior
I should be able to add the `?resolve[]=[resource, top_container]` parameter to my API call by replacing the placeholders and get `_resolved` elements returned.

The documentation specifies a "list of references to resolve", so what to do with a single record type? Brackets or not? `?resolve[]=[top_container]` seems like what is suggested…

## Current Behavior
I get no `_resolved` elements.

## Possible Solution
I only got single record types to work like `?resolve[]=top_container`, but also got multiple record types to work by repeating the `resolve` parameter, like `?resolve[]=top_container&resolve[]=resource`.

## Steps to Reproduce (for bugs)
See above for failing and working examples. Using ArchivesSnake, which may contribute to the problem, but I don't have the patience to deal with authenticating sessions to use with cURL, so I haven't tested it directly.

## Context
For weeks I had given up on trying to use the `resolve` parameter and coded around it by doing multiple API calls. Inspiration struck again today to really try and figure it out. Some extra guessing and searching on Slack channels got me the right combination of quotes and brackets and formatting to get something to work right. Maybe now I will rewrite my application to be a little more efficient.

## Your Environment

* Version used: 2.8.0
* Python 3.8.5
* Operating System and version (desktop or mobile): macOS 10.15.6
* Example code:
```
from asnake.client import ASnakeClient
client = ASnakeClient()
client.authorize()
get_response = client.get(f"/repositories/2/archival_objects/1234?resolve[]=parent&resolve[]=top_container").json()
print(json.dumps(get_response, sort_keys=True, indent=4))
```

**Comment by quoideneuf** [comment]
API Documents have been updated since this was files and hopefully are clearer now. See for example:
http://archivesspace.github.io/archivesspace/api/#get-a-list-of-resources-for-a-repository
