### ISSUE TITLE
Linking Events to Agents - 1.2.3 - dev.05

### ISSUE THREAD

**Issue by jdshaw** [archivesspace/archivesspace#203]
When attempting to link an event to an agent from the agent record, I get a Routing Error on save of the event. This error occurs if I attempt to create the agent from the event or link to an existing agent.

Running against the local derby db in Mac OS 10.9.5, FF 37.

Thanks!
Joshua

Error displayed in browser:
Routing Error
No route matches {:controller=>"agent_people", :action=>"edit", :id=>2}
Try running rake routes for more information on available routes. 

Error log snippet:
Completed 200 OK in 47.0ms (Views: 3.0ms)
Started GET "/has_session" for 0:0:0:0:0:0:0:1 at 2015-05-12 17:14:14 -0400
Processing by SessionController#has_session as */*
Completed 200 OK in 3.0ms (Views: 1.0ms)
Started POST "/events" for 0:0:0:0:0:0:0:1 at 2015-05-12 17:14:14 -0400
Processing by EventsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"g3sSKWFwxj91ismCu8t1iQVBEHu3xV9VTyIuy7luE/E=", "event"=>{"lock_version"=>"", "event_type"=>"acknowledgement_sent", "outcome"=>"", "outcome_note"=>"", "chronotype_label"=>"subrecord", "date"=>{"lock_version"=>"", "label"=>"agent_relation", "expression"=>"", "date_type"=>"single", "begin"=>"2015-05-08", "certainty"=>"", "era"=>"", "calendar"=>""}, "linked_agents"=>{"0"=>{"role"=>"recipient", "_resolved"=>["{\"id\":\"/agents/people/3\",\"title\":\"Carini, Peter\",\"primary_type\":\"agent_person\",\"types\":[\"agent_person\",\"agent\"],\"json\":\"{\\\"lock_version\\\":1,\\\"publish\\\":false,\\\"created_by\\\":\\\"admin\\\",\\\"last_modified_by\\\":\\\"admin\\\",\\\"create_time\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"system_mtime\\\":\\\"2015-05-12T21:08:59Z\\\",\\\"user_mtime\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"jsonmodel_type\\\":\\\"agent_person\\\",\\\"linked_agent_roles\\\":[],\\\"external_documents\\\":[],\\\"notes\\\":[],\\\"dates_of_existence\\\":[],\\\"names\\\":[{\\\"lock_version\\\":0,\\\"primary_name\\\":\\\"Carini\\\",\\\"rest_of_name\\\":\\\"Peter\\\",\\\"sort_name\\\":\\\"Carini, Peter\\\",\\\"sort_name_auto_generate\\\":true,\\\"created_by\\\":\\\"admin\\\",\\\"last_modified_by\\\":\\\"admin\\\",\\\"create_time\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"system_mtime\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"user_mtime\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"authorized\\\":true,\\\"is_display_name\\\":true,\\\"source\\\":\\\"local\\\",\\\"name_order\\\":\\\"inverted\\\",\\\"jsonmodel_type\\\":\\\"name_person\\\",\\\"use_dates\\\":[]}],\\\"related_agents\\\":[],\\\"uri\\\":\\\"/agents/people/3\\\",\\\"agent_type\\\":\\\"agent_person\\\",\\\"display_name\\\":{\\\"lock_version\\\":0,\\\"primary_name\\\":\\\"Carini\\\",\\\"rest_of_name\\\":\\\"Peter\\\",\\\"sort_name\\\":\\\"Carini, Peter\\\",\\\"sort_name_auto_generate\\\":true,\\\"created_by\\\":\\\"admin\\\",\\\"last_modified_by\\\":\\\"admin\\\",\\\"create_time\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"system_mtime\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"user_mtime\\\":\\\"2015-05-12T21:08:51Z\\\",\\\"authorized\\\":true,\\\"is_display_name\\\":true,\\\"source\\\":\\\"local\\\",\\\"name_order\\\":\\\"inverted\\\",\\\"jsonmodel_type\\\":\\\"name_person\\\",\\\"use_dates\\\":[]},\\\"title\\\":\\\"Carini, Peter\\\",\\\"is_linked_to_published_record\\\":false}\",\"suppressed\":false,\"publish\":false,\"system_generated\":false,\"repository\":\"global\",\"source_enum_s\":[\"local\"],\"name_order_enum_s\":[\"inverted\"],\"created_by\":\"admin\",\"last_modified_by\":\"admin\",\"user_mtime\":\"2015-05-12T21:08:51Z\",\"system_mtime\":\"2015-05-12T21:08:59Z\",\"create_time\":\"2015-05-12T21:08:51Z\",\"source\":\"local\",\"uri\":\"/agents/people/3\",\"jsonmodel_type\":\"agent_person\"}"], "ref"=>["/agents/people/3"]}}, "linked_records"=>{"0"=>{"role"=>"source", "_resolved"=>"{\"lock_version\":3,\"publish\":false,\"created_by\":\"admin\",\"last_modified_by\":\"admin\",\"create_time\":\"2015-05-06T20:53:15Z\",\"system_mtime\":\"2015-05-12T21:08:59Z\",\"user_mtime\":\"2015-05-06T20:53:15Z\",\"jsonmodel_type\":\"agent_person\",\"agent_contacts\":[],\"linked_agent_roles\":[],\"external_documents\":[],\"notes\":[],\"dates_of_existence\":[],\"names\":[{\"lock_version\":0,\"primary_name\":\"Shaw\",\"rest_of_name\":\"Joshua\",\"sort_name\":\"Shaw, Joshua\",\"sort_name_auto_generate\":true,\"created_by\":\"admin\",\"last_modified_by\":\"admin\",\"create_time\":\"2015-05-06T20:53:15Z\",\"system_mtime\":\"2015-05-06T20:53:15Z\",\"user_mtime\":\"2015-05-06T20:53:15Z\",\"authorized\":true,\"is_display_name\":true,\"source\":\"local\",\"name_order\":\"inverted\",\"jsonmodel_type\":\"name_person\",\"use_dates\":[]}],\"related_agents\":[],\"uri\":\"/agents/people/2\",\"agent_type\":\"agent_person\",\"display_name\":{\"lock_version\":0,\"primary_name\":\"Shaw\",\"rest_of_name\":\"Joshua\",\"sort_name\":\"Shaw, Joshua\",\"sort_name_auto_generate\":true,\"created_by\":\"admin\",\"last_modified_by\":\"admin\",\"create_time\":\"2015-05-06T20:53:15Z\",\"system_mtime\":\"2015-05-06T20:53:15Z\",\"user_mtime\":\"2015-05-06T20:53:15Z\",\"authorized\":true,\"is_display_name\":true,\"source\":\"local\",\"name_order\":\"inverted\",\"jsonmodel_type\":\"name_person\",\"use_dates\":[]},\"title\":\"Shaw, Joshua\",\"is_linked_to_published_record\":false}", "ref"=>"/agents/people/2"}}}, "redirect_record"=>"/agents/people/2", "redirect_action"=>"edit"}
D, [2015-05-12T17:14:14.784000 #30954] DEBUG -- : Thread-24548: POST /repositories/2/events [session: #<Session:0x180446da @store={:user=>"admin", :login_time=>2015-05-12 16:56:22 -0400, :expirable=>true}, @id="4e2e81fa92f22b45a17373a0d98217499774a6547382f5bde899313a3830d023">]
D, [2015-05-12T17:14:14.816000 #30954] DEBUG -- : Thread-24548: Post-processed params: {:event=>#<JSONModel(:event) {"event_type"=>"acknowledgement_sent", "date"=>{"label"=>"agent_relation", "date_type"=>"single", "begin"=>"2015-05-08"}, "linked_agents"=>[{"role"=>"recipient", "ref"=>"/agents/people/3"}], "linked_records"=>[{"role"=>"source", "ref"=>"/agents/people/2"}], "jsonmodel_type"=>"event", "external_ids"=>[], "external_documents"=>[]}>, :repo_id=>2}
D, [2015-05-12T17:14:14.923000 #30954] DEBUG -- : Thread-24548: Responded with [200, {"Content-Type"=>"application/json", "Cache-Control"=>"private, must-revalidate, max-age=0", "Content-Length"=>"105"}, ["{\"status\":\"Created\",\"id\":8,\"lock_version\":0,\"stale\":null,\"uri\":\"/repositories/2/events/8\",\"warnings\":[]}\n"]]... in 145.0ms
D, [2015-05-12T17:14:14.925000 #30954] DEBUG -- : Thread-22964: Responded with [200, {"Content-Type"=>"application/json", "Cache-Control"=>"private, must-revalidate, max-age=0", "Content-Length"=>"1120"}, ["[{\"record\":{\"lock_version\":0,\"begin\":\"2015-05-08\",\"created_by\":\"admin\",\"last_modified_by\":\"admin\",\"create_time\":\"2015-05-12T21:14:14Z\",\"system_mtime\":\"2015-05-12T21:14:14Z\",\"user_mtime\":\"2015-05-12T21:14:14Z\",\"date_type\":\"single\",\"label\":\"agent_relation\",\"jsonmodel_type\":\"date\"},\"uri\":null,\"sequence\":1431464178,\"timestamp\":1431465254922}... in 15719.0ms
Redirected to 
Completed 404 Not Found in 172.0ms

ActionController::RoutingError (No route matches {:controller=>"agent_people", :action=>"edit", :id=>2}):
  app/controllers/events_controller.rb:66:in `create'
  app/controllers/application_controller.rb:117:in `handle_crud'
  app/controllers/events_controller.rb:48:in `create'

**Comment by cfitz** [comment]
Hi.

Just doing some house cleaning. I believe this was fixed. Just wanted to verify.

**Comment by bdwestbrook** [comment]
If I understand the question, it is possible now to link an event record to an agent and the linked event record then displays at the bottom of the agent record in the view mode.  I only linked an event to one person record, but I assume all is fine for all types of agent records.

**Comment by jdshaw** [comment]
Yes, this is fixed. I think there was also a feature request tied to this to add viewing of the linked event records on both view and edit modes. View mode is there, but I believe that the linked record is still not viewable in edit mode.

Thanks,
Joshua

From: Brad Westbrook
Reply-To: archivesspace/archivesspace
Date: Thursday, September 17, 2015 at 9:22 AM
To: archivesspace/archivesspace
Cc: Joshua Shaw
Subject: Re: [archivesspace] Linking Events to Agents - 1.2.3 - dev.05 (#203)

If I understand the question, it is possible now to link an event record to an agent and the linked event record then displays at the bottom of the agent record in the view mode. I only linked an event to one person record, but I assume all is fine for all types of agent records.
