### ISSUE TITLE
Bulk Importer creates arbitrary date type enumerations

### ISSUE THREAD

**Issue by jdshaw** [archivesspace/archivesspace#2035]
The Bulk importer is not validating date types properly. A user can create an arbitrary date type - especially when importing via CSV. The importer flags the type as an error, but creates a new enumeration anyway. This leads to multiple issues when rendering date subforms since templates for these arbitrary types do not exist.

## Expected Behavior

The importer validator should reject these arbitrary types and fail to import any data.

## Current Behavior

Importer allows arbitrary date types.

## Steps to Reproduce (for bugs)

1. Create a CSV bulk import template with at least one date entry
2. Make the date type any arbitrary value. I chose 'Bulk'. Note the capital 'B'
3. Import the spreadsheet.
4. Though the importer recognizes the error, it successfully completes and adds the new enumeration

Log:

```
Start new bulk_import for job: 34
==================================================
bulk_import_VFIRST01_test01.csv
==================================================
Row 3: Created Archival Object 'The first series, 2010 - 2020, 2020' /repositories/2/archival_objects/44 fe6fd4a6cc56dd2cdd5989a16e56710a
Row 3:	ERROR Date type [Bulk] invalid for (Date: type:Bulk, label: , begin: 2010, end: 2020, expression: ). Defaulting to 'inclusive'
The file has been processed
==================================================
Completed import of bulk_import_VFIRST01_test01.csv

==================================================
Compiling results CSV file
```

## Context

Attempt to create a date subrecord in any object. You will notice a new date type and experience multiple errors associated with the new type.

## Your Environment

* Version used: test.archivesspace.org, local build from master
* Environment name and version (e.g. Chrome 39, node.js 5.4): All
* Operating System and version (desktop or mobile): Mac O/S 10.13
* Link to your project:

**Comment by lorawoodford** [comment]
I believe #2037 resolves this issue.  Feel free to reopen/submit a new issue if necessary.
