### ISSUE TITLE
problem generating PDF from resource where an archival object has '&' character in title

### ISSUE THREAD

**Issue by hading** [archivesspace/archivesspace#2059]
Suppose we have a resource and an archival object under that resource has a title with the '&' character. For example we have some with the string "R&R" in them, e.g. the example below.

## Expected Behavior

- Go to resource page
- Click 'Print' button
- PDF will be generated and user can download

## Current Behavior
After clicking Print the browser may spin for a while and then there is an error page.

## Possible Solution
Probably something requires quoting. 

The log points right to the problem:
`I, [2020-11-11T12:30:54.892615 #35996]  INFO -- : [969607ad-2dc0-4b93-92c1-0a2772d5232d] Completed 500 Internal Server Error in 29707ms
F, [2020-11-11T12:30:54.894224 #35996] FATAL -- : [969607ad-2dc0-4b93-92c1-0a2772d5232d]
F, [2020-11-11T12:30:54.894306 #35996] FATAL -- : [969607ad-2dc0-4b93-92c1-0a2772d5232d] RuntimeError (Failed to clean XML: The reference to entity "R" must end with the ';' delimiter.):
F, [2020-11-11T12:30:54.894372 #35996] FATAL -- : [969607ad-2dc0-4b93-92c1-0a2772d5232d]
F, [2020-11-11T12:30:54.894463 #35996] FATAL -- : [969607ad-2dc0-4b93-92c1-0a2772d5232d] app/lib/xml_cleaner.rb:32:in `clean'
[969607ad-2dc0-4b93-92c1-0a2772d5232d] app/models/finding_aid_pdf.rb:94:in `generate'
[969607ad-2dc0-4b93-92c1-0a2772d5232d] app/controllers/pdf_controller.rb:15:in `resource'
`

It seems likely that the literal 'R&R' in the title is being cast into XML without being quoted, and hence it thinks that '&R' is an entity.

## Steps to Reproduce (for bugs)
This happens at https://archives.tricolib.brynmawr.edu/resources/hcmc-1130. Visit the page, click the 'Print' button in the upper right. Wait about 30s and an error screen with be displayed because of the 500 error shown in the log snippet above.

## Context
Users are unable to generate PDFs of such resources.

## Your Environment
ArchivesSpace 2.8.0 on Centos 6.10

**Comment by hading** [comment]
It has been pointed out to me that this may already have been reported and solved:

https://archivesspace.atlassian.net/browse/ANW-1111

If so please feel free to close this.

**Comment by lorawoodford** [comment]
Thanks for the report @hading .  Yes, this should be fixed as of https://github.com/archivesspace/archivesspace/releases/tag/v2.8.1 which includes #1985 .  If you find any issues feel free to submit a new issue!

**Comment by seanlw** [comment]
I have a similar issue in 3.0.1 using the title `2217, Hines, Galleria North 1&2, 2000-04-10` so PDF fails if `&` or `&amp;` followed by a number.
