### ISSUE TITLE
set :on_delete => :cascade for tables with foreign key constraints?

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/archivesspace#2068]
Our IT folks recently updated our Maria DB instance and turned on error logging for debugging, and now they tell me they're seeing errors like this:

```
ERROR 1451: Cannot delete or update a parent row: a foreign key constraint fails
(`archivesspace2`.`instance_do_link_rlshp`, CONSTRAINT `instance_do_link_rlshp_ibfk_2` FOREIGN KEY (`instance_id`)
REFERENCES `instance` (`id`)) : DELETE FROM `instance` WHERE (`id` IN (2106572))
```

It looks like some tables have their foreign key constraints set with `:on_delete => :cascade` in this migration:
https://github.com/archivesspace/archivesspace/blob/master/common/db/migrations/059_add_on_cascade_delete_to_repo_fk.rb#L15

But I'm not seeing that set for other tables. Is this something that should happen? I think that this would make these errors go away. We're also seeing similar errors related to the foreign key constraint between instance and sub_container.

(For the record, I haven't heard any complaints from users related to this, so my guess is that this error isn't raising an exception within the application itself, at least not in such a way that users notice)

**Comment by Blake-** [comment]
...` and turned on error logging for debugging`

You mean that turned on error logging by setting db_debug_log set to true? If so...

https://archivesspace.atlassian.net/browse/ANW-811

If not... maybe a Maria error? What version of Maria are you running that?

**Comment by trevorthornton** [comment]
@Blake - They turned on error logging on the MariaDB server, which hosts multiple databases. We're running Maria 10.5.

I was able to duplicate the error using a direct database query (ie deleting an instance record raises a foreign key constraint error) but removing an instance in the staff interface is fine, which indicates that the associated record is being destroyed by ActiveRecord via a before_destroy callback (or something similar).

I'm going to close this issue since it's not actually causing any problems beyond the errors in the log, which may be caught and handled in the application. Sorry!
