### ISSUE TITLE
Adding Python API examples to subject

### ISSUE THREAD

**Issue by bobbi-SMR** [archivesspace/archivesspace#2083]
I am about to submit a PR to add examples of python API examples to `backend/app/controllers/subject.rb` .  This covers the CRUD endpoints.
## Expected Behavior

After compilation of the API documentation, new examples will appear under the python tab for the subject endpoints
## Current Behavior

No python examples exist
## Possible Solution

Submitting my PR :-)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lorawoodford** [comment]
Resolved by #2084 and #2251
