### ISSUE TITLE
"Found in" hierarchical links in "Linked Records" section of Agent record in the staff interface are a bit buggy now

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#2094]
## Steps to Reproduce
1. Log into http://test.archivesspace.org/staff/ as 'admin'
2. Make sure you're in the YNHSC repository
3. Go to an agent record that has linked record, like this one, http://test.archivesspace.org/staff/agents/agent_person/116#tree::resource_42 
4. Click on any of the "Found in" in links.
5. That webpage will load embedded in the current div (looking like an iframe), before it disappears, and nothing else happens.

I'll also attach two screenshots that illustrate this issue taken from the ANW-429 version of the application, where I noticed this.

## Expected Behavior

Not sure how the "Found in" stuff functions elsewhere, but I assume the intention is for the linked record to open up in a new tab, instead of what happens now.

## Your Environment

* Version used: 2.8.1
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fordmadox** [comment]
<img width="903" alt="Screen Shot 2021-01-15 at 10 46 57 AM" src="https://user-images.githubusercontent.com/552366/104760182-01310000-572f-11eb-9c25-6cc42d96211a.png">

**Comment by fordmadox** [comment]
And if you click on that Rush papers link (or Letters, etc.), this happens (for a moment):

<img width="917" alt="Screen Shot 2021-01-15 at 12 42 36 PM" src="https://user-images.githubusercontent.com/552366/104760310-2cb3ea80-572f-11eb-8a06-987ab0daf81b.png">

**Comment by cdibella** [comment]
Just a note for when we get there that one of the agents testers pointed this out too. 

According to @jdshaw "The hierarchy links javascript should be updated to account for the presence of the links in this linked records area.
 
The js that's triggering the error: https://github.com/archivesspace/archivesspace/blob/master/frontend/app/assets/javascripts/ajaxtree.js.erb#L49 "
