### ISSUE TITLE
Nasty bug with new "view contact details for agent records" role.

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#2110]
## Expected Behavior

Don't delete data that a user cannot see.

## Current Behavior

If a user who doesn't have permission to view contact details of an agent record happens to edit an agent record that has contact details, then the pre-existing (hidden from view) contact details are DELETED.  

## Steps to Reproduce (for bugs)

1.  Log in as 'admin' at http://test.archivesspace.org/
2. Create a new agent and assign it contact details (e.g. http://test.archivesspace.org/staff/agents/agent_person/556)
3. Create a new user and assign that user to a group that can edit agents but does not have the "view contact details for agent records" role (e.g. the default "Advanced Data Entry users" group)
4. Log in as that user and edit the newly-created agent record, which had contact details.
5. Log back in as 'admin' to see that the recently edited agent record no longer has contact details.

I'll also attach before an after pictures.  

## Your Environment

* Version used: ASpace 2.7.1 and greater.
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fordmadox** [comment]
1) 
<img width="1020" alt="Screen Shot 2021-02-01 at 12 15 31 PM" src="https://user-images.githubusercontent.com/552366/106494327-4885f300-6488-11eb-94f3-bf1a800b0be7.png">

2)
<img width="1213" alt="Screen Shot 2021-02-01 at 12 16 27 PM" src="https://user-images.githubusercontent.com/552366/106494363-550a4b80-6488-11eb-80b0-ba3cb48837d8.png">

3)
<img width="1240" alt="Screen Shot 2021-02-01 at 12 17 14 PM" src="https://user-images.githubusercontent.com/552366/106494384-5b98c300-6488-11eb-868b-a2e9fa3d9743.png">

**Comment by lorawoodford** [comment]
Resolved by #2122
