### ISSUE TITLE
Mimemagic gem

### ISSUE THREAD

**Issue by Hurlyburly2** [archivesspace/archivesspace#2163]
The mimemagic gem appears to have been updated to 0.3.7 today, which must've been accompanied by the yanking of 0.3.5 https://rubygems.org/gems/mimemagic/versions/0.3.5. This prevents bootstrapping.

## Expected Behavior
Bootstrap correctly

## Current Behavior
bundler:
     [echo] Fetching gems for ../frontend/Gemfile
     [java] WARNING: The parameter 'bulk_import_rows' is now deprecated.
     [java] WARNING: The parameter 'bulk_import_size' is now deprecated.
     [java] Fetching gem metadata from https://rubygems.org/.........
     [java] Your bundle is locked to mimemagic (0.3.5), but that version could not be found
     [java] in any of the sources listed in your Gemfile. If you haven't changed sources,
     [java] that means the author of mimemagic (0.3.5) has removed it. You'll need to update
     [java] your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
     [java] in order to install.

BUILD FAILED
/home/runner/work/archivesspace/archivesspace/build/build.xml:207: The following error occurred while executing this line:
/home/runner/work/archivesspace/archivesspace/build/build.xml:408: Java returned: 7

## Possible Solution
Gem update

## Steps to Reproduce (for bugs)
build/run bootstrap

**Comment by ktamaral** [comment]
This appears to be the same issue that is causing all three tests to fail in this open PR: https://github.com/archivesspace/archivesspace/pull/2147

**Comment by ktamaral** [comment]
As you may already know this appears to be related to this rails issue: https://github.com/rails/rails/issues/41750

**Comment by quoideneuf** [comment]
Looks like going forward Mac users will need to `brew install shared-mime-info`

https://github.com/mimemagicrb/mimemagic

**Comment by lorawoodford** [comment]
Hopefully resolved by #2165

**Comment by quoideneuf** [comment]
Until there is a replacement gem, ArchivesSpace distributions (zip packages) will not include the shared-mime-info library. System admins installing the application may need to install the shared-mime-info package prior to running the application. See:
https://github.com/rails/rails/issues/41750#issuecomment-805977682
