### ISSUE TITLE
Frontend en.yml appears to override public en.yml

### ISSUE THREAD

**Issue by Hurlyburly2** [archivesspace/archivesspace#2177]
When a value is defined both in a frontend en.yml and public en.yml, the frontend.yml's value appears to take precedence, even in the case of display on the public interface. We've noticed this occurring in our plugins as we upgrade from version 2.5.2 to 2.8.1. The issue does not occur in version 2.7, but DOES appear in the version 3.0 release candidate.

## Expected Behavior
The public ui should use values defined in a public en.yml.

## Current Behavior
The public ui uses the values defined in a frontend en.yml.

## Possible Solution
I'm unsure as to a solution, but the problem definitely occurred due to one of the changes between release versions 2.7 and 2.8.1.

## Steps to Reproduce (for bugs)
1. Download and unzip a release of Archivesspace version 2.8.1 or higher. (The issue does not appear in 2.7)
2. Create the below two new files. Note that the problem occurs with other fields, but I found 'digital object' easy to test. I noticed no behavior changes with or without the `&digital_object_attributes` tag:
plugins/local/frontend/locales/en.yml:
```
en:
  digital_object:
    _plural: LOCAL/FRONTEND
```
plugins/local/public/locales/en.yml:
```
en:
  digital_object:
    _plural: LOCAL/PUBLIC
```
3. Run archivesspace.sh and navigate to localhost:8081. You will see the digital_object link displaying LOCAL/FRONTEND instead of LOCAL/PUBLIC.
4. You can ensure the public en.yml is set up correctly by removing the frontend one, which will result in the LOCAL/PUBLIC appearing upon restarting aspace.

## Context
This is coming up in our plugins during an upgrade from version 2.5.2 to 2.8.1.

## Your Environment
See steps to reproduce.

**Comment by quoideneuf** [comment]
This is likely related to https://archivesspace.atlassian.net/browse/ANW-1222

**Comment by quoideneuf** [comment]
https://github.com/archivesspace/archivesspace/commit/6c0b185e5f3e86ce1895726789dce43a487c51c2
https://github.com/archivesspace/archivesspace/commit/c6261b021c2433339547f5a838c6d8ec8fb57298
