### ISSUE TITLE
Docs: Broken link in docs

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#231]
http://archivesspace.github.io/archivesspace/doc/ has a link to http://archivesspace.github.io/archivesspace/doc/UPGRADING_1.1.0.md, which doesn't seem to exist.

**Comment by cfitz** [comment]
Hi, the file is here:
https://github.com/archivesspace/archivesspace/blob/master/UPGRADING_1.1.1.md

I've removed that link from the rdoc.
