### ISSUE TITLE
Jira inaccessible to anonymous but looks accessible

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#232]
The Jira instance linked from the documentation will let anonymous users get almost all the way through the issue creation process, but will refuse to submit an issue without a user id.  Jira's messaging treats this like a form submission error on the part of the user.  

This can (and has, in at least one case) lead to user entering bug to some level of detail, hitting enter, scanning form multiple times for field, and only then realizing that they can't actually submit issues via Jira.

**Comment by cfitz** [comment]
Hi. Yes, you have to have a user account to create Jira tickets in the AR project. Please use the https://archivesspace.atlassian.net/projects/AS  project ( which is linked to in the footer of the Staff UI )

**Comment by pobocks** [comment]
Thanks - my primary concern here is that the documentation isn't making it
clear enough.

**Comment by cfitz** [comment]
Hi. Yes, most of this is documented in the Confluence site ( https://archivesspace.atlassian.net/wiki/display/ADC/How+to+Report+a+Bug ). If you have any suggestions, pull requests are definitely welcome/appreciated!
