### ISSUE TITLE
Background jobs stuck at Queued - 1st

### ISSUE THREAD

**Issue by rvanlieshout** [archivesspace/archivesspace#2328]
For some reason background aren't picked up anymore

## Expected Behavior

I would expect jobs not to remain in 'Queued - 1st'

## Current Behavior

Even after a restart jobs get stuck.

## Possible Solution

I'm a developer, but with limited time. Suggestions to where background processed are processed might help me in finding out if it's not picking up a new one or if it's stuck in processing a current one.

## Steps to Reproduce (for bugs)

For us:

1. (re)start Archivesspace
2. Schedule a job

## Context

This prevents us from performing tasks like generating PDF files.

## Your Environment

* Version used: v2.8.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): n/a
* Operating System and version (desktop or mobile): CentOS Linux release 8.4.2105
* Link to your project: archivesspace.nl

**Comment by cdibella** [comment]
Since this is for a member institution, we've put a technical support ticket in for you. You'll be able to follow the progress over email.

**Comment by rvanlieshout** [comment]
Cheers, @cdibella
