### ISSUE TITLE
A variety of MARCXML issues with name-title entries using the LCNAF plugin (example provided)

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#2338]
## Current Behavior

Import a name-title authority record, such as http://id.loc.gov/authorities/names/no2017028402 

Lots of strange things happen.  Check out the dates of existence (which can't be mapped well here, nor can those map to "flourish" dates explicitly for person records, but that's another issue)....  as well as the missing title info, etc.

To review the records imported with this one import, check out http://test.archivesspace.org/staff/jobs/88 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fordmadox** [comment]
In addition to name-title entries, there are also issues with subject headings from LCSH that are complex types that have an agent heading + a subdivision.  

Example:

**Shakespeare, William, 1564-1616--Portraits**
(from https://id.loc.gov/authorities/subjects/sh85121023)

Once that subject heading is imported, an Agent is created in ASpace with "shXXX" as the identifier, but the subheading is lost entirely.   So, just Shakespeare, but not Portrait.  

Not sure how to handle these sorts of headings in the current ASpace data model, but what shouldn't happen is what happens now.  Example:

http://test.archivesspace.org/agents/people/188 / http://test.archivesspace.org/staff/agents/agent_person/188/edit

**Comment by quoideneuf** [comment]
@fordmadox If this is still an issue, please re-file it in JIRA so it can be prioritized.
