### ISSUE TITLE
MariaDB error in name_person table during database upgrade to version 3.0.2

### ISSUE THREAD

**Issue by ccc2lu** [archivesspace/archivesspace#2418]
When running the scripts/setup_database.sh script while upgrading to ArchivesSpace 3.0.2 today, I received an error saying the upgrade failed because the row was too long while adding a field to the name_person table.  When I investigated the issue, I found that the "title" column on that table is 8000 characters long, and the maximum allowed size for a row in my MariaDB instance is 8126 bytes.  

This is a shared MariaDB instance, so just changing a global setting isn't an option for me.  

I worked around the problem by modifying the "title" field of "name_person" to be type text rather than varchar.  Has anyone else encountered this issue?  I hadn't previously made any modifications to the database to change the length or type of any fields.  

The only difference between text and varchar that I know of is that a text field can't be part of an index unless you specify a prefix length for the index, so as long as the "title" field isn't part of an index (doesn't seem to be currently) I don't think this will cause a problem.

**Comment by quoideneuf** [comment]
@ccc2lu If this is still an issue, please file it in JIRA so it may be prioritized.
