### ISSUE TITLE
"Internal Server Error" when attempting to use the "Load via Spreadsheet" button when editing a resource

### ISSUE THREAD

**Issue by ccc2lu** [archivesspace/archivesspace#2473]
If we try to use the "Load via SpreadSheet" button in our ArchivesSpace 3.0.2 instance, we get an error in the browser saying "Internal Server Error".  I'm attaching a screenshot.
## Expected Behavior

The resource should have values loaded into it from the spreadsheet.
## Current Behavior

We get an internal server error.  The logs in archivesspace.out say nothing beyond what's in the browser to help us figure out what the problem is.  The log level is already set to "debug" in our instance, but the only thing in the logs is:
Oct 15, 2021 4:54:18 PM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFO: INFO: resetting rack response due exception: org.jruby.exceptions.IOError: (IOError) No such file or directory
This doesn't help us figure out what file or directory it's talking about to determine if there's a permissions error or something.  Also, I see no configuration values anywhere in config.rb where I can tell ArchivesSpace where to put uploaded files.  Did I miss that?  I feel like that might be related to our problem.
## Steps to Reproduce (for bugs)

1. Edit any resource in the AS staff interface
2. Click the "Load via Spreadsheet" button
3. Select a spreadsheet and click "Load"
4.

## Context

We have student workers who load information into ArchivesSpace from spreadsheets regularly, and can't while this isn't working.  
## Your Environment

* Version used: ArchivesSpace 3.0.2 on Debian Linux 10 "Buster", Java 1.8
* Environment name and version (e.g. Chrome 39, node.js 5.4):Version 94.0.4606.81 (Official Build) (64-bit), but other Chrome versions as well
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: https://archivesspace.lib.lehigh.edu/ (the staff interface is limited to on-campus users, and LDAP authenticated)

Here's the error screenshot:
![ASInternalServerError](https://user-images.githubusercontent.com/5490284/137553213-94f67839-0810-40d2-9003-47d2c2fd6a7b.png)

**Comment by quoideneuf** [comment]
Closing. Please follow this issue here: https://archivesspace.atlassian.net/browse/ANW-1427
