### ISSUE TITLE
Doc update for CSS tweaks

### ISSUE THREAD

**Issue by marktriggs** [archivesspace/archivesspace#257]
Howdy,

I don't think I can send a pull request for a Wiki page, but I just noticed we never really said anything about making small CSS changes to the application.  I've added a note here if you want to merge it into the main version:

https://github.com/marktriggs/archivesspace-wiki/compare/HEAD%5E%5E...master

There's also an unrelated URL fix in there, just because I happened to notice it.

**Comment by cfitz** [comment]
Awesome! Thanks.

**Comment by cfitz** [comment]
Actually, moved this to =>
https://github.com/archivesspace/archivesspace/blob/master/CUSTOMIZING_THEMING.md 

so it gets included in the gh-pages build and can now be seen at: 
http://archivesspace.github.io/archivesspace/user/customizing-and-theming-archivesspace/
