### ISSUE TITLE
Settings sidebar is unnecessary narrow leading to button text being cut-off for longer texts

### ISSUE THREAD

**Issue by nebulon42** [archivesspace/archivesspace#2585]
## Expected Behavior

No cut off text on action buttons no matter how long the text is.

## Current Behavior

Action button text can be cut off leading to not completely legible action button label.

## Possible Solution

Increase width of settings sidebar or let button expand in height when there is more text.
Currently the admin sidebar seems to have a fixed width for larger screen widths. By removing that the issue is resolved as can be seen in the images.

![Bildschirmfoto vom 2021-12-26 13-39-32](https://user-images.githubusercontent.com/3531092/147408430-ea131875-6b0b-49fc-8aff-059f7a336a01.png)
![Bildschirmfoto vom 2021-12-26 13-39-50](https://user-images.githubusercontent.com/3531092/147408431-dfc9c239-2222-46fc-829c-ed2afe47ad6f.png)

## Steps to Reproduce (for bugs)

1. Login into the staff interface with a user that has permissions to manage repositories
2. Go to System > Manage repositories
3. Click on the Create repository button
4. See the sidebar on the left side

## Context

Cut-off labels on action buttons impair the user's ability to see what will happen after clicking on that button.

## Your Environment

* Version used: 3.1.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 95.0.1
* Operating System and version (desktop or mobile): Manjaro Linux 21 Desktop
* Link to your project: N/A

**Comment by quoideneuf** [comment]
@nebulon42 If this is still an issue, please file it in JIRA so it may be prioritized.
