### ISSUE TITLE
i18n: Container profile title cannot be properly translated

### ISSUE THREAD

**Issue by nebulon42** [archivesspace/archivesspace#2605]
## Expected Behavior

The title of a container profile should be fully i18n aware including dimension units and dimensions.

## Current Behavior

So far the container profile title was not translatable at all. I have changed that (PR #2606) but I have not found out how to translate the dimension units and dimensions included in the title because those seem to just be internal values that are by coincidence readable to English speakers.
![Bildschirmfoto vom 2022-01-12 22-19-26](https://user-images.githubusercontent.com/3531092/149223486-ce1ff7ff-cade-4fe9-a856-70f16546d33b.png)

## Possible Solution

I think the internal values for dimension units and dimensions to create a container profile object instance need to be translated before passed to the container profile.

## Steps to Reproduce (for bugs)

1. set language to other than en
2. create container profile
3. observe title in container profile listing

## Context

Non-english speaking users expect a fully translatable UI.

## Your Environment

* Version used: master
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): N/A
* Link to your project: N/A

**Comment by quoideneuf** [comment]
@nebulon42 Please file this in JIRA so it may be prioritized.
