### ISSUE TITLE
l10n: date format should be adjustable

### ISSUE THREAD

**Issue by nebulon42** [archivesspace/archivesspace#2615]
## Expected Behavior

For localization date formats should adjustable for users as in different parts of the world different date formats are used.

## Current Behavior

At least the record citation in [public/app/models/record.rb#L363](https://github.com/archivesspace/archivesspace/blob/master/public/app/models/record.rb#L363) uses a non-adjustable date pattern which resolves to e.g. January 18, 2022 which is an Anglo-American way of writing a date. In e.g. German speaking countries one would rather write 18. January 2022.

## Possible Solution

Analyse classes of used dates and provide settings in AppConfig where users can adjust dates if necessary and then use those config values in code. 

## Context

In addition to i18n users also expect a localized variant of a software so that they feel comfortable in using it and it aligns with their mental models.

## Your Environment

* Version used: master
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): N/A
* Link to your project: N/A

**Comment by quoideneuf** [comment]
@nebulon42 Please file this in JIRA so that it may be prioritized.
