### ISSUE TITLE
Javascript files contain I18n translations that only affect build process

### ISSUE THREAD

**Issue by quoideneuf** [archivesspace/archivesspace#2629]
See for example: 
`var label = '<%= I18n.t("tree.resize") %>';`
https://github.com/archivesspace/archivesspace/blob/master/frontend/app/assets/javascripts/tree.js.erb#L20

The intention was probably to make this label dynamic like other locale values, but due to asset precompiling it just hardcodes the string to whatever `AppConfig[:locale]` is set to at build time. 

So as is it is probably useless and potentially troublesome.

**Comment by brianzelip** [comment]
@quoideneuf I can't replicate this issue given the code linked above. When I visit https://test.archivesspace.org/staff/resources/1/edit#tree::resource_1, and check the dev tools tab for js files ('Debugger' in Firefox), I see the properly interpolated i18n string in the run time code for the particular line you linked to above (line 3779 of the tree.js file).

**Comment by quoideneuf** [comment]
@brianzelip I think the issue is that stopping the application, changing the locale in the config file, and restarting will not work, since the asset was compiled. But I am going to close this anyway since it seems like no one is having an issue with it.
