### ISSUE TITLE
Investigate Solr Checksum Verification

### ISSUE THREAD

**Issue by quoideneuf** [archivesspace/archivesspace#2634]
If a admin misnames the core or makes some other installation / setup error, are the still being the checksum error? If so, we need to add some more specific error handling. @mark-cooper @quoideneuf first to self-assign gets to do it.

**Comment by joewcc** [comment]
Hi, Team,

We were running Archivesspace 2.7.1 before, currently trying to upgrade to 3.2.0. After we had solr-8.11.1 installed and tried to use it in Archivesspace 3.2.0, we met trouble to connect. Following were the error messages in the Archivesspace Log:


--- Backtrace
RuntimeError: Solr checksum verification failed (schema): expected [4d4849771a91d677f255b638cbefa8b8d67a236c56c645bb13c2842480614d78] got [5d5
cd6bba2fcf013a922dee5222c069799a9d8a7e0336c896bef544f0cc401f9]
              verify_checksum! at /usr/local/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-6773433354000918359/webapp/WEB-INF/ap
p/model/solr.rb:79
             verify_checksums! at /usr/local/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-6773433354000918359/webapp/WEB-INF/ap
p/model/solr.rb:72
          ArchivesSpaceService at /usr/local/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-6773433354000918359/webapp/WEB-INF/ap
p/main.rb:149
                     configure at /usr/local/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1426
  <class:ArchivesSpaceService> at /usr/local/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-6773433354000918359/webapp/WEB-INF/app/main.rb:96
                        <main> at /usr/local/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-6773433354000918359/webapp/WEB-INF/app/main.rb:43
                       require at org/jruby/RubyKernel.java:974
                       require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
                        <main> at /usr/local/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-6773433354000918359/webapp/WEB-INF/config.ru:4
                 instance_eval at org/jruby/RubyBasicObject.java:2622
                    initialize at uri:classloader:/vendor/rack-2.2.3/rack/builder.rb:125
                        <main> at /usr/local/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-6773433354000918359/webapp/WEB-INF/config.ru:1
                  start_server at launcher/launcher.rb:90
                          main at launcher/launcher.rb:144
                        <main> at launcher/launcher.rb:242

How could we get this issue resolved?

Thanks very much!

Joe

**Comment by quoideneuf** [comment]
@joewcc At this time that error likely means one of two things: your Solr "core" is not set up, or it is setup but with configuration files that may not be compatible with your version of ArchivesSpace. You can try putting this in the `config/config.rb` file to see which is the case:
`AppConfig[:solr_verify_checksums] = false`
This will allow the application to startup and you can then see if you are able to visit search pages and record listings in the application.

**Comment by joewcc** [comment]
Hi, Brian,

You are right. The issue has been fixed. Please feel free to close the case out.

Appreciated your help very much!

Joe

From: Brian Hoffman ***@***.***>
Sent: Tuesday, March 22, 2022 10:02 AM
To: archivesspace/archivesspace ***@***.***>
Cc: Zhou,Joseph ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [archivesspace/archivesspace] Investigate Solr Checksum Verification (Issue #2634)

** WARNING: This email originated from outside of the WCC organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. **


@joewcc<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoewcc&data=04%7C01%7Cjozhou%40wccnet.edu%7Cf1989e0db152455f897c08da0c0caec6%7Cec4c99b641114ea0bd5a735a0ae10394%7C0%7C0%7C637835545887125052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=POH1CfwvRkR0KuzH9iwhKcWVkWI7WNVdfhwpXHynsvc%3D&reserved=0> At this time that error likely means one of two things: your Solr "core" is not set up, or it is setup but with configuration files that may not be compatible with your version of ArchivesSpace. You can try putting this in the config/config.rb file to see which is the case:
AppConfig[:solr_verify_checksums] = false
This will allow the application to startup and you can then see if you are able to visit search pages and record listings in the application.

-
