### ISSUE TITLE
Bulk import template - multiple columns possible for same Note type?

### ISSUE THREAD

**Issue by KistWright** [archivesspace/archivesspace#2652]
I'm trying to include multiple entries of the same Note type per row in the bulk import template. Specifically, I need to include two separate 'Materials Specific Details' entries to record a start time and end time for a digital object. I've been using the field code 'n_materialspec' without issue. Is there a way to add more? e.g. 'n_2_materialspec', etc. Thanks!

**Comment by quoideneuf** [comment]
@KistWright Please file this issue in JIRA so it may be prioritized.
