### ISSUE TITLE
Backend API error response for malformed resource is misleading

### ISSUE THREAD

**Issue by mistydemeo** [archivesspace/archivesspace#266]
This is a minor issue but I thought I'd mention it.

When POSTing a new archival object, if the provided resource ID is malformed, the error message returned by the API is moderately misleading. The message is "Must be a JSONModel(:resource) uri (you provided a String)", which doesn't immediately make the cause clear.

For example, here's a response returned when the resource ID was typoed as `/repositories/resources/2` instead of `/repositories/2/resources/2`.

```json
{
  "invalid_object": "#<JSONModel(:archival_object) {\"level\"=>\"series\", \"resource\"=>{\"ref\"=>\"/repositories/resources/2\"}, \"parent\"=>{\"ref\"=>\"/repositories/2/archival_objects/2\"}, \"jsonmodel_type\"=>\"archival_object\", \"title\"=>\"Test bad resource\", \"external_ids\"=>[], \"subjects\"=>[], \"linked_events\"=>[], \"extents\"=>[], \"dates\"=>[], \"external_documents\"=>[], \"rights_statements\"=>[], \"linked_agents\"=>[], \"component_id\"=>\"\", \"restrictions_apply\"=>false, \"instances\"=>[], \"notes\"=>[]}>",
  "warning": null,
  "error": {
    "resource/ref": [
      "Must be a JSONModel(:resource) uri (you provided a String)"
    ]
  }
}
```

**Comment by cfitz** [comment]
Hi. Thanks...yeah that's not very clear. I added something that adds this :+1: 
" (malformed or invalid uri? check if referenced object exists.)"

do you think that helps?

**Comment by mistydemeo** [comment]
Yes, thank you!
