### ISSUE TITLE
Location of Popup of help center

### ISSUE THREAD

**Issue by DonRichards** [archivesspace/archivesspace#2669]
The popup location covered the sprocket next to it. Frequently when trying to click the sprocket I accidentally hover over the "?" and trigger the popup. This behavior can be frustrating and is easily addressed with a CSS shift.

## Expected Behavior
Popup should pop up and not directly over the neighboring button.

## Current Behavior
Button covers the manage sprocket if briefly hovered over.
![2022-03-23_09-42](https://user-images.githubusercontent.com/2738244/159715041-f6ed096e-8712-43d0-bd63-bc5e016d8556.png)

## Possible Solution
Change location via CSS to put position up/top
```css
...
  position: relative;
  top: -30px;
...
```
![2022-03-23_09-59](https://user-images.githubusercontent.com/2738244/159716881-a824940a-05c5-4fc4-a414-2739f3e93005.png)

## Steps to Reproduce (for bugs)

1. Place mouse over the question mark next to the manage sprocket.
2. Try to quickly click on the sprocket.
3. Blocked by the help popup

## Context
N/A

## Your Environment
N/A

**Comment by quoideneuf** [comment]
I believe this has been resolved, but if not please open it in JIRA.
