### ISSUE TITLE
Validation error: missing dates of existence label field

### ISSUE THREAD

**Issue by antbrown** [archivesspace/archivesspace#2833]
## Expected Behavior

I expect to be able to enter a valid date range under dates of existence for an Agent record, Save and have no validation errors.

## Current Behavior

I get a Validation error which tells me that there is a missing dates of existence label field.

## Possible Solution

Unsure sorry, I don't have a lot of experience with the ArchivesSpace codebase, but maybe we need to ensure the hidden field is getting the right field name? Maybe it already does have the correct name and the processing is getting confused?

I think the hidden field is included on the form here:

https://github.com/archivesspace/archivesspace/blob/v3.2.0/frontend/app/views/dates/_template.html.erb#L37 

## Steps to Reproduce (for bugs)

Refer to user guide: https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/1942945864/Agent+Record+Fields+from+3.0

1. Create a Person Agent record, give it a name.
2. Add a Dates of Existence record, see Label field is now hidden, I'll attach some screenshots.

## Context

Client is trying to add Agent records and describe dates of existence.

## Your Environment

* Version used: 3.2.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 104.0
* Operating System and version (desktop or mobile): Ubuntu 20.04 desktop
* Link to your project: It's on a UAT server, so unavailable to public at the moment sorry.

## Screenshots

![hidden-dates-of-existence-label](https://user-images.githubusercontent.com/1214401/193133397-227c9700-2d34-4d72-bca4-05a6a1ac6993.png)

![dates-of-existence-example](https://user-images.githubusercontent.com/1214401/193133431-858f29e4-6ca7-4b07-9042-750525ff0bb4.png)

![validation-failed-field-not-found](https://user-images.githubusercontent.com/1214401/193133456-991171a4-2672-44e8-b1fc-21772310d744.png)

**Comment by antbrown** [comment]
In the logs it looks like the label is coming through fine in the data submitted:

```
"dates_of_existence"=>{"0"=>{"date_label"=>"existence", "date_type_structured"=>"single", "date_certainty"=>"", "date_era"=>"", "date_calendar"=>"", "structured_date_single"=>{"lock_version"=>"", "date_role"=>"begin", "date_expression"=>"1994-01-01", "date_standardized"=>"", "date_standardized_type"=>"standard"}}}}
```

I'll attach log here:  

[save-agent-dates-of-existence.log](https://github.com/archivesspace/archivesspace/files/9804746/save-agent-dates-of-existence.log)

But, still coming back with the same error... anyone have any ideas of what else we can check?

**Comment by quoideneuf** [comment]
Fixed for future versions here:
https://github.com/archivesspace/archivesspace/pull/2866
For your current problem, go to System > Manage Controlled Value Lists and select `date_label` and add a value `existence` and Bob's your uncle. Reopen this issue if it doesn't work.

**Comment by antbrown** [comment]
@quoideneuf thank you :) this worked and has got us back on track, much appreciated.
