### ISSUE TITLE
build_release zip  from current master won't run. 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#284]
I ran  `./scripts/build_release master-09-23 ` from current master,
unzipped file and cd-ed to directory. On attempting to start I get this:

    archivesspace$ ./archivesspace.sh
    ArchivesSpace base directory: /projects/Archivespace/archivesspace
    TypeError: can't convert nil into String
                 exists? at org/jruby/RubyDir.java:624
     find_base_directory at file:/projects/Archivespace/archivesspace/lib/common.jar!/asutils.rb:85
                    find at org/jruby/RubyEnumerable.java:594
     find_base_directory at file:/projects/Archivespace/archivesspace/lib/common.jar!/asutils.rb:82
     find_local_directories at file:/projects/Archivespace/archivesspace/lib/common.jar!/asutils.rb:92
                   setup at file:/projects/Archivespace/archivesspace/lib/common.jar!/aspace_gems.rb:30
                  (root) at launcher/launcher.rb:5

Nothing in those sources appeared to have changed. 
I still had a previous build on disk, and comparing them, the only significant difference I found was that the previous build had two versions of jruby-jars: 1.7.18 and 1.7.21 , and the new build had only 1.7.21.

I copied 1.7.18 into gem directory and startup now works. 
When archivesspace.sh builds classpath, and both gems are there, 1.7.18 is first on the list before 1.7.21, so it's presence must have been masking the issue. 

I don't see any problems running out of the development directory with build/run script.,and running scripts/jirb, I don't get any errors on `Dir.exists? nil ` 

Can anyone else reproduce this ? 

#### *update:*

I was able to reproduce this using rbenv to switch jruby versions outside of archivesspace dev. env. 
Using jruby-1.7.12, `Dir.exists? nil` returns `false`.
Using jruby-1.7.21 `Dir.exists? nil`  raises `TypeError: can't convert nil into String`

**Comment by mark-cooper** [comment]
:zap:
