### ISSUE TITLE
RDS problem with binary logging

### ISSUE THREAD

**Issue by mredar** [archivesspace/archivesspace#294]
If using an RDS database, the admin user does not have permission to do binary logging. In order to allow this, the RDS user must create a new parameter group with 

log_bin_trust_function_creators == 1

I've seen at least one other person with this issue (see: https://gist.github.com/aarome/b3474a0c519e8541e1a3) , might be good to document it.

**Comment by cfitz** [comment]
Hi, 

sure, pull request?

**Comment by mark-cooper** [comment]
@mredar any time for a pull request updating the docs for RDS users? Here seems reasonable:

https://github.com/archivesspace/archivesspace#set-up-your-mysql-database

Would be much appreciated. Thx.

**Comment by mredar** [comment]
Give me a few minutes, will have a pull request for you...

**Comment by mredar** [comment]
See pull request #461

**Comment by mark-cooper** [comment]
Resolved by: https://github.com/archivesspace/archivesspace/pull/461

:smile: :+1:
