### ISSUE TITLE
Was Archive Space properly containerised in Docker? 

### ISSUE THREAD

**Issue by rsx491** [archivesspace/archivesspace#2971]
I've pulled the image using "docker pull archivesspace/archivesspace". The container errors at the startup phase and gives the following: 

"[2023-03-23T19:10:13.261255 #64] ERROR -- : Thread-2010: Connection to backend failed (<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">"

Was the application ever containerized? I've found this thread but it was closed sometime ago; i.e. 2019; with the expectation that this would be done in the future? 

https://github.com/archivesspace/archivesspace/issues/1495

**Comment by brianzelip** [comment]
Have you tried following the [docs on setting up a local dev environment](https://archivesspace.github.io/tech-docs/development/dev.html)? I’ve found local docker deployment to work as expected.

**Comment by rsx491** [comment]
@brianzelip I appreciate the link. I dug around for a little while and didn't find anything in the time I had. The image didn't properly start so I abandoned it. I will give this a try!

**Comment by brianzelip** [comment]
Hi @rsx491 - we'll close this issue for now. Please open another issue if you still encounter errors after you leverage the tech docs linked above!
