### ISSUE TITLE
update ant jars?

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#303]
Can we get an update of build/ant jars ? 
ASpace ant version is 1.8.4 . Latest ant version is 1.9.6 . 

The reason is that I would like to submit patches to build.xml that use if/unless task attributes that we added in version 1.9.1 .  I have been using a custom build file that does a local build-zip that includes mysql connector, local config.rb additions and custom plugins. I have found it much easier to unpack the same customized zip file on test and production servers without worrying about missing a post-install step.  I need to update this procedure with recent changes to build.xml, and it seems like it would be better to add these as a conditional procedure to the standard build.xml target. 

One could then parameterize the build tasks with something like: 

```
<copy todir="target/archivesspace/plugins/local" verbose="true" if:true="${local_build}" >...
```

I haven't found any incompatibilities building with ant 1.9.6

**Comment by cfitz** [comment]
Looks good to me. Will probably accept it on next release.

**Comment by lmcglohon** [comment]
Closed with https://github.com/archivesspace/archivesspace/pull/310
