### ISSUE TITLE
Reorder mode always active when editing resource tree

### ISSUE THREAD

**Issue by h4l** [archivesspace/archivesspace#3108]
The resource edit page's tree view is in reorder mode without enabling reorder mode. This prevents highlighting text of rows.

## Expected Behavior

Should be able to select & copy text from resources without them being dragged to reorder.

## Current Behavior
Dragging over text in a resource in the resource edit page's tree results in the row being dragged as if reorder mode was enabled, despite reorder mode not being on.

## Possible Solution
Don't enable reorder dragging outside reorder mode.

## Steps to Reproduce (for bugs)

This screen recording demonstrates the issue:

https://github.com/archivesspace/archivesspace/assets/146503/1d3f67c0-a1be-4d54-b762-22804b385618

## Context

Users report not being able to highlight an copy text from the resource edit page.

## Your Environment

* Version used: 3.4.1 (reproduced on current sandbox)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Brave 1.61.120 Chromium: 120.0.6099.234
* Operating System and version (desktop or mobile): MacOS
* Link to your project: https://sandbox.archivesspace.org/staff / https://archivesearch.lib.cam.ac.uk/

**Comment by brianzelip** [comment]
@h4l Thanks for the bug report!

**Comment by h4l** [comment]
Thanks for fixing it so quickly with your PR @brianzelip, that's excellent!

**Comment by brianzelip** [comment]
Closed via #3111
