### ISSUE TITLE
Can't Unzip 1.4.1 On Windows 7

### ISSUE THREAD

**Issue by Blake-** [archivesspace/archivesspace#314]
![untitled](https://cloud.githubusercontent.com/assets/5229940/10467732/72823784-71c9-11e5-9680-c638138b49db.png)

Stock Win 7 NTFS dies when using the built in extractor with the attached error.

**Comment by cfitz** [comment]
Agggghhhhhhhhh!!!!!!!!!!!!!!

**Comment by cfitz** [comment]
So, yes, where are you trying to extract this. I think windows has a set limit of 260 character for the path, so maybe try unzipping it in C:\ ? 
Is this the only file where this is an issue? You can safely skip this one, since it's just a part of the Saxon-XSLT gem test suite.

**Comment by Blake-** [comment]
Dies when trying to unzip at the root of C, also tried Desktop. I did hit "skip" and it continued on through without any other errors. So it seems to be just that one file.

**Comment by cfitz** [comment]
Ok. hm...so, it would probably be a good idea to remove that file in the packaging process. 

F'ing java developers...

**Comment by cfitz** [comment]
added the build.xml to ignore spec in gems.
