### ISSUE TITLE
Error in Locations#show in v 1.4.1

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/archivesspace#322]
We are consistently seeing this error message when attempting to view a location record in 1.4.1 (sorry for the lack of formatting):

SyntaxError in Locations#show

Showing /opt/archivesspace-v1.4.1/archivesspace/data/tmp/jetty-0.0.0.0-8180-frontend.war-_-any-/webapp/WEB-INF/app/views/locations/show.html.erb where line #28 raised:

/opt/archivesspace-v1.4.1/archivesspace/data/tmp/jetty-0.0.0.0-8180-frontend.war-_-any-/webapp/WEB-INF/app/views/locations/show.html.erb:28: syntax error, unexpected kENSURE
          ensure
               ^
Extracted source (around line #28):

25:   </div>
26: </div>
Trace of template inclusion: app/views/locations/show.html.erb

Rails.root: /opt/archivesspace-v1.4.1/archivesspace/data/tmp/jetty-0.0.0.0-8180-frontend.war-_-any-/webapp/WEB-INF

**Comment by cfitz** [comment]
Hi,

Yep, we have a PR on deck for this: 
https://github.com/archivesspace/archivesspace/pull/313

i'm actually working on (another) quick fix release to address the issue of shipping with 2 version of jruby...will include this.

**Comment by trevorthornton** [comment]
Are either of the 1.4.2 RC releases recommended to address the syntax error
in Locations#show? Or a build from master? Trying to address the problem
for our staff using 1.4.1.

**Comment by cfitz** [comment]
Ugh, yeah it looks like this fix wasn't merged into the v1.4.1 release
somehow.

This is in the v1.4.2 branch that's going out soon...You can fix this by
putting this :
https://raw.githubusercontent.com/archivesspace/archivesspace/v1.4.2/frontend/app/views/locations/show.html.erb
in to  plugins/local/frontend/views/locations .

**Comment by cfitz** [comment]
Hi, this was merged into v1.4.2

**Comment by trevorthornton** [comment]
Thanks!

**Comment by cfitz** [comment]
No, thank you...sorry about the mess..
