### ISSUE TITLE
[ead import] - incorrect parsing of primary language of materials

### ISSUE THREAD

**Issue by walkerdb** [archivesspace/archivesspace#326]
The [current behavior](https://github.com/archivesspace/archivesspace/blob/master/backend/app/converters/ead_converter.rb#L177) of the ASpace EAD importer is to re-assign the primary language of materials in the resource every time it encounters a ```<language>``` tag, mapping it to the value of that tag's ```@langcode``` attribute.

Since this is an indiscriminate process, given a ```<langmaterial>``` tag of the following:

```xml
<langmaterial>
   The material is mostly in <language langcode="eng" encodinganalog="041">English</language>; 
   some correspondence is in <language langcode="arm" encodinganalog="041">Armenian;</language>; 
   select items are in <language langcode="ger" encodinganalog="041">German</language>.
</langmaterial>
```

by the end of the import the primary language of materials will have been assigned to "German", which is not correct.

---------------

We wrote up the following fix at the bentley, and would be happy to make a PR if it seems acceptable. The change assumes that the first language tag appearing in the langmaterial element is the primary language of materials for the ead, and preserves the old note-making behavior for langmaterial tags:

```ruby
with "langmaterial" do
  # assigning the primary language of materials for the ead
  # assumed to be the first language appearing in the langmaterial tag
  langmaterial = Nokogiri::XML::DocumentFragment.parse(inner_xml)
  langmaterial.children.each do |child|
    if child.name == 'language'
      set ancestor(:resource, :archival_object), :language, child.attr("langcode")
      break
    end
  end

  # write full tag content to a note, subbing out the language tags
  # copied verbatim from old langmaterial code
  content = inner_xml
  next if content =~ /\A<language langcode=\"[a-z]+\"\/>\Z/

  if content.match(/\A<language langcode=\"[a-z]+\"\s*>([^<]+)<\/language>\Z/)
    content = $1
  end

  make :note_singlepart, {
    :type => "langmaterial",
    :persistent_id => att('id'),
    :content => format_content( content.sub(/<head>.*?<\/head>/, '') )
  } do |note|
    set ancestor(:resource, :archival_object), :notes, note
  end
end
```

**Comment by quoideneuf** [comment]
This seems like a good change to me. I'm not sure any domain experts will chime in here (or anywhere) but I'd be happy to merge this if you post a PR.

**Comment by walkerdb** [comment]
Great! We'll make a PR shortly.

**Comment by walkerdb** [comment]
Fix was merged, so I'll close the issue. Thanks!
