### ISSUE TITLE
ArchivesSpace Security Vulnerability - Python Code Injection

### ISSUE THREAD

**Issue by TruongNguyen-USDA** [archivesspace/archivesspace#3261]
### Python Code Injection in ArchiveSpace

The ApplicationGatewayAffinityCORS cookie appears to be vulnerable to Python code injection attacks. The submitted value appears to be placed into a dynamically evaluated Python statement, within an unquoted context.

The payload eval(compile('for x in range(1):\n import time\n time.sleep(20)','a','single')) was submitted in the ApplicationGatewayAffinityCORS cookie. The application took 23422 milliseconds to respond to the request, compared with 1610 milliseconds for the original request, indicating that the injected Python code caused a time delay.

## Context
Tool: Burp Suite vulnerability scanner 
Business Impact: The USDA Cyber Security Team categorizes this issue as a Critical severity that must be mitigated per Government IT system guidelines

## Your Environment

* Version used: v3.5.0
* Environment name and version: Google Chrome v126.0.6478.127 (Official Build) (64-bit)
* Operating System and version: Azure VM Ubuntu v22.04 64-bit Server Edition
* Microsoft Azure Application Gateway

**Comment by TruongNguyen-USDA** [comment]
This issue has been mitigated by disable the AffinityCORS cookie at the Azure application gateway

**Comment by cdibella** [comment]
Preliminary investigation by our team indicates this either cannot be replicated or is not problematic for actual ArchivesSpace usage. Deleting these issues and continuing to correspond in private channels as needed according to our [security issues policy](https://github.com/archivesspace/archivesspace/security/policy).
