### ISSUE TITLE
ArchivesSpace Security Vulnerability - LDAP Injection

### ISSUE THREAD

**Issue by TruongNguyen-USDA** [archivesspace/archivesspace#3262]
### LDAP Injection in ArchiveSpace

The **q%5b%5d** parameter appears to be vulnerable to LDAP injection attacks.

The payloads )(objectClass= and )(!(objectClass=) were each submitted in the q%5b%5d parameter. These two requests resulted in different responses, indicating that the input may be being incorporated into a conjunctive LDAP query in an unsafe manner.

## Context
Tool: Burp Suite vulnerability scanner 
Business Impact: The USDA Cyber Security Team categorizes this issue as a Critical severity that must be mitigated per Government IT system guidelines

## Your Environment

* Version used: v3.5.0
* Environment name and version: Google Chrome v126.0.6478.127 (Official Build) (64-bit)
* Operating System and version: Azure VM Ubuntu v22.04 64-bit Server Edition
* Microsoft Azure Application Gateway

**Comment by TruongNguyen-USDA** [comment]
The Burp Suite scan report is attached 
[Burp_scan_archivesspace.nal.usda.gov_07-26-24.zip](https://github.com/user-attachments/files/16420707/Burp_scan_archivesspace.nal.usda.gov_07-26-24.zip)

**Comment by cdibella** [comment]
Preliminary investigation by our team indicates this either cannot be replicated or is not problematic for actual ArchivesSpace usage. Deleting these issues and continuing to correspond in private channels as needed according to our [security issues policy](https://github.com/archivesspace/archivesspace/security/policy).
