### ISSUE TITLE
ArchivesSpace Security Vulnerability - SQL Injection

### ISSUE THREAD

**Issue by TruongNguyen-USDA** [archivesspace/archivesspace#3263]
### SQL Injection in ArchiveSpace

The **op%5b%5d** parameter appears to be vulnerable to SQL injection attacks. The payload ')waitfor delay'0:0:20'-- was submitted in the op%5b%5d parameter. The application timed out when responding to the request, indicating that the injected SQL command caused a time delay.

## Context
Tool: Burp Suite vulnerability scanner 
Business Impact: The USDA Cyber Security Team categorizes this issue as a Critical severity that must be mitigated per Government IT system guidelines

## Your Environment

* Version used: v3.5.0
* Environment name and version: Google Chrome v126.0.6478.127 (Official Build) (64-bit)
* Operating System and version: Azure VM Ubuntu v22.04 64-bit Server Edition
* Microsoft Azure Application Gateway

**Comment by TruongNguyen-USDA** [comment]
This root cause of this issue might relate to #3262

**Comment by cdibella** [comment]
Preliminary investigation by our team indicates this either cannot be replicated or is not problematic for actual ArchivesSpace usage. Deleting these issues and continuing to correspond in private channels as needed according to our [security issues policy](https://github.com/archivesspace/archivesspace/security/policy).
