### ISSUE TITLE
ArchivesSpace Security Vulnerability - OS Command Injection

### ISSUE THREAD

**Issue by TruongNguyen-USDA** [archivesspace/archivesspace#3264]
### OS Command Injection in ArchiveSpace

The ApplicationGatewayAffinityCORS cookie appears to be vulnerable to OS command injection attacks. It is possible to use various shell metacharacters to inject arbitrary OS commands. The command output does not appear to be returned in the application's responses, however it is possible to inject time delay commands to verify the existence of the vulnerability.

The payload |ping -n 21 127.0.0.1||ping -c 21 127.0.0.1 #' |ping -n 21 127.0.0.1||ping -c 21 127.0.0.1 #" |ping -n 21 127.0.0.1 was submitted in the ApplicationGatewayAffinityCORS cookie. The application timed out when responding to the request, indicating that the injected command caused a time delay.

## Context
Tool: Burp Suite vulnerability scanner 
Business Impact: The USDA Cyber Security Team categorizes this issue as a Critical severity that must be mitigated per Government IT system guidelines

## Your Environment

* Version used: v3.5.0
* Environment name and version: Google Chrome v126.0.6478.127 (Official Build) (64-bit)
* Operating System and version: Azure VM Ubuntu v22.04 64-bit Server Edition
* Microsoft Azure Application Gateway

**Comment by TruongNguyen-USDA** [comment]
This issue has been mitigated by disable the AffinityCORS cookie at the Azure application gateway

**Comment by cdibella** [comment]
Preliminary investigation by our team indicates this either cannot be replicated or is not problematic for actual ArchivesSpace usage. Deleting these issues and continuing to correspond in private channels as needed according to our [security issues policy](https://github.com/archivesspace/archivesspace/security/policy).
