### ISSUE TITLE
ArchivesSpace Security Vulnerability -  Blind XPath Injection

### ISSUE THREAD

**Issue by TruongNguyen-USDA** [archivesspace/archivesspace#3268]
### Blind XPath Injection (differential analysis) in ArchivesSpace

- **Description**: XML Path Language (XPath) queries are used by web applications for selecting nodes from XML documents. Once selected, the value of these nodes can then be used by the application.

- **Potential Solution**: The most effective remediation against NoSQL injection attacks is to ensure that NoSQL API calls are not constructed via string concatenation that includes unsanitized data..

See also: http://projects.webappsec.org/w/page/13247005/XPath%20Injection

## Context
Tool: Tenable Web Application Scans
Business Impact: The USDA Cyber Security Team categorizes this issue as a Critical severity that must be mitigated per Government IT system guidelines

## Your Environment

* Version used: v3.5.0
* Environment name and version: Google Chrome v126.0.6478.127 (Official Build) (64-bit)
* Operating System and version: Azure VM Ubuntu v22.04 64-bit Server Edition
* Microsoft Azure Application Gateway

**Comment by cdibella** [comment]
Preliminary investigation by our team indicates this either cannot be replicated or is not problematic for actual ArchivesSpace usage. Deleting these issues and continuing to correspond in private channels as needed according to our [security issues policy](https://github.com/archivesspace/archivesspace/security/policy).
