### ISSUE TITLE
EAD Import - Problem with Escaped Characters

### ISSUE THREAD

**Issue by djpillen** [archivesspace/archivesspace#332]
It looks like there is an issue with certain escaped characters (& and <) getting dropped in at least \<unittitle\> and \<physdesc\> tags.

What we suspect is happening is that escaped characters are being unescaped by inner_xml before being passed along to Nokogiri::XML::DocumentFragment.parse so that, e.g., `&amp;` is passed along as just `&` and then cannot be parsed because it is not properly escaped. So something like...

```
<unittitle>A &amp; B</unittitle>
```
...becomes `A  B`. This has somewhat more severe consequences when the initially escaped ampersand is directly followed by additional characters, so that...

```
<unittitle>A &amp;B C D E</unittitle>
```
...becomes just `A`. `&amp;B C D E` is being unescaped to `&A B C D E` which the parser is completely dropping because it doesn't get the reference.

We would be happy to try to come up with a fix for this and submit a pull request, but we cannot figure out where this initial unescaping is happening. Our current workaround is to do `Nokogiri::XML::DocumentFragment.parse(inner_xml.gsub("&","&amp;").strip`, but there has to be a better way.

**Comment by walkerdb** [comment]
Just to give an example of where this is a particularly bad issue: if we have an ead unittitle with the text ```LS&amp;A, administrative records```, it gets processed into aspace as ```LS```, since it drops everything after the ampersand.
