### ISSUE TITLE
Bulk update of container profiles/locations has no constraints

### ISSUE THREAD

**Issue by alexduryee** [archivesspace/archivesspace#334]
I'm trying out version 1.4.3-dev17 (container management) and attempted to reassign top container profiles and locations to existing containers.  When creating top containers via the resource/archival object pages or the API, ASpace requires that the user choose from a set of existing values for profiles and locations.  However, when reassigning this metadata via the Bulk Operations menu on /top_containers, there are no constraints on possible values.  If the user inputs an invalid value for the container profile or location, the existing data is deleted, and nulls replace them.  In addition, the Browse and auto-complete functions appear inoperable.

Browser: Firefox 42, OSX (10.10.5)

**Comment by quoideneuf** [comment]
Thanks!
