### ISSUE TITLE
Top containers don't always point back to linked archival objects

### ISSUE THREAD

**Issue by alexduryee** [archivesspace/archivesspace#335]
Version: 1.4.3-dev17

In certain cases, the page for a top container will not list all linked archival objects under Linked Records.  For example, I have a resource where two objects are linked to the same container (id 644) - one linked only to that container, and one that is linked to multiple containers.  However, the object linked to multiple containers is not listed under /top_containers/644; only one object is listed.

**Comment by cfitz** [comment]
hi, 
is there an example in the sandbox or test that you can point back to?

**Comment by alexduryee** [comment]
The sandbox isn't using the container module yet - is there another instance I could use?

Looking deeper into this, the issue seems to be that the index of [[top_container_uri_u_sstr]] isn't fully generating for us.  Querying for the [[top_container_uri_u_sstr]] via "Go To Search Results" isn't returning a full list of objects associated with a container - in most cases, it isn't returning any objects at all.  This issue is manifesting on two different instances using two different test collections (both imported into ASpace via the API), so it doesn't seem to be edge-case data jamming the index.

**Comment by alexduryee** [comment]
Tested again on a fresh database; same issue.  Forcing a reindex (via deleting `indexer_state`) resolves the issue.  I didn't see any indexer errors when importing objects and/or linking containers to objects.

**Comment by mark-cooper** [comment]
Looks like it's ok to close this one. The upgrade docs recommend deleting the solr index in preparation for the upgrade and a full reindex is triggered post container conversion.
