### ISSUE TITLE
build/run bootstrap fails : No value set for ... migrate_to_container_management 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#353]
I assume there is no default value set so that people are warned on upgrade and know what they are doing. I know how to fix this locally, but I think it's likely to be confusing to people trying to set up out-of-the-box. Is this behavior intentional ? 

bundler:
     [echo] Fetching gems for ../backend/Gemfile
     [java] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=196m; support was removed in 8.0
     [java] 
     [java] [!] There was an error parsing `Gemfile`: No value set for config parameter: migrate_to_container_management. Bundler cannot continue.
     [java] 
     [java]  #  from /projects/Archivespace/dcs-archivesspace/backend/Gemfile:1
     [java]  #  -------------------------------------------
     [java]  >  source "http://rubygems.org"
     [java]  #  
     [java]  #  -------------------------------------------

BUILD FAILED

Note: also had to create an empty launcher/tomcat directory to build release. Otherwise, zip build fails.

**Comment by cfitz** [comment]
Hi, 
yes actually replacing this. You can temporary fix this by setting 
AppConfig[:migrate_to_container_management] = true in config.rb.

**Comment by sdm7g** [comment]
I set it to false as the second  thing I was trying to do was db:nuke on development.

**Comment by sdm7g** [comment]
https://github.com/archivesspace/archivesspace/pull/355
