### ISSUE TITLE
API - bug in auth id conflict error message when posting agents

### ISSUE THREAD

**Issue by walkerdb** [archivesspace/archivesspace#360]
If I successfully post an agent json, the API will spit back json with a "Created" status, and an ASpace URI for the new resource. Let's say in this case it was 10.

If I try to post a new agent json with a different primary name but the _same authority_id_, I will receive the following message:

``` json
{"error": {"conflicting_record": ["/agents/corporate_entities/11"],
           "names/0/authority_id": ["Authority ID must be unique"]}}
```

The fact that this is an error is good - I assume we don't want to have multiple agent items pointing to the same UID. However the given conflicting record URI is wrong. Instead of returning the URI of the actual conflicting record (10 in this case), it instead returns the next unassigned URI in the specific agent category. Navigating to the given URI gives a "resource not found" error.

Posting the following two json files in order to the `/agents/people` API endpoint should replicate the error:

``` json
{"names": 
    [{"primary_name": "Superman", 
      "authority_id": "http://id.loc.gov/authorities/names/n2015060724.html", 
      "source": "lcnaf", 
      "name_order": "inverted", 
      "sort_name_auto_generate": true}], 
    "publish": true
}
```

``` json
{"names": 
    [{"primary_name": "Kent", 
      "rest_of_name": "Clark", 
      "authority_id": "http://id.loc.gov/authorities/names/n2015060724.html", 
      "sort_name_auto_generate": true, 
      "source": "lcnaf", 
      "name_order": "inverted"}], 
    "publish": true
}

```

**Comment by cfitz** [comment]
Hi,

Hm. Couldn't replicate this:

 $ cat >> 1.json
{"names": 
    [{"primary_name": "Superman", 
      "authority_id": "http://id.loc.gov/authorities/names/n2015060724.html", 
      "source": "lcnaf", 
      "name_order": "inverted", 
      "sort_name_auto_generate": true}], 
    "publish": true
}
^C

$ cat >> 2.json
{"names": 
    [{"primary_name": "Kent", 
      "rest_of_name": "Clark", 
      "authority_id": "http://id.loc.gov/authorities/names/n2015060724.html", 
      "sort_name_auto_generate": true, 
      "source": "lcnaf", 
      "name_order": "inverted"}], 
    "publish": true
}
^C

$ curl -H "X-ArchivesSpace-Session: $SESSION"  -d @1.json http://localhost:4567/agents/people
{"status":"Created","id":148,"lock_version":0,"stale":true,"uri":"/agents/people/148","warnings":[]}

$ curl -H "X-ArchivesSpace-Session: $SESSION"  -d @2.json http://localhost:4567/agents/people
{"error":{"names":["Agent must be unique"],"conflicting_record":["/agents/people/148"]}}


$ curl -H "X-ArchivesSpace-Session: $SESSION"   http://localhost:4567/agents/people/148
{"lock_version":0,"publish":true,"created_by":"admin","last_modified_by":"admin","create_time":"2016-03-17T09:40:33Z","system_mtime":"2016-03-17T09:40:33Z","user_mtime":"2016-03-17T09:40:33Z","jsonmodel_type":"agent_person","agent_contacts":[],"linked_agent_roles":[],"external_documents":[],"rights_statements":[],"notes":[],"dates_of_existence":[],"names":[{"lock_version":0,"primary_name":"Superman","sort_name":"Superman","sort_name_auto_generate":true,"created_by":"admin","last_modified_by":"admin","create_time":"2016-03-17T09:40:33Z","system_mtime":"2016-03-17T09:40:33Z","user_mtime":"2016-03-17T09:40:33Z","authorized":true,"is_display_name":true,"source":"lcnaf","name_order":"inverted","jsonmodel_type":"name_person","use_dates":[],"authority_id":"http://id.loc.gov/authorities/names/n2015060724.html"}],"related_agents":[],"uri":"/agents/people/148","agent_type":"agent_person","display_name":{"lock_version":0,"primary_name":"Superman","sort_name":"Superman","sort_name_auto_generate":true,"created_by":"admin","last_modified_by":"admin","create_time":"2016-03-17T09:40:33Z","system_mtime":"2016-03-17T09:40:33Z","user_mtime":"2016-03-17T09:40:33Z","authorized":true,"is_display_name":true,"source":"lcnaf","name_order":"inverted","jsonmodel_type":"name_person","use_dates":[],"authority_id":"http://id.loc.gov/authorities/names/n2015060724.html"},"title":"Superman","is_linked_to_published_record":false}

Did you run into this when creating multiple agents in one go? It might behave different when it's in a transaction.

**Comment by lmcglohon** [comment]
Closing this issue because it's old and there was no response to a previous request for information (in 2016) but can reopen it if further information is provided that indicates it's still an issue.

**Comment by AustinTSchaffer** [comment]
Hello,

I am also seeing an issue where attempting to post a new agent record that contains a previously used Authority ID is causing Archives Space to return a reference to a URI that does not exist yet.

If you need a little background, I'm trying to migrate some data to Archives Space that contains only Accessions, Agents, and Events, where a lot of agent records are repeated. Currently, the program posts up to 2 agents, then exactly 1 accession record, then up to 5 events, all being related through the Accession record.

Sometimes when posting an agent that is duplicated, I get the following *"Agent must be unique"* error. I'm pretty much ignoring these errors at this point, since the returned URI is valid and doesn't cause any issues when linking to the Accession and Event records. 

```json
{"error":{"names":["Agent must be unique"],"conflicting_record":["/agents/x/y"]}}
```

Others times, I get the following *"Authority ID must be unique"* error. When I try to use the returned URI, the Accession record fails to post, which also causes the Event records to fail to post. 

```json
{"error":{"names/0/authority_id":["Authority ID must be unique"],"conflicting_record":["/agents/x/y"]}}
```

If there anything I could provide to help diagnose this issue, please let me know. I am running Archives Space on a personal VM, so I have access to any server logs that you may want.

For now, I have included sequential server responses up to the point where posting an agent record returned one of the responses. In this example, there were no actions happening in parallel, so the program was not moving on to post the next group of (2 Agents, 1 Accession, 5 Events) until the previous had completed. 

```json
{"status":"Created","id":33,"lock_version":0,"stale":true,"uri":"/agents/people/33","warnings":[]}
{"status":"Created","id":36,"lock_version":0,"stale":true,"uri":"/repositories/2/accessions/36","warnings":[]}
{"status":"Created","id":102,"lock_version":0,"stale":null,"uri":"/repositories/2/events/102","warnings":[]}
{"status":"Created","id":103,"lock_version":0,"stale":null,"uri":"/repositories/2/events/103","warnings":[]}

{"status":"Created","id":34,"lock_version":0,"stale":true,"uri":"/agents/people/34","warnings":[]}
{"status":"Created","id":37,"lock_version":0,"stale":true,"uri":"/repositories/2/accessions/37","warnings":[]}
{"status":"Created","id":105,"lock_version":0,"stale":null,"uri":"/repositories/2/events/105","warnings":[]}
{"status":"Created","id":106,"lock_version":0,"stale":null,"uri":"/repositories/2/events/106","warnings":[]}
{"status":"Created","id":107,"lock_version":0,"stale":null,"uri":"/repositories/2/events/107","warnings":[]}

{"status":"Created","id":35,"lock_version":0,"stale":true,"uri":"/agents/people/35","warnings":[]}
{"status":"Created","id":38,"lock_version":0,"stale":true,"uri":"/repositories/2/accessions/38","warnings":[]}
{"status":"Created","id":109,"lock_version":0,"stale":null,"uri":"/repositories/2/events/109","warnings":[]}
{"status":"Created","id":110,"lock_version":0,"stale":null,"uri":"/repositories/2/events/110","warnings":[]}

{"status":"Created","id":36,"lock_version":0,"stale":true,"uri":"/agents/people/36","warnings":[]}
{"status":"Created","id":39,"lock_version":0,"stale":true,"uri":"/repositories/2/accessions/39","warnings":[]}
{"status":"Created","id":112,"lock_version":0,"stale":null,"uri":"/repositories/2/events/112","warnings":[]}

{"status":"Created","id":37,"lock_version":0,"stale":true,"uri":"/agents/people/37","warnings":[]}
{"status":"Created","id":40,"lock_version":0,"stale":true,"uri":"/repositories/2/accessions/40","warnings":[]}
{"status":"Created","id":114,"lock_version":0,"stale":null,"uri":"/repositories/2/events/114","warnings":[]}

{"error":{"names/0/authority_id":["Authority ID must be unique"],"conflicting_record":["/agents/people/38"]}}
{"error":"Can't relate to non-existent record: /agents/people/38"}
{"error":{"linked_records/0/ref":["Property is required but was missing"]},"warning":null,"invalid_object":"#<JSONModel(:event) {\"event_type\"=>\"processed\", \"outcome\"=>\"pass\", \"date\"=>{\"date_type\"=>\"single\", \"label\"=>\"creation\", \"expression\"=>\"1997-05\", \"begin\"=>\"1997-05-01\", \"jsonmodel_type\"=>\"date\"}, \"linked_agents\"=>[{\"role\"=>\"recipient\", \"ref\"=>\"/agents/people/1\"}], \"linked_records\"=>[{\"role\"=>\"source\"}], \"jsonmodel_type\"=>\"event\", \"external_ids\"=>[], \"external_documents\"=>[]}>"}
```

Best,
Austin

**Comment by AustinTSchaffer** [comment]
I checked back at my data for this test, and have attached the 2 agent records that came into conflict. The first of the 2 agent records was successfully stored as `/agents/people/34`. The second caused the error.

agent_role | agent_type | agent_contact_address_1 | agent_contact_address_2 | agent_contact_city | agent_contact_country | agent_contact_region | agent_contact_post_code | agent_contact_telephone | agent_name_authority_id | agent_name_dates | agent_name_fuller_form | agent_name_primary_name | agent_name_qualifier | agent_name_rest_of_name | agent_name_rules | agent_name_source
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
source | agent_person | 323 South 11th Place |   | Rogers |   | AR | 72756 |   | no2002010971 | 1914-2013 |   | Reagan |   | Agnes Lytton | DACS | NACO
source | agent_person |   |   | Rogers |   | AR |   |   | no2002010971 | 1914-2013 |   | Reagan |   | Agnes Lytton | DACS | NACO


In total, this issue occurred 103 times while posting my data set.

**Comment by lmcglohon** [comment]
https://archivesspace.atlassian.net/browse/ANW-292
