### ISSUE TITLE
Updating robots.txt?

### ISSUE THREAD

**Issue by kardeiz** [archivesspace/archivesspace#368]
A few days ago, I noticed our log files had gotten huge and realized that some web crawler was sending dozens of requests per second to our AS public site (and had been doing so for more than a week). These weren't malicious requests--they were all to `search` and `advanced_search` pages with different query parameters.

It does not appear that there is an easy way (at least using the standard release rather than the full source) to update the `robots.txt` file using any built-in mechanism. I ended up just doing `jar -uf wars/public.war robots.txt` with the file I wanted to use.

A few questions/comments:

1. It might be a good idea to make the `robots.txt` file for the `public` site disallow `/search` and `/advanced_search` by default (having these pages indexed by Google et al. probably isn't necessary or a good idea anyway).
2. Would it be a good idea to have a tool to modify `robots.txt` and other "static" files?
3. On a related note, do most AS users use the standard releases or clone the repo and build their own releases?

**Comment by cfitz** [comment]
Hi,

Yeah, I think the jar method is ok or using a reverse proxy and configuring the robots.txt there is probably the way to go. 

A tool to modify them would be great too ( pull requests welcome ).

Most people use a standard release....
