### ISSUE TITLE
API - passing json parameters to search endpoint broken?

### ISSUE THREAD

**Issue by walkerdb** [archivesspace/archivesspace#394]
This may just be me not understanding the api.

According to the documentation, the search endpoint can take a number of parameters, among them "type", which must be an array of strings, and "filter_term", which must be an array of json strings.

If I make a search with the following json:

``` json
{
    "type": ["agent_person", "agent_family", "agent_corporate_entity"],
    "filter_term": ["{\"authority_id\": auth_id}"]
}
```

the response is an error suggesting that the types are incorrect:

``` json
{
    "error": {
        "filter_term": ["Wanted type [String] but got '{\"authority_id\": auth_id}'"],
        "type": ["Wanted type [String] but got 'agent_corporate_entity'"]
    }
}
```

This is confusing for a few reasons: the first being that the original terms are in the required format (or at least, I think they are), and the second being that the error is reporting that the incorrect values are not the arrays themselves but rather the last element in each array.
## 

This search can be performed from a browser with `search?page=1&type=agent_person&type=agent_family&type=agent_corporate_entity&filter_term={"authority_id": "auth_id"}`. However, trying the same from a command line results in the above error.

Am I just interpreting the requirements incorrectly? Or is this a bug somewhere?
## 

[edit]:
Search parameters that require single strings (eg the "q" parameter) work just fine -- whatever is going wrong may apply only to array parameters.

**Comment by quoideneuf** [comment]
@walkerdb - in your first snippet of json, shouldn't 'auth_id' be enclosed in escaped quotes, just like 'authority_id'?

**Comment by lmcglohon** [comment]
@walkerdb Closing this - if you are still having trouble, can reopen this.
