### ISSUE TITLE
Unitids are having their content rewritten... again.

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#409]
Commit f4c5091 has reintroduced the behavior referenced in #328 which was fixed in #338.  

I am omitting the problem description because, well, it's exactly the behavior from #328. 

Is this deliberate, or accidental? If deliberate, what's the rationale, and what's an alternate solution that doesn't corrupt content on ingest?

**Comment by cfitz** [comment]
Hi,

Hm, that commit you're referencing is from June 18, 2013. Looking at the[ repo's master](https://github.com/archivesspace/archivesspace/blob/master/backend/app/converters/ead_converter.rb#L136) that gsub is not present .

I think you need to pull upstream for your fork?

**Comment by pobocks** [comment]
I think you're write :-( I'm very, very sorry - Firefox "helpfully" replaced more of a URL than I thought.
