### ISSUE TITLE
Nested forms (invalid HTML) on Resource Edit page causes display issue in IE

### ISSUE THREAD

**Issue by kardeiz** [archivesspace/archivesspace#41]
The `frontend/app/views/shared/_merge_dropdown.html.erb` partial creates a nested form on the Resource Edit page (e.g., `/resources/3/edit`), which is invalid HTML. Firefox and Chrome ignore the tag entirely; IE (9) ignores the opening tag, but preserves the closing tag, which triggers the closing of the primary "resource_form", which causes the "record-toolbar" to break and the sidebar to obscure form elements on scroll.

It seems like the nested form tag could be removed entirely: the "submit" URL is added to the button separately with the "button_confirm_action" helper, and there appears to be JS handling in place to ensure the appropriate inputs are submitted on clicking the "Merge" button.

**Comment by cfitz** [comment]
closing as part of housekeeping.
