### ISSUE TITLE
XSS possible when editing agent records

### ISSUE THREAD

**Issue by rsdoiel** [archivesspace/archivesspace#410]
There appears to be an XSS vulnerability when editing agents in v1.4.2. Most editable fields allow JavaScript to be  pasted in unaltered. E.g. pasing

';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//"; alert(String.fromCharCode(88,83,83))//";alert(String.fromCharCode(88,83,83))//-- ></SCRIPT>">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT> ';alert(String.fromChar

In a field yields undesirable JavaScript execution in the browser when the page is updated.  Not allowing script element in the input would solve the problem.

**Comment by cfitz** [comment]
Cool. Can you submit a PR?

**Comment by rsdoiel** [comment]
Sorry I don't have code to fix it. I am a total noob when it comes to Ruby/Rails and I am pretty sure it is in that code (as opposed to the Java) that you'd want to implement a fix.

**Comment by lmcglohon** [comment]
Fixed with #719
