### ISSUE TITLE
Generated links for aspace-public-formats are wrong

### ISSUE THREAD

**Issue by kardeiz** [archivesspace/archivesspace#411]
See [_navlist.html.erb#L29](https://github.com/archivesspace/archivesspace/blob/master/plugins/aspace-public-formats/public/views/records/_navlist.html.erb#L29).

`/format/<format>` is simply appended to `request.original_url`. If the page URL has a query string, this link will not work. Even worse, the link will return to the same page with `/format/<format>` at the end of the query string, and the next link will end with `/format/<format>/format/<format>`, which could continue ad infinitem. We just had a web crawler stuck in this cycle.

It would be way better to use Rails URL helpers to generate this link, but the quickest fix that might work might be to change `request.original_url` to `request.path`.

**Comment by cfitz** [comment]
Cool. Can you submit a PR?

**Comment by mark-cooper** [comment]
Resolved by: https://github.com/archivesspace/archivesspace/pull/415
