### ISSUE TITLE
How to use session IDs with API after login

### ISSUE THREAD

**Issue by sckott** [archivesspace/archivesspace#424]
I see that login https://github.com/archivesspace/archivesspace/blob/4c26d82b1b0e343b7e1aea86a11913dcf6ff5b6f/docs/slate/source/index.md#authentication gives a session ID. and the docs say to use that in subsequent API requests. But the docs don't say how you want that done. Can you clarify how you want session IDs passed in http requests?

**Comment by cfitz** [comment]
Hi, 

Have a look at http://archivesspace.github.io/archivesspace/api/#authentication
( that had the correctly rendered version of that file you're looking at in git ). 
The example export SESSION=THESESSIONID
Then you add a header of "X-ArchivesSpace-Session:" with the session id.

Does that make sense?

**Comment by cfitz** [comment]
Ugh actually just noticed the slate is rending that incorrectly as "export SESSION-" instead of "export SESSION=". will correct that.

**Comment by sckott** [comment]
Thanks very much, will try

**Comment by sckott** [comment]
thanks, that works

**Comment by cfitz** [comment]
:+1:
