### ISSUE TITLE
require_relative causes chaos with plugins

### ISSUE THREAD

**Issue by alexduryee** [archivesspace/archivesspace#426]
The latest release candidates use `require_relative` to pull methods into models (e.g. `backend/app/exporters/serializers/ead.rb` points to `backend/app/exporters/lib/serialize_extra_container_values.rb`).  When writing plugins, this creates dependency issues - lots of files need to be pulled into the plugin, and `require_relative` paths need to be reset.

This is particularly bad when adding tests to a plugin; the `require_relative` calls in `spec_helper.rb` create a chain of dozens of files that need to be packaged with a plugin.

**Comment by lmcglohon** [comment]
@alexduryee Can you provide an example for this?

**Comment by lmcglohon** [comment]
@alexduryee This is really old. Does the problem still exist in the newer releases? Thanks, Laney

**Comment by alexduryee** [comment]
Sorry for the long delay - I'm fine closing + killing this.  I was able to work around it during development, so it hasn't been an issue.
