### ISSUE TITLE
Running archivesspace in Tomcat with separate CATALINA_HOME and CATALINA_BASE

### ISSUE THREAD

**Issue by ccc2lu** [archivesspace/archivesspace#44]
I'm trying to install ArchivesSpace on a Debian Linux server with Tomcat installed by the apt package manager.  This creates separate CATALINA_HOME (/usr/share/tomcat6) and CATALINA_BASE (/var/lib/tomcat6) directories.  The existing configure_tomcat.sh script refuses to run with this configuration when given either of the above directories as its argument.  It exits stating that the directory "doesn't look like a Tomcat directory".  

I tried downloading a version of Tomcat outside the package manager, unpacking it to a folder in my home directory, running configure_tomcat.sh to copy the libraries and configuration for ArchivesSpace to that folder, and then manually copying the changes to the package manager maintained Tomcat installation, but I must have missed something.  I'm getting exceptions from each of the archivesspace webapps when I try to start Tomcat.  The first says 
org.jruby.exceptions.RaiseException: (ArgumentError) wrong number of arguments (1 for 2)
        at RUBY.capture(file:/libwebdata/tomcat6/catalina_home/lib/jruby-rack-1.1.12.jar!/jruby/rack/capture.rb:48) ...

The next says 
org.jruby.rack.RackInitializationException: no such file to load -- bundler/set\
up
        from org/jruby/RubyKernel.java:1082:in `require'
        from jar:file:/libwebdata/tomcat6/catalina_home/lib/jruby-stdlib-complete-1.7.6.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_requ\ire.rb:55:in `require'
        from /var/lib/tomcat6/webapps/public/WEB-INF/config/boot.rb:10:in `(root)' ...

That sequence repeats several times.  Any thoughts what's causing this?  Did I miss copying a library to CATALINA_HOME/lib?

**Comment by cfitz** [comment]
Closing this as housekeeping.
