### ISSUE TITLE
Issues with ArchivesSpace Install on Microsoft Server

### ISSUE THREAD

**Issue by erineallsop** [archivesspace/archivesspace#494]
Hello, I have been following the YouTube video by Ben Finberg, Director of IT and Operations at the Georgia O'Keeffe Museum on how to properly install ArchivesSpace on a Microsoft 2012 server against a MySQL database. Towards the end of his video is where I run into some trouble with running the script for the setup-database.bat command as well as the service.bat command in launcher. This is the message I get: 

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

U:\>c:

C:\>cd archivesspace\

C:\archivesspace>cd scripts\

C:\archivesspace\scripts>dir
 Volume in drive C has no label.
 Volume Serial Number is 30D8-550F

 Directory of C:\archivesspace\scripts

07/14/2016  11:34 AM    <DIR>          .
07/14/2016  11:34 AM    <DIR>          ..
07/14/2016  11:34 AM               323 backup.bat
07/14/2016  11:34 AM               371 backup.sh
07/14/2016  11:34 AM               282 configure-tomcat.bat
07/14/2016  11:34 AM               374 configure-tomcat.sh
07/14/2016  11:34 AM               296 ead_export.bat
07/14/2016  11:34 AM               356 ead_export.sh
07/14/2016  11:34 AM               217 find-base.sh
07/14/2016  11:34 AM               377 initialize-plugin.bat
07/14/2016  11:34 AM               708 initialize-plugin.sh
07/14/2016  11:34 AM               301 password-reset.bat
07/14/2016  11:34 AM               359 password-reset.sh
10/27/2015  05:11 PM    <DIR>          rb
07/14/2016  11:34 AM               274 setup-database.bat
07/14/2016  11:34 AM               328 setup-database.sh
              13 File(s)          4,566 bytes
               3 Dir(s)  37,058,719,744 bytes free

C:\archivesspace\scripts>setup-database.bat
io/console not supported; tty will not be manipulated
Loading ArchivesSpace configuration file from path: C:/archivesspace/config/conf
ig.rb
NoMethodError: undefined method `|' for #<String:0x639aba11>
            (root) at C:/archivesspace/config/config.rb:35
              load at org/jruby/RubyKernel.java:1059
            (root) at file:/C:/archivesspace/lib/common.jar!/config/config-distr
ibution.rb:1
  load_user_config at file:/C:/archivesspace/lib/common.jar!/config/config-distr
ibution.rb:102
            reload at file:/C:/archivesspace/lib/common.jar!/config/config-distr
ibution.rb:130
              init at C:/archivesspace/launcher/launcher_init.rb:10
           require at org/jruby/RubyKernel.java:1040
            (root) at C:/archivesspace/launcher/launcher_init.rb:23
            (root) at /C:/archivesspace/gems/gems/jruby-jars-1.7.21/lib/jruby-st
dlib-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_re
quire.rb:1
            (root) at ..\scripts\rb\migrate_db.rb:6

C:\archivesspace\scripts>cd ..

C:\archivesspace>cd launcher

C:\archivesspace\launcher>dir
 Volume in drive C has no label.
 Volume Serial Number is 30D8-550F

 Directory of C:\archivesspace\launcher

07/14/2016  11:33 AM    <DIR>          .
07/14/2016  11:33 AM    <DIR>          ..
07/14/2016  11:33 AM               776 archivesspace.bat
07/14/2016  11:33 AM             4,470 archivesspace.sh
07/14/2016  11:33 AM    <DIR>          backup
07/14/2016  11:33 AM    <DIR>          ead_export
07/14/2016  11:33 AM             8,339 launcher.rb
07/14/2016  11:33 AM               658 launcher_init.rb
07/14/2016  11:33 AM    <DIR>          lib
07/14/2016  11:33 AM    <DIR>          password_reset
07/14/2016  11:33 AM    <DIR>          plugin_gems
07/14/2016  11:33 AM             1,083 request_handler.rb
07/14/2016  11:33 AM    <DIR>          scripts
07/14/2016  11:33 AM             3,980 service.bat
07/14/2016  11:33 AM    <DIR>          tomcat
               6 File(s)         19,306 bytes
               9 Dir(s)  37,058,072,576 bytes free

C:\archivesspace\launcher>service.bat
This program will attempt to set up a procrun windows service
for ArchivesSpace.
ECHO is off.
Prerequisites:
1) Download procrun
 ( http://commons.apache.org/proper/commons-daemon/procrun.html )
and put the execuitables ( prunsrv.exe and prunmgr.exe )
into your archivesspace directory.
ECHO is off.
ECHO is off.
2) You must have JAVA_HOME defined as a global variable, pointing
to your systems java home ( e.g. C:\Program Files\Java\jre7 ).
To find this, you can use "where java" command. The home will be the
directory above "bin\java.exe".
ECHO is off.
ECHO is off.
Press any key to continue . . .
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
        1 file(s) copied.
        1 file(s) copied.
ECHO is off.
ECHO is off.
ECHO is off.
The service has been installed. There is now an
ArchivesSpaceService execucitable and ArchivesSpaceServicew monitor.
ArchivesSpaceService Options:
ArchivesSpaceService //TS// Run the service as a console app
ArchivesSpaceService //RS// Run the service
ArchivesSpaceService //SS// Stop the service
ArchivesSpaceService //US// Update service pamaters
ArchivesSpaceSerivce //DS// Delete service
ECHO is off.
ECHO is off.
ArchivesSpaceServicew Options:
ArchivesSpaceServicew //ES// Start GUI service editor
ArchivesSpaceServicew //MS// Monitor service (puts an icon in system tray)
ECHO is off.
Enjoy.
Done

I then proceeded to start the ArchivesSpaceServicew application but it would stop automatically.

I am a complete novice on how to install a server and a database. Ben's video is extremely helpful, but I just cannot pinpoint exactly where I went wrong because it seems to me like I have made multiple errors. If anyone can provide me with information on how I can resolve this/these issue(s), I'm greatly appreciative. Here is the link for Ben's video: https://www.youtube.com/watch?v=s8sDok-eMFo, I'm referring to his steps between 11:12-13:51. 

Thank you,
Erin

**Comment by mark-cooper** [comment]
Hi Erin,

Looking at this part `NoMethodError: undefined method `|' for #String:0x639aba11
(root) at C:/archivesspace/config/config.rb:35`.

It looks like you've updated the line in the default config.rb file `#AppConfig[:db_url] = proc { AppConfig.demo_db_url }`. What do you have there?

Mark

**Comment by mark-cooper** [comment]
Hi Erin,

Can I assume you worked through your issue? I'll close this on Friday if there's no further input.

**Comment by erineallsop** [comment]
Hi Mark,

So sorry for my delayed response. Yes, my issue has been resolved. We are now on a Linux server which has been much easier to install and navigate. Sorry for any inconvenience the open ticket may have caused you.

Have a great evening,
Erin

**Comment by mark-cooper** [comment]
No problem at all Erin! Glad you have been able to move on with your implementation =)
