### ISSUE TITLE
REST API Documentation curl examples and output missing, model descriptions missing

### ISSUE THREAD

**Issue by rsdoiel** [archivesspace/archivesspace#498]
Good Morning,

I am working on a workshop presentation for the Members' forum this Aug 2nd. and as I was updating my links to the REST API docs (http://archivesspace.github.io/archivesspace/api/) I notice that most of the *curl* examples and outputs have been removed. Also noticed the section that described the models is missing.

If the documentation website's repo was visible I could help update the examples from the v1.4.2 to v1.5.0 release but I can't seem to find archivesspace.github.io (assume it is private).

All the best,

Robert

**Comment by cfitz** [comment]
Hi, yeah I realized my documentation I left behind to do the documentation build was lacking. i updated it to do the API / Slate / Curl examples a little better now.

**Comment by rsdoiel** [comment]
Thank you so much. It is amazing how those simple examples made such a difference when I have talked with others about how to use the APIs or debug problems in the clients I've written.

All the best,

Robert

**Comment by mark-cooper** [comment]
@rsdoiel just looking into some things related to: https://github.com/archivesspace/archivesspace/pull/499

with @cfitz 

Hoping to have an update soon.

**Comment by cfitz** [comment]
Yep. just added some stuff to get rid of those annoying YARD errors. Also updated a couple of the documents. I think should be good to go..

**Comment by rsdoiel** [comment]
Thank you both for the help. This will make it much easier to teach the REST API next week. All the best!!!!
