### ISSUE TITLE
Path too long

### ISSUE THREAD

**Issue by smoore4moma** [archivesspace/archivesspace#506]
I got a "Path too long" error on Windows 2008 R2 when extracting v1.5.0.

Was able to resolve by copying to a very short starting point (C:\AS) and then renaming the extracted files as something short as well (C:\AS\v1.5.0).  Maximum path length on Windows is 255 characters, although that is supposed to change with Windows Server 2016.

![img](https://cloud.githubusercontent.com/assets/4989910/17297121/556956ec-57d2-11e6-8864-9d14a4e3dffc.jpg)

**Comment by mark-cooper** [comment]
Well, that's unfortunate. I'm personally biased towards considering this a documentation issue as it's not a problem with ArchivesSpace, it's more of a Windows idiosyncrasy.

So I think adding a section to the README about how to workaround this is sufficient (if not ideal), until hopefully WS 2016 resolves it for Windows users.

If anyone disagrees with that and wants to propose something different the comments are wide open =)

(aside: 1.5.1 has been released which resolves a couple of issues with 1.5.0)

**Comment by smoore4moma** [comment]
I think we can all agree that the path limit is ridiculous.  I will close the comment after a 2-3 days, and then Google will pick up on the search terms "path too long archivesspace".  It will lead here of course.

**Comment by smoore4moma** [comment]
And it helps not to name folders and files as ..\archivesspace\reports\Accessions\AccessionsSubjectsNamesClassificationsListReport\AccessionsSubjectsNamesClassificationsListReport.jrxml

That's a seriously long filename.  But still agree that it shouldn't matter.

**Comment by minorscience** [comment]
Possible fix. 

https://support.microsoft.com/en-us/kb/2891362

**Comment by cfitz** [comment]
Ugghhhh!!! It's back!

Yeah, sorry...there's a weird file in the Saxon gem called "saxon-xslt-0.7.2-java/spec/fixtures/cassettes/Saxon_SourceHelper/returning_a_StreamSource/StreamSource_systemId/for_inputs_where_we_can_infer_the_path_or_URI/is_set_to_an_open-uri_d_URI_s_URI.yml" 

I had [something to block that out, ](https://github.com/archivesspace/archivesspace/blob/master/build/build.xml#L617) but the gem version changed...

You can skip this file. It's just part of the gem's test suite...

I'll try and put something in the build to skip this...

**Comment by smoore4moma** [comment]
Multiple workarounds available.  Closing issue.
