### ISSUE TITLE
Font 'Arial' is not available to the JVM

### ISSUE THREAD

**Issue by kardeiz** [archivesspace/archivesspace#523]
When running a `digitalobjectlisttablereport` on AS `v1.5.1`, I get the following error:

```
 Font 'Arial' is not available to the JVM. See the Javadoc for more details.
```

Considering `Arial` is not commonly installed on Linux machines (it can be installed, but not from an official repo, at least on CentOS), it might be better to use a more generic sans-serif font in the Jasper reports.

**Comment by mark-cooper** [comment]
Would be nice to have something more natively cross-platform for sure. My understanding is that the Jasper Reports implementation is undergoing review and may be replaced entirely so I think the status quo may prevail for a while longer ...

For anyone running into this the standard workaround is to install the mscorefonts package:

https://www.google.com/search?q=msstfonts+installer#q=ubuntu+ttf-mscorefonts-installer (ubuntu bias =)

**Comment by lmcglohon** [comment]
@mark-cooper Now that Jasper has been removed (in v2.0.0), is this still an issue?

**Comment by lmcglohon** [comment]
I believe that the removal of Jasper reports has made this a non-issue so I am closing this.
