### ISSUE TITLE
ArchivesSpace should create revision_statement on import.

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#527]
While creation time of the record is captured in the database and thus preserved in ArchivesSpace as a system, it's not captured as an event in the life of the record.

A couple of people (mostly at Harvard, some others) have supported the idea of a revision statement added to represent the import process.  As far as I can tell, this could be added in two places:
1. the individual importers
2. StreamingImport#do_create) around [#L267](https://github.com/archivesspace/archivesspace/blob/7182437b8f0a5801cd63faf69cb4c52eaf8a7e4b/backend/app/lib/streaming_import.rb#L267)

It seems to me that it makes sense to put it outside the converter, so that every record gets an import statement regardless, and make the content overridable in config (maybe in converter?)

I'm having to do the work either plugin-wise or otherwise for Harvard anyway, so I'm happy to put up a PR, if people think this is a good idea generally.

**Comment by bdwestbrook** [comment]
I think it would be a good idea to raise this question on the Users Group List, as it may be possible that not everybody will agree that an import is a revision of the finding aid.  I would like to see how much community support there might be for this idea.  -bdw

**Comment by lmcglohon** [comment]
@pobocks Created JIRA ticket - https://archivesspace.atlassian.net/browse/AR-1689, so closing this one.
