### ISSUE TITLE
EAD Converter doesn't set publish on some objects

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#534]
Several types of objects default to publish: false and don't respect EAD audience values when provided.  The list handed to me by the archivists here includes:
- subnotes in resources and archival objects
- digital objects
- notes in digital objects

I'm working on a PR to handle these with the same logic as other elements currently handled properly by the importer, namedly:

``` ruby
{ # object initialization hash 
publish => att('audience') != 'internal'
}
```

On a related note, publish seems to be missing from some JSON schemas where it is present in the DB - notably, digital_object and note.

Note that my understanding of how aspace uses publish is pretty notional.

**Comment by pobocks** [comment]
This is definitely a thing.  I have a PR that catches it everywhere I can find it, but a solution which overrode #make or something and did this generically for all object types that support publish would definitely be cleaner.

**Comment by marktriggs** [comment]
@pobocks: here's a little patch that might get us some of the way to a more automated check:

https://gist.github.com/marktriggs/0d31cb42a53394131933c878464e61d3

I think I would need to get more eyes on it to feel confident that it's guessing correctly, but maybe a starting point :)

**Comment by pobocks** [comment]
That looks v similar to what I was thinking, albeit I was gonna do it in
the individual converters, since AFAIK att('audience') is an implementation
of concrete schema, and not dependable in all XML formats...

I think to do it cleanly, one would maybe want some sort of abstraction of
node-handling that concrete handlers could inherit behavior from?  That
would still leave things like my daogrp fix, which stop at a parent node
and process contents as a DocumentFragment, having to handle things
manually, but it would catch the simple case of "element handler makes one
element."

**Comment by pobocks** [comment]
Plz poke me tomorrow if the preceding made no sense, I'm in bad headspace
for the obvs reason right now and was kind of distracting myself with code,
but it's not working.

**Comment by marktriggs** [comment]
Yep, that makes sense (your explanation; not the election...)

So if we had a way for the concrete handlers to add a hook at the point the element is being created, they'd have access to the current node, the JSON schema and the attributes that had been passed in.  Then our new code could use that to add the "publish" attribute based on the combination of the audience attribute and the JSON schema.  Does that seem workable?

Thanks!
Mark

**Comment by pobocks** [comment]
@marktriggs that seems workable to me.  It obvs doesn't cover things like how I did file versions in daogrp, but I despair of a solution that does, and (at least so far) there aren't that many cases covered by that kind of "stop at parent and DOM parse" solution (although maybe there should be - might make list handling a lot easier).

Anyway, it's got my vote!

**Comment by marktriggs** [comment]
Cool!  I'll give it a go soon and report back.

And yeah, the daogrp case seemed a bit more specialized, so I'd be reluctant to try to come up with some sort of generalization for that without a few more examples.  I think the special case code is fine for now :)
