### ISSUE TITLE
Advanced Search XSS - Vulnerability

### ISSUE THREAD

**Issue by nstr10** [archivesspace/archivesspace#536]
Hi, it appears there is no sanitization of inputs for search filters:
`/search?filter_term[]={%22%22%3A%22%3Cscript%3Ealert(1)%3C/script%3E%22}&page=1`

Also of note, since the value sent in the above request has an empty key, the following is output in the "Filtered By" section, which seems like an issue:

> {:show_fewer=>"Show fewer", :show_more=>"Show more", :query=>"Text", :subjects=>"Subject", :primary_type=>"Type", :repository=>"Repository", :creators=>"Creator", :fullrecord=>"Keyword", :subjects_text=>"Subject", :title=>"Title", :creators_text=>"Creator", :scope=>"Scope", :notes=>"Notes", :source=>"Source", :agents=>"Agents", :agents_text=>"Agents", :classification_uri=>"Classification", :linked_agent_roles=>"Role"}: 

There ought to be checks to verify [A] whether the filter key exists in the array of available filters and then [B] that the value passed in for said key is free of any markup. In most applications I've seen, the key and value are separate GET variables that are each sanitized before use. Blindly parsing the string as an object and reflecting it in the output seems like a bad idea to me.

I am not a Ruby or Java developer and regardless don't have time to track down the source of this vulnerability, so no pull request.

**Comment by cfitz** [comment]
Yep, this is a known issue and will most likely be addressed with the new public UI ( since the current app uses Rails 3 ).

**Comment by nstr10** [comment]
Thanks for the quick reply! I'm assessing an instance of this app for production use and this issue has me on the fence about it. Is there a target date for when the new public UI will be released?

**Comment by mark-cooper** [comment]
You have the option of going into production with the public app disabled, if that works for you. New public ui, off the top of my head, will have a beta by the end of the year, or early next year I think -- just don't quote me on that 😄 

@fordmadox can you confirm / deny timeline for new public ui?

**Comment by cfitz** [comment]
@nstr10 just curious if you're part of a member organization?

**Comment by nstr10** [comment]
@cfitz That I'm not sure of - I work for an educational institution, and my role in this project is just to identify potential security issues before the site is put in production.

**Comment by cfitz** [comment]
@nstr10 ok...well, there's a one liner fix that I just submitted as a PR. 

The original public UI never got much love or attention, and as @mark-cooper says, there is supposed to be a new public UI soon. You can run the application with the public UI disabled for now. 

 Install [this patch](https://gist.github.com/cfitz/67f21316f5cb7a91ec30fc38ffafd157) as a plugin and see if that works for you.

**Comment by fordmadox** [comment]
end of the year is still the goal, but it's possible that the
candidate/beta release won't be ready until January.

The code for the new PUI is here,
https://github.com/archivesspace/public-new, although i hope by March it's
merged back with the core ASpace code for the next release.

If anyone notices any issues, please let us know!

**Comment by nstr10** [comment]
@cfitz Sorry, forgot to follow up on this - thanks for the patch! It's a good [temporary?] solution.

@fordmadox Thanks for the update!
