### ISSUE TITLE
Checkout on windows fails

### ISSUE THREAD

**Issue by RaananW** [archivesspace/archivesspace#556]
Hi,

there is a file called "<<<<<<<-head.md" located at https://github.com/archivesspace/archivesspace/blob/master/docs/user/%3C%3C%3C%3C%3C%3C%3C-head.md. "<" is an illigal character in windows file system. This  prevents me from being able to checkout the repo (failed to write the file).

Will it be possible to change the filename? I would submit a PR myself, but I won't send the entire signed form just for a single `git mv` . Besides, I don't know what the filename should be called. (I guess head.md?)

Thanks a lot!

**Comment by marktriggs** [comment]
Thanks @RaananW!  That does indeed look like an error.  I've just removed the file now.

Cheers,
Mark
