### ISSUE TITLE
NoMethodError for #container on context object in ead_converter

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#562]
Around [here](https://github.com/archivesspace/archivesspace/blob/master/backend/app/converters/ead_converter.rb#L610), import can fail on some EAD with 
```
(NoMethodError) undefined method `container' for #<Hash:0x2a687e52>
```  
I don't have time to investigate further right now, and this only affects one of our finding aids, but the solution might be as simple as just using hash key-based access syntax or methods, bc instances are (if I'm understanding correctly) still just hashes at all points prior to saving the object as a whole in most?

**Comment by pobocks** [comment]
it looks like when in container-handler, when container is triggered in a situation where the context_obj is something OTHER than an instance, it grabs the last instance in whatever context obj is.  

context_obj.instances returns an array of HASHES - they're suitable for turning into JSONModels, but they're not actually JSONModels.  So, they don't have a container attr.

----------Line Below Which Speculation Exists-----------

I think the right thing is to just wrap the instance in the instance constructor. I'm not 100% sure, but based on my daogrp work, it seems plausible?  If jsonmodel properties are supposed to return hashes rather than subsidiary JSONModels, then it's almost certainly how it would have to be done.

**Comment by pobocks** [comment]
Some investigation Noah Huffman and Mark Custer has done led me to the conclusion that it might be more complicated than just "wrap the hash in the instance constructor" - the instance that you get depends on ordering in the source document, and if it's possible for the any of those instances to have differing container values, then I'm not sure what the right thing to do is.

**Comment by fordmadox** [comment]
So, is this just a procedural code error?  The document order / placement of dao elements doesn't matter in EAD, but wouldn't a simple fix be to say that ASpace can't (for now) ingest daos within the did element, so make sure that they're all outside of the did (see the third component in the example below).  

And here's a DSC excerpt that can be used for testing:

      <dsc type="in-depth">
         <c>
            <did>
               <unittitle>test</unittitle>
               <container type="box">1</container>
               <daogrp xlink:type="extended">
                  <resource xlink:label="start" xlink:type="resource"/>
                  <daoloc
                     xlink:href="http://nrs.harvard.edu/urn-3:HUL.ARCH:193562" xlink:label="resource-1" xlink:type="locator"/>
                     <arc xlink:from="start" xlink:show="embed" xlink:to="resource-1"
                        xlink:type="arc"/>
                     <daoloc
                        xlink:href="http://nrs.harvard.edu/urn-3:HUL.ARCH:127141"
                        xlink:label="resource-2" xlink:type="locator">
                        <daodesc>
                           <p>Click here for larger view.</p>
                        </daodesc>
                     </daoloc>
                     <arc xlink:actuate="onRequest" xlink:from="start"
                        xlink:show="new" xlink:to="resource-2" xlink:type="arc"/>
               </daogrp>
            </did>
         </c>
         <c>
            <did>
               <unittitle>test</unittitle>
               
               <container type="box">1</container>
            </did>
         </c>
         <c>
            <did>
               <unittitle>test</unittitle>
               <container type="box">1</container>
            </did>
            <daogrp xlink:type="extended">
               <resource xlink:label="start" xlink:type="resource"/>
               <daoloc
                  xlink:href="http://nrs.harvard.edu/urn-3:HUL.ARCH:193562" xlink:label="resource-1" xlink:type="locator"/>
               <arc xlink:from="start" xlink:show="embed" xlink:to="resource-1"
                  xlink:type="arc"/>
               <daoloc
                  xlink:href="http://nrs.harvard.edu/urn-3:HUL.ARCH:127141"
                  xlink:label="resource-2" xlink:type="locator">
                  <daodesc>
                     <p>Click here for larger view.</p>
                  </daodesc>
               </daoloc>
               <arc xlink:actuate="onRequest" xlink:from="start"
                  xlink:show="new" xlink:to="resource-2" xlink:type="arc"/>
            </daogrp>
         </c>
      </dsc>

As is, all 3 components import fine.  If you uncomment the daogrp in that second component, though, then you'll get that strange "container" error.

**Comment by fordmadox** [comment]
I mean, I know that ASpace can sometimes import DAOs within a did element, but this proves that the import process with daos and containers is only going to work all of the time right now if those values are separated (containers in the did element, where they have to be according to EAD, and digital objects outside of the did, where they optionally may be according to EAD).  Rather than allowing both for digitial objects, I think it makes the most sense to say that ASpace supports a sub-profile of EAD 2002 (and eventually a sub-profile of EAD3).  Just my two cents, unless there's something else that this affects that would require changes to the EAD import code.

**Comment by fordmadox** [comment]
You know what...  even that second component will import fine as long as you slap an @id attribute on that container element.  So, something else might be going on with how instances are grouped in this odd edge case of the container occurring after a dao group.  

In other words, this component _will_ import fine without any errors whatsoever (thanks to a new attribute)

         <c>
            <did>
               <unittitle>test</unittitle>
 <daogrp xlink:type="extended">
                  <resource xlink:label="start" xlink:type="resource"/>
                  <daoloc xlink:href="http://nrs.harvard.edu/urn-3:HUL.ARCH:193562" xlink:label="resource-1" xlink:type="locator"/>
                  <arc xlink:from="start" xlink:show="embed" xlink:to="resource-1" xlink:type="arc"/>
                  <daoloc xlink:href="http://nrs.harvard.edu/urn-3:HUL.ARCH:127141" xlink:label="resource-2" xlink:type="locator">
                     <daodesc>
                        <p>Click here for larger view.</p>
                     </daodesc>
                  </daoloc>
                  <arc xlink:actuate="onRequest" xlink:from="start" xlink:show="new" xlink:to="resource-2" xlink:type="arc"/>
               </daogrp>
               <container id="nomoretears" type="box">1</container>
            </did>
         </c>

**Comment by pobocks** [comment]
The above is kind of why I think the code should actually be looked at by someone with a good grasp of the ASpace data model around instances and rewritten to be correct - because:

- there IS conditional logic that changes depending on attr values 
- the logic isn't documented except in that code
- the logic isn't a reflection of the EAD schema

I don't think it's hard to do, and if I wasn't in the middle of our production ingest I would puzzle it out, but I think the work it would take to come up with a genuinely "safe" subprofile is the same work you'd need to do to figure out how to fix it.

**Comment by lmcglohon** [comment]
@pobocks Created JIRA ticket for this - https://archivesspace.atlassian.net/browse/AR-1688, so closing this one.
