### ISSUE TITLE
EAD physdesc/@label is not mapped during import, but it should be

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#568]
Just an FYI of another small EAD import issue, which should be very simple to fix.  The physdesc section starts here:

https://github.com/archivesspace/archivesspace/blob/master/backend/app/converters/ead_converter.rb#L242

The EAD serializer in ASpace also doesn't include these values, which is counter to expectations (and how the AT used to work).

**Comment by lmcglohon** [comment]
@fordmadox Created a JIRA ticket for this - https://archivesspace.atlassian.net/browse/AR-1687, so closing this one.
