### ISSUE TITLE
Physdesc/dimensions/physfacet note label values are not included in EAD exports

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#569]
Unlike the other notes, the label value in ASpace are not included in the EAD exports for those three notes.  A current export looks like this:

          <physdesc id="aspace_af7e16a1e6a006234b2d479b62a665a1">label export text</physdesc>
          <physdesc><physfacet id="aspace_51e89690b57e76bba47be95126e7b002">label export
              test</physfacet></physdesc>
          <physdesc><dimensions id="aspace_0e4abd582d2d679abb3b3d329dd0f796">label export
              test</dimensions></physdesc>

But it should include a label value for these three notes in a label attribute (whereas most of the other notes that can have a label, have those mapped to a head element):

          <physdesc label="labelexporttest" id="aspace_af7e16a1e6a006234b2d479b62a665a1">label export text</physdesc>
          <physdesc><physfacet label="labelexporttest" id="aspace_51e89690b57e76bba47be95126e7b002">label export
              test</physfacet></physdesc>
          <physdesc><dimensions  label="labelexporttest" id="aspace_0e4abd582d2d679abb3b3d329dd0f796">label export
              test</dimensions></physdesc>

I *assume* that the same issue would exist for the abstract element, but I haven't tested that yet.  Since you can add a "label" in the ASpace staff interface, though, it should be included in the imports and exports (just like the AT used to do).

[All that said, I still think that the dimensions and physfacet notes could just be subsumed into a generic physdesc note, as long as that mixed encoding would be retained during import and exporter... but that's another issue / feature-removal request.]

**Comment by lmcglohon** [comment]
@fordmadox Created JIRA ticket for this - https://archivesspace.atlassian.net/browse/AR-1686, so I am closing this ticket.
