### ISSUE TITLE
Format content breaks XML whitespace semantics when content is left-justified.

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#572]
Currently, the EAD converter's `#format_content` method, has a line, located [here](https://github.com/archivesspace/archivesspace/blob/18952e431e78358b8fe8cdc46cfbaf9fb9e5ebb3/backend/app/converters/ead_converter.rb#L48), that deletes all newlines in the formatted content.

In cases where the following line is a continuation of text on the previous line and has no leading space, this will cause data corruption, e.g.

```xml
<p>Yay, ASpace is cool
let's fix some XML</p>
```

will turn into this on import:

```xml
Yay, ASpace is coollet's fix some XML
```

This doesn't happen more often solely because most XML tools pretty-print and preserve indentation even for breaks in text within tags.  But we've seen instances processed with XMetaL or WordPerfect where whole files are left-justified, and this issue happens thousands of times per file.  Additionally, there's no hard guarantee that it won't happen to pretty-printed XML, it's just less likely.

**Comment by pobocks** [comment]
Thanks for the fast action on these, @marktriggs!  Is it too late for these to go into a 1.5.2.RC3?

**Comment by marktriggs** [comment]
Not my call, but I think they'll make it.  We have another few fixes to go in anyway.
