### ISSUE TITLE
Tomcat Runtime error: doesn't look like a Tomcat directory

### ISSUE THREAD

**Issue by ccmn98** [archivesspace/archivesspace#61]
I am trying to install ArchivesSpace on a Ubuntu 14.04 running with a manually installed Tomcat 7.0.53. The folders for both programs are at the var/tmp directory (if I move tomcat folder to a folder not owned my root, tomcat doesn't work). 

When I run this script: archivesspace_v1.0.7.1/archivesspace/scripts/configure-tomcat.sh ../tomcat7

I get this as a response:

archivesspace_v1.0.7.1/archivesspace/scripts/configure-tomcat.sh: line 3: cd: ../tomcat7: No such file or directory
Loading ArchivesSpace configuration file from path: /var/tmp/archivesspace_v1.0.7.1/archivesspace/config/config.rb
Loading ArchivesSpace configuration file from path: /var/tmp/archivesspace_v1.0.7.1/archivesspace/config/config.rb
RuntimeError: Directory '/var/tmp' doesn't look like a Tomcat directory.
  initialize at ../launcher/tomcat/lib/configure-tomcat.rb:22
      (root) at ../launcher/tomcat/lib/configure-tomcat.rb:139

I also got this same message on the our museum's hosting site which is running CentOS. In this instance, I have run this script other times, but it work normally.  Both the Tomcat and archivesspace files are located in the same directory.

Any thoughts on what is making this happen?

**Comment by cfitz** [comment]
Hello,

This is an old issue. Going back on this...is this still a problem for you in v1.1.2?

**Comment by quoideneuf** [comment]
I'm closing this because it's old and the OP never replied: ¯\\_(ツ)_/¯
