### ISSUE TITLE
Digital Object deletion leaves 'digital_object' instance type

### ISSUE THREAD

**Issue by ives1227** [archivesspace/archivesspace#615]
When deleting a digital object from ArchivesSpace, the instance_types value of "digital_object" does not get removed from the resource_tree.  Therefore, in the frontend, the resource tree still displays 'Digital Object' next to the resource and/or archival object.  

To replicate:
1. attach a digital object to an archival object
2. navigate to the digital object record
3. delete the digital object 
4. navigate back to the archival object

You will see that the tree still has the 'Digital Object' but the actual digital object will no longer be under the 'Instances'.

The work-around is to:
1. Delete the instance from the archival object
2. navigate to the digital object
3. delete the digital object

**Comment by lmcglohon** [comment]
@ives1227 I have moved this into this JIRA ticket - https://archivesspace.atlassian.net/browse/AR-1685. SO I am going to close this issue.
