### ISSUE TITLE
"Queue Job" button always disabled for some job types

### ISSUE THREAD

**Issue by cvonkleist** [archivesspace/archivesspace#630]
I think there is a bug with the **Queue Job** button on the **New Background Job** page.

Whenever the **Reports** job type is selected from the **Job Type** dropdown, the **Queue Job** button becomes disabled. This is intentional, and the button becomes reenabled once you select a report. However, if you don't select a report, and you instead select a different job type from  **Job Type** dropdown (e.g., **Import Data** job type), then the **Queue Job** button remains disabled and cannot be reenabled. Because of this, there is no way to initiate the job.

Looking at the code, it seems that `addClass('disabled')` is called on the **Queue Job** button when the **Reports** job type is selected, and `removeClass('disabled')` is only ever called when the user selects a report. I don't think `removeClass('disabled')` is ever called when one of the other job types is selected, and this is why the button is never reenabled:

https://github.com/archivesspace/archivesspace/blob/d0f4649904a00ee73e469d4c4ff3db4466d9f8a8/frontend/app/assets/javascripts/jobs.crud.js#L125

On one of our ArchivesSpace instances, it seems that sometimes the **Reports** job type is the default selection in the dropdown, and on this instance one our users noticed the **Queue Job** button problem immediately because the **Queue Job** button is always initially disabled. On other instances, the **Reports** job type is not the default (for some reason), so the **Queue Job** button is not initially disabled.

<img width="1168" alt="screen shot 2017-02-27 at 8 24 56 pm" src="https://cloud.githubusercontent.com/assets/20558/23364124/4a9f2c06-fd30-11e6-913b-392650bbec10.png">

**Comment by lmcglohon** [comment]
@cvonkleist I believe that this was fixed with 2.0.0_RC1. Can you reproduce it in the newest release candidate?

**Comment by lmcglohon** [comment]
@cvonkleist I tested this in the 2.1.0 release and I cannot recreate the issue so closing this issue.
