### ISSUE TITLE
Trying to use Archon->AS Migration Tool:  Failing on source connection details

### ISSUE THREAD

**Issue by csaundrs** [archivesspace/archivesspace#638]
When I try to run the migration tool, the message  "Source connection could not be established .." appears when I hit the "Copy to Archives Space" button.

I have a valid user/pass for Archon and the link in the "Archon Source" box resolves fine to the Archon page through a browser.

What should I be looking at to troubleshoot this?   

Thanks,
Chris

**Comment by jenhm** [comment]
I'm wondering if this has to do with the security error that happens on archon-test? I set up the same username/password for you on Archon prod to see if you run into the same problem.

If you do, we may need to actually use the sa login as shown in that screenshot you emailed me.

**Comment by csaundrs** [comment]
I get the same issue on prod
________________________________

**Comment by jenhm** [comment]
OK, so my next guess is to use "sa" and "admin" as pictured in that image. I'm looking through my information on Archon to see if I have a different "sa" password since I imagine that it was changed.

**Comment by jenhm** [comment]
Found the correct sa password and shared off github.

**Comment by jenhm** [comment]
sa password did not work either.

**Comment by csaundrs** [comment]
we have the Archon server pretty locked down network-wise.  Does anyone know what port the migration tool needs to use?

**Comment by lmcglohon** [comment]
@csaundrs @jenhm Did you get this worked out?

**Comment by csaundrs** [comment]
Imcglohon,  No we never have gotten past this.  Still getting the same error.

**Comment by lmcglohon** [comment]
@csaundrs @jenhm I have a few questions: What version of ArchivesSpace are you migrating to and what version of the ArchonMigration Tool are you using?

**Comment by Blake-** [comment]
That should be using just plain old port 80. It sounds like a user/pass problem, can you double check you can login into Archon with that same user/pass you're using in the migrator?

**Comment by jenhm** [comment]
I just verified the sa password, I had to update it, so that may very well be the problem. I can now login to Archon using the sa password so I'll have @csaundrs check the migration now. If it is that simple mea culpa for bad record keeping.

**Comment by csaundrs** [comment]
Thanks for the response guys,

To answer Imcglohon, We have installed ArchivesSpace 1.4.2 on it's own server and are using ArchonMigrator 1.1   We have run the migrator both on a separate windows client and locally on the Archon server (ubuntu).

Well, using the SA login has now gotten me to the same error message, but running the ArchonMigrator (1.1) on the linux box that contains Archon, There are program errors that come to the command line:


-rwxrwxrwx 1 csaundrs sudo 6104724 Mar  7 10:12 ArchonMigrator.jar
csaundrs@archon-test:~$ java -jar ArchonMigrator.jar
log4j:WARN No appenders could be found for logger (org.apache.commons.httpclient.HttpClient).
log4j:WARN Please initialize the log4j system properly.
username: sa, password: ******
post: http://localhost/archon?p=core/authenticate
Status code: 404
Status text: Not Found


With that more specific error message, can anyone offer guidance?

**Comment by Blake-** [comment]
That 404 probably means that Archon isn't at http://localhost/archon/ 
When you login to Archon, what's the URL? That's the one you want there.

**Comment by csaundrs** [comment]
I have changed the Archon Source to http://archon-test.carli.illinois.edu   which is the url that works to connect to Archon via a browser, but I still get the message

"Source Connection couldn't be established"


This is now the feedback from the program on ubuntu:

username: sa, password: j1nk1e
post: http://archon-test.carli.illinois.edu?p=core/authenticate
Status code: 200
Status text: OK

This is how the Archon Migrator form was filled out to submit (except with the SA pw removed)

![image](https://cloud.githubusercontent.com/assets/18536549/24763131/b5b5620e-1aad-11e7-871f-93c62bc19123.png)

**Comment by Blake-** [comment]
"Source Connection couldn't be established" sounds like we're back to user/pass problem. If you try to login to Archon directly with that user/pass does it let you in?

**Comment by csaundrs** [comment]
I have verified that the sa user/pw does work when you go to the main archon page to log in.

**Comment by csaundrs** [comment]
Is there a way to log into archon from the ubuntu command line so I can test the user/pw that way as well?

**Comment by Blake-** [comment]
Good question, I don't think so. I wonder if that same error would come from having wrong ArchivesSpace creds? Did you double check those as well?

**Comment by lmcglohon** [comment]
@csaundrs @jenhm Are you still having troubles with this?

**Comment by lmcglohon** [comment]
@csaundrs @jenhm Are you still having troubles with this? We have released an updated version of the Archon migration tool: https://github.com/archivesspace/archon-migration/releases/tag/v2.0.

**Comment by lmcglohon** [comment]
@csaundrs @jenhm Did this ever get resolved? If so, I would like to close the issue.

**Comment by csaundrs** [comment]
Imcglohon,  With the version we used, we never got it to work.  We can try to install 2.0 and see if it has a  better result for us.

**Comment by lmcglohon** [comment]
@csaundrs OK.  Let me know how it goes.  I am going to close this issue for now.
