### ISSUE TITLE
Create User button not functional (1.0.9 w/ LDAP)

### ISSUE THREAD

**Issue by mickelj** [archivesspace/archivesspace#67]
After upgrading to 1.0.9, the Create User button immediately returns to the main URL.  We have LDAP configured in our setup.

Please advise if this is an issue with all installations or if it appears we have a local problem.  Thanks!

**Comment by mark-cooper** [comment]
Closing as an old issue. Create user with LDAP configured does not manifest this behavior in current release (v1.4.2).
