### ISSUE TITLE
EAD export produces malformed XML in v. 1.0.9

### ISSUE THREAD

**Issue by marktriggs** [archivesspace/archivesspace#68]
Issue moved from https://github.com/hudmol/archivesspace/issues/776 -- created by @kardeiz

-----

In upgrading to the latest release, I've noticed that the EAD exporter is generating invalid XML for many of my finding aid "resources". Some XML files end with a closing </did> tag; the root <ead/> node and possibly others remain unclosed.

I've tried this with a number of different EAD export options, but that has no effect. However, some resources do in fact generate well-formed and valid EAD files, which leads me to think the issue is with how AS is parsing certain fields.

In my previous version (v. 1.0.0 or v. 1.0.1--question: is there an easy way to find out which version I'm running, either from the web interface or in my app directory?), all resources (as far as I can tell) generate valid XML. This includes those resources which are having issues in v. 1.0.9.

I realize that it would be easier to debug this issue with a snapshot of my resource data. Is there an easy way to get a "data dump" of some sort for an AS resource?

**Comment by cfitz** [comment]
This was fixed in v1.1.0. Closing for housekeeping.
