### ISSUE TITLE
new public interface digital objects link errors

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#694]
Some of my digital objects in the new public interface, are displayed with method="post" links instead of a GET.  
Clicking on those links goes to a page with the text "Method Not Allowed" 

Here is the source of that line:
https://github.com/archivesspace/archivesspace/blob/v2.0.0-RC1/public-new/app/views/shared/_digital.html.erb#L9

Question: Is there some reason for wanting a POST method here, or is that just an error ? 

Looking for the source of some of the attributes used in the above template, I find this:
https://github.com/archivesspace/archivesspace/blob/v2.0.0-RC1/public-new/app/models/resource.rb#L37-L58

Editing my digital object to set clink-show-attribute to "embed" makes the link method default to "GET" , but shows a broken image "?" as it's not really an embeddable image. 

Not sure what is the intended behavior here and what is a bug.

**Comment by sdm7g** [comment]
Also note that AR-1561 is still a problem on the frontend. I can't get complete URIs from my digital objects as the scheme is being changed to "file:" .

**Comment by lmcglohon** [comment]
Corresponding JIRA ticket - https://archivesspace.atlassian.net/projects/AR/issues/AR-1681

**Comment by sdm7g** [comment]
Note: I'm seeing the POST problem with http: URLs ( not file: as in that JIRA ticket ) and I'm still seeing the behavior in v2.1.0-RC1 . Clicking on the digital object icon brings up an error page ( because the POST doesn't work ) but the URL in the address bar is correct: (in Safari) if I click on the reload  icon, it asks if I want to send a form again, and gives the same error page, but if I just hit <return> at the end of the URL in address bar, it reloads with a GET and display the correct page.

**Comment by sdm7g** [comment]
PS: It would also be helpful if some of the digital object attributes ( like use-statement/role ) were passed in the page, even if hidden. ( This would enable knowing whether to fire IIIF scripts in public display. )

**Comment by lmcglohon** [comment]
@sdm7g I believed I fixed the link problem here: https://github.com/archivesspace/archivesspace/pull/1072. Does that mean we can close this issue and the corresponding JIRA ticket (https://archivesspace.atlassian.net/projects/AR/issues/AR-1681)?

**Comment by lmcglohon** [comment]
JIRA ticket moved to https://archivesspace.atlassian.net/browse/ANW-264
