### ISSUE TITLE
LCNAF plugin can't search when OCLC option is selected

### ISSUE THREAD

**Issue by cvonkleist** [archivesspace/archivesspace#699]
The LCNAF plugin can't search when the OCLC option is selected. This is happening because OCLC has dropped support for the web service powering the search. We see this error in ArchivesSpace:

```
SRUSearcher::SRUSearchException in LcnafController#search
```

I emailed OCLC about it, and this is what they had to say:

> Thanks for pointing this out. It turns out that we have not supported this service for some time. We have been directing users to the version hosted by the Library of Congress instead:
>  
> http://id.loc.gov/authorities/names.html
>  
> I will work on updating our documentation accordingly.

You can see that the service is broken by doing the following request with curl:

```
curl 'http://alcme.oclc.org/srw/search/lcnaf?query=test'
```

I expect to get search results; however, this is what comes back:

```
HTTP/1.0 302 Found
Location: http://ServiceUnavailable.oclc.org
Connection: close
```

If I follow this 302 redirect, I see this:

```
  Directory Listing Denied: This Virtual Directory does not allow contents to be listed.
```

Here is the line in the ArchivesSpace LCNAF plugin source code where the service URL is set:

https://github.com/archivesspace/archivesspace/blob/6026a8ab461b55271d6b9418808e3ea1284c72fb/plugins/lcnaf/frontend/controllers/lcnaf_controller.rb#L62

**Comment by lmcglohon** [comment]
@cvonkleist Created JIRA ticket - https://archivesspace.atlassian.net/browse/AR-1690, so closed this one.
