### ISSUE TITLE
Adding event to existing archival object redirects to invalid route

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/archivesspace#71]
When adding an event to an existing archival object record, an exception is thrown after 'save' is clicked. This seems to be due to the controller re-directing to an invalid route (does not happen when adding an event to a resource).

To reproduce:
1. Open an archival object record in edit mode
2. Use "add event" drop-down to add an event.
3. Enter required event details and click 'save'
4. "Something went wrong..." message displays. URL corresponds to the archival object  (e.g. '/archival_objects/333438', which is not a valid route)
5. Browse events and locate the event just created - it's there and is correctly linked to the record

**Comment by cfitz** [comment]
Hi, 
Yes, events without a specific field caused an issue. This was fixed in v1.1.0. Closing this for housekeeping.
