### ISSUE TITLE
footers in html docs for v2.0.0 release still say v1.5.3a

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#725]
minor glitch in the v2.0.0 release:

footers in html docs for v2.0.0 release still say v1.5.3a

probably due to common/asconstants.rb still says `fallback_version = "v1.5.3.a"`

( frontend footer and backend status correctly say v2.0.0 )

**Comment by lmcglohon** [comment]
@sdm7g Is this still true?  I can't replicate on latest release html docs...

**Comment by sdm7g** [comment]
It's what's in the last doc build that was in the 2.0.0 release. 
https://github.com/archivesspace/archivesspace/blob/master/docs/doc/vocabulary_schema.html#L134

I think the source of the problem is that the doc build uses value from common/ARCHIVESSPACE_VERSION , which is in .gitignore, and may retain value from last build, so even after version in common/asconstants.rb is updated, doc build may contain the wrong version number.

**Comment by sdm7g** [comment]
More accurately:  _yard footer template
https://github.com/archivesspace/archivesspace/blob/master/_yard/templates/default/layout/html/footer.erb
is using ASConstants.VERSION , and what's in common/ARCHIVESSPACE_VERSION overrides what's in common/asconstants fallback version number, so probably doc:yardoc should delete that file, or else whoever builds docs before release has to remember to delete it.

**Comment by lmcglohon** [comment]
Cool!  Thanks @sdm7g!  I'll get the process for creating the documentation for release updated so that in the future, it will be correct.
