### ISSUE TITLE
Look into Solr STABLE (currently 6.x)

### ISSUE THREAD

**Issue by mark-cooper** [archivesspace/archivesspace#734]
Just registering an issue for this one. 4.10.4 is technically EOL:

https://lucene.apache.org/solr/community.html#about-versions
https://cwiki.apache.org/confluence/display/solr/Upgrading+Solr
https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+4+to+Solr+5
https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+5+to+Solr+6

"Solr is Now a Standalone Server ... Deployment as a "webapp" to other Servlet Containers (or other instances of Jetty) is not supported, and may not work in future". 'Tis a big change.

**Comment by mark-cooper** [comment]
Some notes:

Did the most basic possible testing with 6.5.1. New install, single core created for ArchivesSpace using the existing configuration files.

To get no errors on core creation make these edits:

Remove `enablePositionIncrements="true"` from schema.xml (2 occurences).

Remove this from solrconfig.xml:

```xml
  <!-- Admin Handlers

       Admin Handlers - This will register all the standard admin
       RequestHandlers.
    -->
  <requestHandler name="/admin/"
                  class="solr.admin.AdminHandlers" />
```

Superificially this is working, but schema and solrconfig should be reviewed for appropriate updates:

Still using: `<luceneMatchVersion>LUCENE_40</luceneMatchVersion>`.

Solr log errors:

```
TokenizerFactory is using deprecated 4.0.0 emulation. You should at some point declare and reindex to at least 6.0,&#8203; because 5.x emulation is deprecated and will be removed in 7.0
...
TokenFilterFactory is using deprecated 4.0.0 emulation. You should at some point declare and reindex to at least 6.0,&#8203; because 5.x emulation is deprecated and will be removed in 7.0
```

**Comment by mark-cooper** [comment]
Easy (with Docker) external Solr testing:

https://github.com/archivesspace/archivesspace/blob/master/README_DOCKER.md
https://github.com/archivesspace/archivesspace/blob/master/docker-compose.yml

**Comment by lorawoodford** [comment]
Closing, as we will no longer track these maintenance issues in GH.
