### ISSUE TITLE
Custom Stylesheets

### ISSUE THREAD

**Issue by vergelal** [archivesspace/archivesspace#74]
Following instructions provided in https://github.com/hudmol/archivesspace/tree/master/plugins, where it reads "files such as images, stylesheets and PDFs can be made available as static resources by placing them in an assets directory under an enabled plug-in," I have tried to modify the color scheme of my local instance's public interface. I thought putting customized copies of as-eac-cpf-html.xsl and as-ead-html.xsl in plugins/local/public/assets would do it, but I've gotten nowhere. I also tried placing a customized variables.less in the same directory to no avail. What stylesheet should I place in plugins/local/public/assets to override the master one?

**Comment by cfitz** [comment]
Hi, doing some house keeping...
Please see this : https://github.com/archivesspace/archivesspace/wiki/Customizing-&-Theming-ArchivesSpace for some themes. 
Let us know if you have any other questions...a good place is the mailing list.
