### ISSUE TITLE
Frontend plugin locales no longer overwriting common locales

### ISSUE THREAD

**Issue by vncaMichaelD** [archivesspace/archivesspace#757]
Plugins with Frontend locales are no longer overwriting the common locales.  Public locales do overwrite.

**Comment by lmcglohon** [comment]
@vncaMichaelD Is this still the case with the latest version of ArchivesSpace? I believe this might have been fixed in v2.1.0.

**Comment by vncaMichaelD** [comment]
It looks like it is resolved in v2.1.0.

**Comment by lmcglohon** [comment]
Great!
