### ISSUE TITLE
public/app/views/records/_instances.html.erb not yet updated for new container model. Throws error. 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#802]
public/app/views/records/_instances.html.erb not yet updated for new container model. Throws error. 

top_container has to be resolved for the first three; container should be sub_container for others. 

https://github.com/archivesspace/archivesspace/blob/master/public/app/views/records/_instances.html.erb#L16-L23

**Comment by lmcglohon** [comment]
File was removed from master when the new public user interface was put into place so I am closing this issue
