### ISSUE TITLE
PDF stylesheet update needed

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#825]
Just a quick note that both instances of .[@label] should just be changed to @label.  Saxon 9.7 at least throws the XTSE0340 error.  I think it still used to group things okay, but I'd also say it's probably safer to group on the parent / id attributes here, but both should work with how ASpace creates the export.  Anyway, just an FYI in case this transformation ever fails after upgrading Saxon.  

Regardless, the syntax would be much more appropriate as `group-starting-with="@label"` !

**Comment by lmcglohon** [comment]
Also, look at this: https://archivesspace.atlassian.net/browse/ANW-258

**Comment by lmcglohon** [comment]
@fordmadox We are already up to Saxon 9.8 and I am not seeing any issues with this. I am going to close this issue but we can refer to it in the future if issues do come up.
