### ISSUE TITLE
Unable to build documentation

### ISSUE THREAD

**Issue by lmcglohon** [archivesspace/archivesspace#834]
@marktriggs Please see screen shot below - the building of the documentation is not working.

lyrasiss-mbp:archivesspace lyrasis$ build/run doc:build
Buildfile: /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/build/build.xml

set-classpath:

doc:yard:
     [java] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=196m; support was removed in 8.0
     [java] Loading ArchivesSpace configuration file from path: uri:classloader:/config/config.rb
     [java] rake aborted!
     [java] NameError: uninitialized constant ArchivesSpaceOAIRepository::ArchivalObject
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/backend/app/lib/oai/aspace_oai_repository.rb:9:in `<class:ArchivesSpaceOAIRepository>'
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/backend/app/lib/oai/aspace_oai_repository.rb:4:in `<main>'
     [java] uri:classloader:/jruby/kernel/kernel.rb:1:in `(root)'
     [java] uri:classloader:/jruby/kernel/kernel.rb:13:in `<main>'
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/backend/app/lib/oai/aspace_oai_provider.rb:3:in `(root)'
     [java] uri:classloader:/jruby/kernel/kernel.rb:1:in `<main>'
     [java] uri:classloader:/jruby/kernel/kernel.rb:13:in `block in require_relative'
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/backend/app/controllers/oai.rb:1:in `block in (root)'
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/_yard/rakefile.rb:1:in `block in (root)'
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/_yard/rakefile.rb:40:in `(root)'
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/_yard/rakefile.rb:40:in `block in (root)'
     [java] /Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/_yard/rakefile.rb:74:in `block in (root)'
     [java] Tasks: TOP => doc:api
     [java] (See full trace by running task with --trace)

BUILD FAILED
/Users/lyrasis/Desktop/ASpaceVersions/check_new_master/archivesspace/build/build.xml:572: Java returned: 1

This will prevent us from being able to put out the final release but not the release candidates.

**Comment by marktriggs** [comment]
Oops, thanks @lmcglohon.  I'll check this out soon.

**Comment by marktriggs** [comment]
Right!  That should be fixed in the linked PR.  And I learned something about YARD (well, anything)
