### ISSUE TITLE
indexentry handling is wrong, suggest adoption of fix based on work done by Bentley

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#873]
Currently, in the EAD importer, indexentry elements are processed such that refs, persnames, famnames, etc - any child element, basically - will be ingested as its own item.

The incoming PR fixes this. It's based on the work here: https://github.com/bentley-historical-library/bhl-ead-importer with slight cleanup and modification.

Corresponds to ANW-167 https://archivesspace.atlassian.net/browse/ANW-167

**Comment by lmcglohon** [comment]
This was implemented with pull request #874
