### ISSUE TITLE
backend API  /repositories/:repo_id/preferences/defaults  broken: undefined method 'defaults_for' 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#879]
calls to GET /repositories/:repo_id/preferences/defaults  in current master ( v2.1.0-RC ) return "error":"undefined method `defaults_for' for Preference:Class\nDid you mean?  defaults"

It looks like the method name and args were changed in the model, but not in the controller. 
This seems to work for me. But looks like it's repository scoped, so it also worked without the :repo_id .  Will investigate and test more. 

```
dcs-archivesspace$ git diff backend/app/controllers/preferences.rb 
diff --git a/backend/app/controllers/preferences.rb b/backend/app/controllers/preferences.rb
index 2c72fd0..85455a6 100644
--- a/backend/app/controllers/preferences.rb
+++ b/backend/app/controllers/preferences.rb
@@ -20,7 +20,7 @@ class ArchivesSpaceService < Sinatra::Base
     .permissions([])
     .returns([200, "(defaults)"]) \
   do
-    json_response(Preference.defaults_for(params[:repo_id], params[:username]))
+    json_response(Preference.parsed_defaults_for({ :repo_id => params[:repo_id], :user_id => params[:username] } ))
   end
```

**Comment by lmcglohon** [comment]
Closed by https://github.com/archivesspace/archivesspace/pull/885
