### ISSUE TITLE
locales configuration doesn't work for changing language of PUI

### ISSUE THREAD

**Issue by lmcglohon** [archivesspace/archivesspace#883]
From Br. Paul - When I build AS (2.1-RC1) locally, and set        AppConfig[:locale] = :fr
in config.rb, the staff interface is displayed in french but *not* the new public user interface. 

I tested this with the latest master this morning and am having the same problem.  I have attached screen shots. 

<img width="1043" alt="screen shot 2017-07-05 at 11 00 53 am" src="https://user-images.githubusercontent.com/3585151/27874146-7e9a962a-617c-11e7-9e99-ebf8aeb2e7ce.png">
<img width="1123" alt="screen shot 2017-07-05 at 11 01 15 am" src="https://user-images.githubusercontent.com/3585151/27874153-82de20e4-617c-11e7-9eed-eda32c1c0aad.png">

This needs to be fixed before we can put out another release candidate.

**Comment by sdm7g** [comment]
I looks like this line (from frontend/config/application.rb ) is missing in public app:
https://github.com/archivesspace/archivesspace/blob/master/frontend/config/application.rb#L76

    `config.i18n.default_locale = AppConfig[:locale]`

I added it to public/config/application.rb right after the I18n path and folder additions and it works for me.
