### ISSUE TITLE
Some fonts not loading when using a URL prefix

### ISSUE THREAD

**Issue by lmcglohon** [archivesspace/archivesspace#888]
For example, getting the following error in the console:

Failed to decode downloaded font: http://test.archivesspace.org/assets/PTS75F-webfont-2fc89e4bb41ae3747474e804b2c1ee95b9ff4cb01056d18e16a1dfb7d3e9ba68.woff
search?utf8=✓&op[]=&q[]=hercules&limit=&field[]=&from_year[]=&to_year[]=&commit=Search:1

**Comment by mark-cooper** [comment]
See console in dev tools (chrome) for: http://test.archivesspace.org/public/

**Comment by mark-cooper** [comment]
@lmcglohon @marktriggs FYI

https://github.com/archivesspace/archivesspace/blob/master/frontend/app/assets/stylesheets/archivesspace.less#L30-L34

These aren't being found with prefix. Also some fonts:

assets/glyphicons-halflings-regular.woff woff2 ttf

**Comment by mark-cooper** [comment]
I should add that ^ is since: https://github.com/archivesspace/archivesspace/pull/892

**Comment by jambun** [comment]
We've worked through the staff and public interfaces with prefixes enabled and have fixed this and a few other issues we encountered. We would like to hold off on submitting a PR until tomorrow to give it a final check through. Here's our branch if you want to take a look:
https://github.com/hudmol/archivesspace/tree/prefixes

**Comment by lmcglohon** [comment]
I believe this is fixed by https://github.com/archivesspace/archivesspace/pull/1097
