### ISSUE TITLE
URL prefix still seems to have a problem

### ISSUE THREAD

**Issue by lmcglohon** [archivesspace/archivesspace#889]
@marktriggs When we used a URL prefix on the test server (see attached screen shot), the individual records no longer displayed. Instead the welcome page was displaying. Once we took the prefix away and cleared our browsing history, the problem went away. Maybe there is still some places that don't get the prefix?

https://archivesspace.atlassian.net/browse/AR-1566

**Comment by marktriggs** [comment]
Thanks for taking a look @lmcglohon.  Locally I'm finding that things work as expected when I add a prefix to `AppConfig[:public_url]` (which is what I was doing when testing), but not consistently when I use `AppConfig[:public_proxy_url]`.

There are two corresponding prefix configs -- `AppConfig[:public_prefix]` and `AppConfig[:public_proxy_prefix]`, and I think the issues you're seeing stem from those being used inconsistently in the code.  Honestly, I can't see why we need both, so I'll review and try to figure it out.  It seems like they could safely be made synonyms (just for compatibility's sake), since it doesn't really make sense to set them to different things.

**Comment by marktriggs** [comment]
Ah, found a bit of history here: 887df9d3f8a3f7d0980bfec700322cc19cc2fee3.  Will investigate!

**Comment by mark-cooper** [comment]
@lmcglohon @marktriggs I revisited the configuration this morning and went through it more carefully. The frontend error was actually in our configuration so I've cleaned up and reorganized things to make it clearer (it's certainly grown over the years). Right now I don't know there's an issue other than: https://github.com/archivesspace/archivesspace/issues/888

I haven't looked into the purpose of `AppConfig[:public_prefix]` (or the frontend equivalent). I suspect like most we run ArchivesSpace itself without any prefixes, but may prefix at the proxy level (something like: http://as.org]/staff -> http://localhost:8080) so it can be valid for them to be different.

**Comment by mark-cooper** [comment]
@lmcglohon @marktriggs 

Prefixes for public and staff:
http://test.archivesspace.org/public/
http://test.archivesspace.org/staff/

Prefix for staff only:
https://latest.lyrasistechnology.org/
https://latest.lyrasistechnology.org/staff/

No prefixes:
http://public.archivesspace.org/
http://sandbox.archivesspace.org/

**Comment by sdm7g** [comment]
I poked at the ones on test.archivespace.org a bit and didn't see any issues. 
Is this master branch ?  ( I will run some more local tests.  )

**Comment by mark-cooper** [comment]
It's the nightly build of master. So it won't have anything that was merged today until tomorrow.

**Comment by marktriggs** [comment]
Hi @lmcglohon, @sdm7g, @mark-cooper,

@payten and I reviewed the situation with prefixes yesterday, and we have a pull request ready to go.  Here's my attempt to summarize the situation :)

Originally, URL prefixes were set by adding the prefix to the `:frontend_url` and `public_url` config properties.  Doing this flowed on to the `AppConfig[:frontend_prefix]` and `AppConfig[:public_prefix]` properties, and so various places in the code (and in plugins) used those prefix settings to make sure things worked properly.

Back in 2015, this got partially changed in https://github.com/archivesspace/archivesspace/commit/887df9d3f8a3f7d0980bfec700322cc19cc2fee3.  That commit introduced `:frontend_proxy_url` and `:public_proxy_url`, which I'm guessing were intended to allow the system to generate absolute URLs for its public address.  This change also introduced `:frontend_proxy_prefix` and `:public_proxy_prefix`, and changed (some) places to use them.  The documentation (https://github.com/archivesspace/archivesspace/blob/master/README_PREFIX.md) was updated to instruct people to use these new properties.

But in the testing we did yesterday, it seems like the prefix behavior was still inconsistent in the staff and public interfaces.  Lots of places were still using `:frontend_prefix`, and there are presumably plugins out there that were relying on this setting too.  It's also not clear what would happen if `:frontend_prefix` and `:frontend_proxy_prefix` (or their public counterparts) were set to different things.  Madness, probably!

So, we've worked through the staff and public interfaces and made things match what the documentation says to do: put the right URLs (with prefixes) into `:frontend_proxy_url` and `:public_proxy_url`, and we'll do the right thing.  Here's what we've done to make that work:

  * We've made `AppConfig[:frontend_prefix]` an alias for `AppConfig[:frontend_proxy_prefix]`, so you get the same value no matter which you use.  In the core code, we've switched all usages to `AppConfig[:frontend_proxy_prefix]` and any uses of `AppConfig[:frontend_prefix]` will log a warning message.  Same deal for `AppConfig[:public_prefix]` and `AppConfig[:public_proxy_prefix]` too.

  * If someone was theoretically manually setting `AppConfig[:frontend_prefix]` and `AppConfig[:frontend_proxy_prefix]`, they'll now get a warning on startup.  I doubt anyone is doing this, as the documentation doesn't mention them and the comments tell you to leave them alone...

  * We also noticed the public interface was using a different version of the Rails sprockets pipeline to the staff interface.  This added confusion while testing that the prefixes were working correctly, so we've unified those versions now (public now matches what staff was already using)

  * Several places in the public interface were using `AppConfig[:public_url]` when they meant to use the newer `AppConfig[:public_proxy_url]`.  This would have caused `http://localhost/` URLs to be served out in some contexts (like citations), so we've fixed those too.

So the end result of this is that the system should now behave the way the README_PREFIX.md document says it should, and any code in the wild relying on the `AppConfig[:public_url]`  and `AppConfig[:frontend_url]` settings should also reliably work under a prefix.

**Comment by cfitz** [comment]
Hi,
Yes, my vague recollection is there has been a lot of wack-a-mole on this, so not surprised there's a lot of inconsistency here. Sorry!

But just a question, wouldn't it be easier to use jetty to serve up assets? You are already doing precompilation, so the static assets are there. I'm probably missing something, but it feels like configuring jetty to handle the prefix would be ideal. I think I might have mentioned that before => #815 . Not sure you need all that, but something in that vein?

**Comment by marktriggs** [comment]
Hi @cfitz,

The prefix stuff has always been a pain so no foul, of course :)

And yeah, I'd really like to leave Jetty to serve the assets and get it all out of Rails.  The thing that always stopped this was that it wouldn't work for people running under Tomcat, but maybe official support for Tomcat already went away?  I see the documentation is gone out of the README, and I'd definitely be happy to see it go.

I think no matter what happens with asset handling, the above prefix changes still need to be made (issues #806 and #629 both sound like the kind of problems that PR #892 was addressing), but I'll create a new issue to track getting assets out of Rails.

**Comment by lmcglohon** [comment]
Fixed with #892
