### ISSUE TITLE
Tomcat setup script deletes existing Tomcat services

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/archivesspace#90]
The Tomcat configuration script overwrites Tomcat's server.xml file with it's own version. This effectively deletes the 'Catalina' service and disables anything already running under Tomcat. Rather than overwriting this file, the script should instead insert new service instances for the ArchivesSpace webapps into the existing server.xml.

**Comment by trevorthornton** [comment]
Just wanted to follow up on this - looks like the problem persists in version 1.1.1

**Comment by cfitz** [comment]
sorry, this one was on  the backburner...just pushed some updates that will correct this. The script doesn't update any Services with the same name ( like ArchivesSpaceBackend ) and will not touch a server.xml that already has a Connector defined on a port that ASpace needs.

Will be included in next release, but you can download the launch scripts now if you want...
