### ISSUE TITLE
Change config boolean examples

### ISSUE THREAD

**Issue by hietpasd** [archivesspace/archivesspace#918]
Pretty minor but threw me for a loop.  At least in version 2.1, I kept getting DB connection errors.

The config.rb example shows:
_#AppConfig[:allow_unsupported_database] = false
#AppConfig[:allow_non_utf8_mysql_database] = false_

The example output from the error log files suggest you change it to this:
_AppConfig[:allow_unsupported_database] = "true"
AppConfig[:allow_non_utf8_mysql_database] = "true"_

I thought it was odd that it switched from bool to string so I tried first the bool approach
_AppConfig[:allow_unsupported_database] = true
AppConfig[:allow_non_utf8_mysql_database] = true_

and the bool approach ended up not working.  I did what the log suggested and switched it to a string and it worked.

I'd recommend making a change to the config.rb examples to use the correct syntax.

**Comment by lmcglohon** [comment]
Closed because moved to tech-docs repo: https://github.com/archivesspace/tech-docs/issues/15

**Comment by lmcglohon** [comment]
After discussion with the technical documentation team, we decided to move this issue back to the main repo.
