### ISSUE TITLE
Fonts return 404 in PUI under a prefix

### ISSUE THREAD

**Issue by payten** [archivesspace/archivesspace#957]
With all the prefix buzz, I revisited it all and came across a bug whereby the path to custom fonts and font-awesome is incorrect and returns a 404 for the ArchivesSpace PUI.

To replicate, you can use a Docker image to be your proxy (unless you're a lucky ducky and have apache installed already).

ASpace Server IP: 192.168.1.14
Proxy IP (Docker Image): 192.168.99.100

**Setup ArchivesSpace**
Fake a domain:
$ sudo vim /etc/hosts
`192.168.99.100 proxy.payten.com`

$ wget https://github.com/archivesspace/archivesspace/releases/download/v2.1.1/archivesspace-v2.1.1.zip
$ unzip archivesspace-v2.1.1.zip
$ vim archivesspace/config/config.rb
```
AppConfig[:frontend_proxy_url] = 'http://proxy.payten.com/staff/'
AppConfig[:public_proxy_url] = 'http://proxy.payten.com/public/'
```
$ archivesspace/archivesspace.sh

**Setup Apache**
$ docker pull linode/lamp
$ docker run -it --name aspace-proxy lamp
This will give you a shell in the docker instance:
docker$ apt-get update
docker$ apt-get install vim
docker$ vim /etc/apache2/apache2.conf
Add:
```
IncludeOptional mods-available/proxy.load
IncludeOptional mods-available/proxy.conf
IncludeOptional mods-available/proxy_http.load
```
docker$ vim /etc/apache2/mods-available/proxy.conf
```
<IfModule mod_proxy.c>
ProxyPass /staff http://192.168.1.14:8080/staff
ProxyPassReverse /staff http://192.168.1.14:8080/
ProxyPass /public http://192.168.1.14:8081/public
ProxyPassReverse /public http://192.168.1.14:8081/
</IfModule>
```
docker$ apache2ctl restart

**Check in the browser**
Staff interface:
![screen shot 2017-09-04 at 9 04 50 am](https://user-images.githubusercontent.com/608337/30007447-e0de4ef8-9151-11e7-8ab9-78e843ff3e40.png)
Public:
![screen shot 2017-09-04 at 9 20 59 am](https://user-images.githubusercontent.com/608337/30007468-a262daa8-9152-11e7-9e73-fae62e42bb08.png)
Public (with patch provided - see incoming PR):
![screen shot 2017-09-04 at 9 05 04 am](https://user-images.githubusercontent.com/608337/30007446-e0dd935a-9151-11e7-8d6c-30f02384409e.png)

**Comment by lmcglohon** [comment]
Fixed by #958
