### ISSUE TITLE
PUI: External document links broken on digital objects

### ISSUE THREAD

**Issue by cvonkleist** [archivesspace/archivesspace#963]
It seems that external document links are broken in the PUI. They are prepended with the app prefix instead of being linked to directly, even when the external document link is a resolvable URI. This means that an external document URL gets linked as, e.g., `<a href="/http://xyz.org/1234">...</a>`. Clicking on this link causes a 404:

    `ActionController::RoutingError (No route matches [GET] "/http:/dcmny.org/islandora/search")`

I think this is the code responsible:

https://github.com/archivesspace/archivesspace/blob/4cd7f12701cacb7da30a62886131922dc05123db/public/app/views/shared/_present_list.html.erb#L35-L40

In the above snippet, note that the `app_prefix()` method is wrapping the value of the URI.

* * * *

#### External document with link

<img width="880" alt="screen shot 2017-09-11 at 12 24 01 pm" src="https://user-images.githubusercontent.com/20558/30259804-9de31646-96ed-11e7-968e-86c3cb353b32.png">

* * * *

#### Generated HTML

<img width="855" alt="screen shot 2017-09-11 at 12 25 00 pm" src="https://user-images.githubusercontent.com/20558/30259839-c3a1ace4-96ed-11e7-8b2a-2bd1e8bbed04.png">

* * * *

#### 404 error

![screen shot 2017-09-11 at 12 38 09 pm](https://user-images.githubusercontent.com/20558/30259878-19ea1672-96ee-11e7-8364-ecf5812bd68c.png)

**Comment by lmcglohon** [comment]
@cvonkleist Thank you for reporting this problem. It has been fixed in the latest version (v2.1.2) with this pull request - https://github.com/archivesspace/archivesspace/pull/953, so I am going to close this issue.

**Comment by cvonkleist** [comment]
Hi, @lmcglohon. It turns out this bug was fixed in v2.1.2 with #953. I just checked on one of our v2.1.2 instances, and the external document links are working correctly.

I got confused because I still saw the `app_prefix()` method in https://github.com/archivesspace/archivesspace/blob/v2.1.2/public/app/views/shared/_present_list.html.erb, not realizing that the relevant partial is now https://github.com/archivesspace/archivesspace/blob/v2.1.2/public/app/views/shared/_present_list_external_docs.html.erb.

Sorry for the noise! This issue can be closed. Thank you.

**Comment by lmcglohon** [comment]
Thanks @cvonkleist !
