### ISSUE TITLE
Error running setup-database.bat on windows

### ISSUE THREAD

**Issue by ChristineGlew** [archivesspace/archivesspace#967]
I get the attached errors:
[error.txt](https://github.com/archivesspace/archivesspace/files/1299551/error.txt)

**Comment by lmcglohon** [comment]
@ChristineGlew I believe this issue was fixed with the latest release (v2.1.2) that is here: https://github.com/archivesspace/archivesspace/releases/tag/v2.1.2. Please try to install that version and let me know if you are still having the problem.

**Comment by lmcglohon** [comment]
@ChristineGlew that looks like a permissions issue on the MySQL side. From this, https://dev.mysql.com/doc/refman/5.7/en/stored-programs-logging.html. It looks like you need to do something like this:

If you do not want to require function creators to have the SUPER privilege (for example, if all users with the CREATE ROUTINE privilege on your system are experienced application developers), set the global log_bin_trust_function_creators system variable to 1. You can also set this variable by using the --log-bin-trust-function-creators=1 option when starting the server. If binary logging is not enabled, log_bin_trust_function_creators does not apply. SUPER is not required for function creation unless, as described previously, the DEFINER value in the function definition requires it.

**Comment by ChristineGlew** [comment]
Thanks very much that has sorted it

**Comment by lmcglohon** [comment]
@ChristineGlew Great! Thanks for letting me know!
