### ISSUE TITLE
`Failed to clean XML` error when printing PDF from PUI

### ISSUE THREAD

**Issue by cvonkleist** [archivesspace/archivesspace#972]
In ArchivesSpace 2.1.2, some of our collections can't be printed from the PUI. When the PUI user uses the *Print* button to print certain resources, the server gives a `500 Internal Server Error` with the corresponding sort of error message in the logs:

```
RuntimeError (Failed to clean XML: The reference to entity "A." must end with the ';' delimiter.):$
  app/lib/xml_cleaner.rb:31:in `clean'$
  app/models/finding_aid_pdf.rb:93:in `generate'$
  app/controllers/pdf_controller.rb:15:in `resource'$
```

(There is some variation in the exact text of the error message due to differences in record content.)

After looking into the problem, it seems that there might be a bug in one of the ERB partials in the HTML report that becomes the input for the PDF generator. The exception shown above (`Failed to clean XML` raised by the `XMLCleaner` class) is a side effect of the real bug which is that HTML-unsafe characters are emitted in the HTML report.

This is a snippet of the HTML that was generated in one case. Please note the unsafe ampersand in `Correspondence-D.S.S.&A.` on line 45929:

```
 45927 <div class="avoid-break">
 45928     <div class="print-record-border print-record level-4">
 45929         <h3><a class="record-title" id="/repositories/2/archival_objects/1370">Correspondence-D.S.S.&A., 1932-1948</a></h3>
 45930 
 45931                 <div class="container-information">
 45932 
 45933                         Box 376; Folder 9
 45934                             (Mixed Materials)
 45935                 </div>
 45936 
 45937         <div class="indented">
 45938 
 45939             <dl>
 45940 
 45941                     <dt>Date</dt><dd>1932-1948</dd>
 45942 
 45943 
 45944 
 45945          
 45946 
 45947             </dl>
 45948 
 45949         </div>
 45950     </div>
 45951 </div>
```

### The actual bug

I believe the bug is located in the `pdf/_archival_object.html.erb` partial on line 17:

https://github.com/archivesspace/archivesspace/blob/bcfb0f4aeab8079446351a6beaffd043c567dfc4/public/app/views/pdf/_archival_object.html.erb#L15-L20

### Possible fix

I think the `<%== record.display_string %>` (raw output) should be `<%= record.display_string %>` (HTML-safe output).

There are two other occurrences of `<%==` in `_archival_object.html.erb` which are related to note text. Maybe these note fields are allowed to contain HTML, and that's why `<%== note['note_text'] %>` is used, but I'm not sure.

https://github.com/archivesspace/archivesspace/blob/bcfb0f4aeab8079446351a6beaffd043c567dfc4/public/app/views/pdf/_archival_object.html.erb#L54
https://github.com/archivesspace/archivesspace/blob/bcfb0f4aeab8079446351a6beaffd043c567dfc4/public/app/views/pdf/_archival_object.html.erb#L75

* * * * *

Please let me know if I can supply any additional info on this bug. I'm also happy to submit a PR if it's helpful. Thanks!

**Comment by lmcglohon** [comment]
@cvonkleist A pull request would be terrific!
